package org.lerchenflo.schneaggchatv3mp.games.presentation.wordle

/**
 * Solution pool for the German Wordle. Every entry is exactly five A-Z
 * letters — umlauts and ß are avoided instead of expanded, because AE/OE/UE/SS
 * would change the word length. Content lives in code like the other game word
 * lists (Morse, Undercover, German crossword), not in string resources.
 *
 * This is a solution pool, not a dictionary: German guesses are only checked for
 * length, so a valid word missing here is still accepted as a guess.
 */
val germanWordleWords: List<String> = listOf(
    "ABEND", "ABGAS", "ABTEI", "ACKER", "ADERN", "ADLER", "AFFEN", "AGENT",
    "AHORN", "AKKUS", "AKTEN", "AKTIE", "ALARM", "ALBUM", "ALLEE", "ALPEN",
    "ALTAR", "AMPEL", "AMSEL", "ANGEL", "ANGST", "ANKER", "ANRUF", "ANTIK",
    "ANZUG", "APFEL", "ARENA", "ARGON", "ARMEE", "ARTEN", "ASCHE", "ASSEL",
    "ASTER", "ATLAS", "AUGEN", "AUTOR", "AUTOS", "BACKE", "BADEN", "BANDE",
    "BANJO", "BARON", "BASIS", "BATIK", "BAUCH", "BAUER", "BEBEN", "BEERE",
    "BEIGE", "BEILE", "BEINE", "BELAG", "BERGE", "BERUF", "BESEN", "BETEN",
    "BETON", "BEUTE", "BEVOR", "BIBEL", "BIENE", "BIEST", "BINDE", "BIRKE",
    "BIRNE", "BISON", "BITTE", "BLASE", "BLATT", "BLECH", "BLICK", "BLITZ",
    "BLOCK", "BLOND", "BLUES", "BLUME", "BLUSE", "BODEN", "BOGEN", "BOHNE",
    "BOMBE", "BONUS", "BOOTE", "BORKE", "BORTE", "BOSSE", "BOXEN", "BRAND",
    "BRAUN", "BRAUT", "BREIT", "BRETT", "BRIEF", "BRISE", "BROTE", "BRUCH",
    "BRUST", "BUCHE", "BUCHT", "BUDEN", "BUSCH", "BYTES", "CAMPS", "CAPES",
    "CELLO", "CHAOS", "CHEFS", "CHILI", "CHINA", "CHROM", "CIDER", "CLOWN",
    "COACH", "CODES", "COMIC", "CORPS", "COUCH", "CRASH", "CREME", "CREPE",
    "CURRY", "DACHS", "DAMEN", "DAMPF", "DANKE", "DATEI", "DATEN", "DATUM",
    "DAUER", "DECKE", "DEGEN", "DEICH", "DELLE", "DEMUT", "DEPOT", "DERBY",
    "DICHT", "DICKE", "DIEBE", "DIELE", "DIESE", "DINGE", "DIODE", "DISCO",
    "DOCHT", "DOGGE", "DOHLE", "DOLCH", "DONAU", "DOSEN", "DOSIS", "DRAHT",
    "DRAMA", "DRANG", "DROGE", "DRUCK", "DUELL", "DUENE", "DUKAT", "DUNST",
    "DURST", "EBENE", "ECHSE", "ECHTE", "ECKEN", "EDIKT", "EGGEN", "EHREN",
    "EICHE", "EIFER", "EIGEN", "EILIG", "EIMER", "EINER", "EINES", "EISEN",
    "EISIG", "EITEL", "EKLIG", "ELCHE", "ELEND", "ELFEN", "ELITE", "EMAIL",
    "EMSIG", "ENDEN", "ENGEL", "ENKEL", "ENTEN", "ERBEN", "ERBSE", "ERDEN",
    "ERLEN", "ERNST", "ERNTE", "ERSTE", "ESCHE", "ESSAY", "ESSEN", "ESSIG",
    "ETAGE", "ETHIK", "EULEN", "EUROS", "EXAKT", "EXTRA", "FABEL", "FADEN",
    "FAHNE", "FALKE", "FALLE", "FALTE", "FARBE", "FASAN", "FASER", "FAUST",
    "FAXEN", "FEDER", "FEGEN", "FEIER", "FEIGE", "FEILE", "FEINE", "FELLE",
    "FERNE", "FERSE", "FESTE", "FETTE", "FEUER", "FIBEL", "FIGUR", "FILET",
    "FILME", "FINNE", "FINTE", "FIRMA", "FIRST", "FISCH", "FJORD", "FLACH",
    "FLAIR", "FLAUM", "FLECK", "FLIRT", "FLOSS", "FLUCH", "FLUSS", "FOLIE",
    "FONDS", "FORKE", "FORST", "FORUM", "FOTOS", "FRACK", "FRAGE", "FRIST",
    "FUCHS", "FUGEN", "FUNKE", "GABEL", "GABEN", "GALLE", "GANZE", "GARBE",
    "GARDE", "GASSE", "GATTE", "GEBEN", "GEBET", "GEBOT", "GEHEN", "GEIER",
    "GEIGE", "GEIST", "GELEE", "GEMSE", "GENAU", "GENIE", "GENRE", "GERTE",
    "GESTE", "GILDE", "GLANZ", "GLEIS", "GLIED", "GNADE", "GNOME", "GOTIK",
    "GRAMM", "GREIS", "GRIFF", "GRILL", "GROSS", "GRUBE", "GRUND", "GRUSS",
    "GUMMI", "GUNST", "GURKE", "GURTE", "GUTES", "HAARE", "HABEN", "HACKE",
    "HAFEN", "HAFER", "HAGEL", "HAKEN", "HALBE", "HALLE", "HALLO", "HALME",
    "HANDY", "HARFE", "HARKE", "HASEL", "HASEN", "HAUCH", "HAUPT", "HAUSE",
    "HEBEL", "HEBEN", "HECKE", "HEFTE", "HEIDE", "HEISS", "HELLE", "HENNE",
    "HERDE", "HEUTE", "HEXEN", "HIRSE", "HITZE", "HOBBY", "HOBEL", "HOLEN",
    "HONIG", "HORDE", "HOSEN", "HOTEL", "HUMOR", "HUMUS", "HUNDE", "HUPEN",
    "HYMNE", "IDEAL", "IDEEN", "IMAGE", "IMKER", "INDEX", "INDIZ", "INNEN",
    "INPUT", "INSEL", "INTIM", "IONEN", "IRREN", "ISLAM", "JACKE", "JAGEN",
    "JAHRE", "JEANS", "JETZT", "JOKER", "JOULE", "JUBEL", "JUNGE", "JUNGS",
    "JUNTA", "JUWEL", "KABEL", "KADER", "KAJAK", "KAKAO", "KAMEL", "KAMIN",
    "KAMPF", "KANAL", "KANNE", "KANON", "KANTE", "KARMA", "KARTE", "KASSE",
    "KATER", "KATZE", "KAUEN", "KEGEL", "KEHLE", "KELCH", "KENIA", "KERBE",
    "KERNE", "KERZE", "KETTE", "KILOS", "KINOS", "KIOSK", "KIPPE", "KISTE",
    "KIWIS", "KLAGE", "KLAMM", "KLANG", "KLAUE", "KLEID", "KLEIE", "KLICK",
    "KLIMA", "KLOTZ", "KNABE", "KNAST", "KNIFF", "KNOPF", "KOALA", "KOBRA",
    "KODEX", "KOHLE", "KOKON", "KOLIK", "KOMET", "KOMIK", "KOMMA", "KONTO",
    "KONUS", "KOPIE", "KORAN", "KRACH", "KRAFT", "KRAKE", "KRANZ", "KRAUT",
    "KREBS", "KREIS", "KREUZ", "KRIEG", "KRIMI", "KRONE", "KRUMM", "KUGEL",
    "KUNDE", "KUNST", "KUPPE", "KURSE", "KURVE", "KUTTE", "LACHE", "LACHS",
    "LADEN", "LAGER", "LAICH", "LAKEN", "LAMAS", "LAMPE", "LANGE", "LANZE",
    "LARVE", "LASER", "LATTE", "LAUBE", "LAUGE", "LAUNE", "LAUTE", "LEBEN",
    "LEBER", "LEDER", "LEDIG", "LEGEN", "LEHNE", "LEHRE", "LEINE", "LESEN",
    "LEUTE", "LEVEL", "LICHT", "LIEBE", "LIEGE", "LILIE", "LIMIT", "LINDE",
    "LINIE", "LINKE", "LINSE", "LIPPE", "LISTE", "LITER", "LOBBY", "LOBEN",
    "LOCKE", "LODEN", "LOGEN", "LOGIK", "LOKAL", "LOTSE", "LOTTO", "LUCHS",
    "LUNGE", "LUPEN", "LUXUS", "LYRIK", "MACHT", "MADEN", "MAGEN", "MAGER",
    "MAGIE", "MAGMA", "MAKEL", "MAKRO", "MALEN", "MALER", "MANGO", "MAPPE",
    "MARGE", "MARKE", "MARKT", "MASKE", "MASSE", "MATTE", "MAUER", "MEILE",
    "MEINE", "MEISE", "MENGE", "MENUE", "MESSE", "METER", "MIENE", "MIETE",
    "MILCH", "MIMIK", "MINEN", "MINUS", "MITTE", "MIXER", "MOBIL", "MODEL",
    "MODUS", "MOLCH", "MOLKE", "MONAT", "MONDE", "MOOSE", "MOPED", "MORAL",
    "MOTIV", "MOTOR", "MOTTE", "MOTTO", "MULDE", "MUMIE", "MUMPS", "MUSEN",
    "MUSIK", "MUTIG", "NABEL", "NACHT", "NACKT", "NADEL", "NAGEL", "NAGEN",
    "NAHEN", "NAMEN", "NARBE", "NASEN", "NATUR", "NEBEL", "NEBEN", "NEFFE",
    "NEIGE", "NELKE", "NETTE", "NETZE", "NEUES", "NICHT", "NIERE", "NIMMT",
    "NIXEN", "NOBEL", "NONNE", "NOTAR", "NOTEN", "NOTIZ", "NUDEL", "NYLON",
    "OASEN", "OBERE", "OCHSE", "OFFEN", "OHREN", "OKTAV", "OLIVE", "ONKEL",
    "OPALE", "OPERN", "OPFER", "OPTIK", "ORBIT", "ORDEN", "ORDER", "ORGAN",
    "ORGEL", "ORKAN", "OSTEN", "OTTER", "OVALE", "OZEAN", "PAKET", "PALME",
    "PANDA", "PANEL", "PANIK", "PAPPE", "PARKA", "PARKS", "PARTY", "PASTA",
    "PASTE", "PATEN", "PAUKE", "PAUSE", "PEDAL", "PEGEL", "PELZE", "PERLE",
    "PFAND", "PFEIL", "PFERD", "PFLUG", "PFOTE", "PFUND", "PHASE", "PIANO",
    "PILOT", "PILZE", "PINIE", "PIRAT", "PISTE", "PIZZA", "PLAGE", "PLANE",
    "PLATZ", "PLUTO", "POKAL", "POKER", "POLEN", "POLKA", "PONYS", "PORTO",
    "POSEN", "PREIS", "PRIMA", "PRINZ", "PRISE", "PROBE", "PROSA", "PROST",
    "PUDEL", "PUDER", "PULLI", "PUMAS", "PUMPE", "PUNKT", "PUPPE", "PUTEN",
    "QUALM", "QUARK", "QUARZ", "QUELL", "QUERE", "QUITT", "QUOTE", "RABEN",
    "RACHE", "RADAR", "RADIO", "RAMPE", "RANKE", "RASEN", "RASSE", "RASUR",
    "RATEN", "RATIO", "RATTE", "RAUCH", "RAUPE", "RAUTE", "REBEN", "RECHT",
    "REDEN", "REGAL", "REGEL", "REGEN", "REGIE", "REICH", "REIFE", "REIHE",
    "REISE", "RENTE", "RESTE", "REUSE", "REVUE", "RHEIN", "RIEGE", "RIESE",
    "RINDE", "RINGE", "RIPPE", "ROBBE", "ROBEN", "RODEO", "ROGEN", "ROLLE",
    "ROMAN", "ROSEN", "ROTOR", "ROUTE", "RUBEL", "RUBIN", "RUDEL", "RUDER",
    "RUFEN", "RUGBY", "RUHIG", "RUINE", "RUMBA", "RUMPF", "RUNDE", "RUNEN",
    "RUSSE", "RUTEN", "SACHE", "SAGEN", "SAHNE", "SAITE", "SALAT", "SALBE",
    "SALDO", "SALON", "SALZE", "SAMBA", "SAMEN", "SATAN", "SATIN", "SAUCE",
    "SAUER", "SAUNA", "SCHAF", "SCHAL", "SCHAR", "SCHAU", "SCHUH", "SEELE",
    "SEGEL", "SEGEN", "SEHEN", "SEIDE", "SEIFE", "SEILE", "SEITE", "SEKTE",
    "SENAT", "SENSE", "SERIE", "SERUM", "SICHT", "SIEBE", "SIEGE", "SIGMA",
    "SILBE", "SINNE", "SIRUP", "SITTE", "SITZE", "SKALA", "SKALP", "SKIER",
    "SOCKE", "SOFAS", "SOHLE", "SOLAR", "SONDE", "SONNE", "SORGE", "SORTE",
    "SOSSE", "SPALT", "SPECK", "SPEER", "SPIEL", "SPORE", "SPORT", "SPRAY",
    "SPREE", "SPULE", "STAAT", "STADT", "STAHL", "STALL", "STAMM", "STAND",
    "STAUB", "STEIL", "STEIN", "STERN", "STICH", "STIEL", "STIER", "STIFT",
    "STIRN", "STOCK", "STOFF", "STOLZ", "STOPP", "STOSS", "STROH", "STROM",
    "STUBE", "STUFE", "STUHL", "STURM", "STURZ", "STUTE", "SUCHE", "SUCHT",
    "SUITE", "SUMME", "SUMPF", "SUPPE", "SUSHI", "SZENE", "TABAK", "TADEL",
    "TAFEL", "TALAR", "TALER", "TANGO", "TANKS", "TANNE", "TANTE", "TARIF",
    "TASSE", "TASTE", "TATEN", "TAUBE", "TAXIS", "TEICH", "TEILE", "TEMPO",
    "TENOR", "TESTS", "TEUER", "TEXTE", "THEMA", "THRON", "TIARA", "TIEFE",
    "TIERE", "TIGER", "TINTE", "TIPPS", "TISCH", "TITAN", "TITEL", "TOAST",
    "TOBEN", "TONER", "TONNE", "TORTE", "TOTAL", "TRAGE", "TRANK", "TRAUM",
    "TREND", "TREUE", "TRICK", "TRIEB", "TROLL", "TROPF", "TROTZ", "TRUHE",
    "TRUPP", "TUBEN", "TULPE", "TUMOR", "TURBO", "TUTEN", "TYPEN", "UEBEL",
    "UEBER", "UHREN", "ULKIG", "ULMEN", "UMBAU", "UMZUG", "UNFUG", "UNION",
    "UNKEN", "UNTEN", "UNTER", "URALT", "URNEN", "VASEN", "VATER", "VEGAN",
    "VELOS", "VENEN", "VENUS", "VERSE", "VIDEO", "VIELE", "VILLA", "VINYL",
    "VIOLA", "VIREN", "VIRUS", "VISUM", "VITAL", "VOGEL", "VORAB", "VORNE",
    "VOTUM", "WAAGE", "WACHE", "WACHS", "WADEN", "WAFFE", "WAGEN", "WAHRE",
    "WALZE", "WANGE", "WANNE", "WANZE", "WAREN", "WARTE", "WATTE", "WEBEN",
    "WEDEL", "WEGEN", "WEHEN", "WEIDE", "WEIHE", "WEINE", "WEISE", "WEISS",
    "WELLE", "WELPE", "WENDE", "WENIG", "WERFT", "WERKE", "WERTE", "WESEN",
    "WESPE", "WESTE", "WETTE", "WIEGE", "WIESE", "WINDE", "WIPPE", "WITWE",
    "WITZE", "WOCHE", "WODKA", "WOLKE", "WOLLE", "WONNE", "WORTE", "WUCHS",
    "WUNDE", "WURST", "XENON", "YACHT", "YETIS", "YOGIS", "ZANGE", "ZEBRA",
    "ZECKE", "ZEDER", "ZEHEN", "ZEILE", "ZELLE", "ZELTE", "ZENIT", "ZEUGE",
    "ZIEGE", "ZIELE", "ZINKE", "ZINNE", "ZITAT", "ZOBEL", "ZONEN", "ZUNFT",
    "ZUNGE", "ZWANG", "ZWECK", "ZWEIG", "ZWERG", "ZWIRN",
)
