package org.lerchenflo.schneaggchatv3mp.games.presentation.cchallenge

/**
 * A line of [CSnippet.lines] that the fill-the-blank challenge may hide, with wrong
 * alternatives. Every distractor must change what the code does (or not compile),
 * never be an equivalent rewrite.
 */
class CBlank(val line: Int, val distractors: List<String>)

/**
 * One correct, compiling piece of C. The challenge generators derive all syntax,
 * fill-the-blank and line-order challenges from these. [orderRange] is a block whose
 * lines can only go in one order - otherwise a correct answer would be rejected.
 */
class CSnippet(
    val lines: List<String>,
    val blanks: List<CBlank>,
    val orderRange: IntRange,
)

// Adding a snippet: keep it short enough for a phone (about 15 lines), make sure it compiles,
// and pick the order range so that no other order would also be correct.
internal val C_SNIPPETS: List<CSnippet> = listOf(
    CSnippet(
        lines = listOf(
            "// Sort the array ascending (bubble sort)",
            "void bubbleSort(int a[], int n) {",
            "    for (int i = 0; i < n - 1; i++) {",
            "        for (int j = 0; j < n - 1 - i; j++) {",
            "            if (a[j] > a[j + 1]) {",
            "                int tmp = a[j];",
            "                a[j] = a[j + 1];",
            "                a[j + 1] = tmp;",
            "            }",
            "        }",
            "    }",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("for (int j = 0; j <= n - i; j++) {", "for (int j = 1; j < n - 1 - i; j--) {", "for (int j = i; j < n; j++) {")),
            CBlank(4, listOf("if (a[j] < a[j + 1]) {", "if (a[j] > a[j - 1]) {", "if (a[j] = a[j + 1]) {")),
            CBlank(7, listOf("a[j] = tmp;", "tmp = a[j + 1];", "a[j + 1] = a[j];")),
        ),
        orderRange = 5..7,
    ),
    CSnippet(
        lines = listOf(
            "// Print the prime factors of n, e.g. 12 -> 2 2 3",
            "void primeFactors(int n) {",
            "    for (int p = 2; p * p <= n; p++) {",
            "        while (n % p == 0) {",
            "            printf(\"%d \", p);",
            "            n /= p;",
            "        }",
            "    }",
            "    if (n > 1) {",
            "        printf(\"%d\", n);",
            "    }",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("if (n % p == 0) {", "while (p % n == 0) {", "while (n / p == 0) {")),
            CBlank(5, listOf("n -= p;", "p /= n;", "n %= p;")),
            CBlank(8, listOf("if (n > 2) {", "if (n == 1) {", "if (n < p) {")),
        ),
        orderRange = 1..4,
    ),
    CSnippet(
        lines = listOf(
            "// Greatest common divisor (Euclid)",
            "int gcd(int a, int b) {",
            "    while (b != 0) {",
            "        int r = a % b;",
            "        a = b;",
            "        b = r;",
            "    }",
            "    return a;",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("while (a != 0) {", "while (b == 0) {", "while (a > b) {")),
            CBlank(3, listOf("int r = a / b;", "int r = b % a;", "int r = a * b;")),
            CBlank(7, listOf("return b;", "return a % b;", "return a * b;")),
        ),
        orderRange = 3..5,
    ),
    CSnippet(
        lines = listOf(
            "// n! computed recursively",
            "long factorial(int n) {",
            "    if (n <= 1) {",
            "        return 1;",
            "    }",
            "    return n * factorial(n - 1);",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("if (n == 2) {", "if (n >= 1) {", "if (n < 0) {")),
            CBlank(5, listOf("return n * factorial(n);", "return factorial(n - 1);", "return n + factorial(n - 1);")),
        ),
        orderRange = 2..5,
    ),
    CSnippet(
        lines = listOf(
            "// n-th Fibonacci number (0, 1, 1, 2, 3, 5, ...)",
            "int fibonacci(int n) {",
            "    int a = 0, b = 1;",
            "    for (int i = 0; i < n; i++) {",
            "        int next = a + b;",
            "        a = b;",
            "        b = next;",
            "    }",
            "    return a;",
            "}",
        ),
        blanks = listOf(
            CBlank(4, listOf("int next = a * b;", "int next = b - a;", "int next = a + 1;")),
            CBlank(5, listOf("b = a;", "a = next;", "a = a + b;")),
            CBlank(6, listOf("next = b;", "b = a;", "b = next + a;")),
        ),
        orderRange = 4..6,
    ),
    CSnippet(
        lines = listOf(
            "// Returns 1 if n is a prime number, otherwise 0",
            "int isPrime(int n) {",
            "    if (n < 2) {",
            "        return 0;",
            "    }",
            "    for (int i = 2; i * i <= n; i++) {",
            "        if (n % i == 0) {",
            "            return 0;",
            "        }",
            "    }",
            "    return 1;",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("if (n < 0) {", "if (n > 2) {", "if (n == 2) {")),
            CBlank(5, listOf("for (int i = 1; i * i <= n; i++) {", "for (int i = 2; i * i < n; i++) {", "for (int i = 2; i <= n; i++) {")),
            CBlank(6, listOf("if (i % n == 0) {", "if (n % i != 0) {", "if (n / i == 0) {")),
        ),
        orderRange = 5..9,
    ),
    CSnippet(
        lines = listOf(
            "// Largest value in the array",
            "int maxValue(int a[], int n) {",
            "    int max = a[0];",
            "    for (int i = 1; i < n; i++) {",
            "        if (a[i] > max) {",
            "            max = a[i];",
            "        }",
            "    }",
            "    return max;",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("int max = 0;", "int max = a[n];", "int max = n;")),
            CBlank(4, listOf("if (a[i] < max) {", "if (max > a[i]) {", "if (a[i] > a[0]) {")),
            CBlank(5, listOf("a[i] = max;", "max = i;", "max += a[i];")),
        ),
        orderRange = 2..6,
    ),
    CSnippet(
        lines = listOf(
            "// Average of the array values",
            "double average(int a[], int n) {",
            "    int sum = 0;",
            "    for (int i = 0; i < n; i++) {",
            "        sum += a[i];",
            "    }",
            "    return (double) sum / n;",
            "}",
        ),
        blanks = listOf(
            CBlank(4, listOf("sum = a[i];", "sum += i;", "a[i] += sum;")),
            CBlank(6, listOf("return sum / n;", "return (double) (sum / n);", "return (double) n / sum;")),
        ),
        orderRange = 2..5,
    ),
    CSnippet(
        lines = listOf(
            "// Reverse the array in place",
            "void reverse(int a[], int n) {",
            "    for (int i = 0; i < n / 2; i++) {",
            "        int tmp = a[i];",
            "        a[i] = a[n - 1 - i];",
            "        a[n - 1 - i] = tmp;",
            "    }",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("for (int i = 0; i < n; i++) {", "for (int i = 1; i < n / 2; i++) {", "for (int i = 0; i <= n; i++) {")),
            CBlank(4, listOf("a[i] = a[n - i];", "a[i] = a[i + 1];", "a[n - 1 - i] = a[i];")),
        ),
        orderRange = 3..5,
    ),
    CSnippet(
        lines = listOf(
            "// Length of a string without strlen()",
            "int length(const char *s) {",
            "    int len = 0;",
            "    while (s[len] != '\\0') {",
            "        len++;",
            "    }",
            "    return len;",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("while (s[len] == '\\0') {", "while (s != '\\0') {", "while (len != '\\0') {")),
            CBlank(4, listOf("s++;", "len--;", "len = 1;")),
        ),
        orderRange = 2..5,
    ),
    CSnippet(
        lines = listOf(
            "// Returns 1 if the string reads the same backwards",
            "int isPalindrome(const char *s, int len) {",
            "    int left = 0;",
            "    int right = len - 1;",
            "    while (left < right) {",
            "        if (s[left] != s[right]) {",
            "            return 0;",
            "        }",
            "        left++;",
            "        right--;",
            "    }",
            "    return 1;",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("int right = len;", "int right = 0;", "int right = len + 1;")),
            CBlank(5, listOf("if (s[left] == s[right]) {", "if (left != right) {", "if (s[left] != s[left + 1]) {")),
            CBlank(9, listOf("right++;", "left--;", "right = left;")),
        ),
        orderRange = 4..7,
    ),
    CSnippet(
        lines = listOf(
            "// Index of x in the array, or -1 if missing",
            "int indexOf(int a[], int n, int x) {",
            "    for (int i = 0; i < n; i++) {",
            "        if (a[i] == x) {",
            "            return i;",
            "        }",
            "    }",
            "    return -1;",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("if (a[i] = x) {", "if (i == x) {", "if (a[x] == i) {")),
            CBlank(4, listOf("return a[i];", "return x;", "break;")),
            CBlank(7, listOf("return i;", "return 0;", "return n;")),
        ),
        orderRange = 2..6,
    ),
    CSnippet(
        lines = listOf(
            "// Index of x in the sorted array, or -1",
            "int binarySearch(int a[], int n, int x) {",
            "    int lo = 0, hi = n - 1;",
            "    while (lo <= hi) {",
            "        int mid = lo + (hi - lo) / 2;",
            "        if (a[mid] == x) return mid;",
            "        if (a[mid] < x) lo = mid + 1;",
            "        else hi = mid - 1;",
            "    }",
            "    return -1;",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("while (lo < hi) {", "while (lo >= hi) {", "while (lo != x) {")),
            CBlank(4, listOf("int mid = (hi - lo) / 2;", "int mid = lo + hi;", "int mid = hi / 2;")),
            CBlank(6, listOf("if (a[mid] > x) lo = mid + 1;", "if (a[mid] < x) lo = mid;", "if (a[mid] < x) hi = mid - 1;")),
        ),
        orderRange = 3..5,
    ),
    CSnippet(
        lines = listOf(
            "// base raised to exp (exp >= 0)",
            "long power(int base, int exp) {",
            "    long result = 1;",
            "    for (int i = 0; i < exp; i++) {",
            "        result *= base;",
            "    }",
            "    return result;",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("long result = 0;", "long result = base;", "long result = exp;")),
            CBlank(4, listOf("result *= exp;", "result += base;", "result = base * i;")),
        ),
        orderRange = 2..5,
    ),
    CSnippet(
        lines = listOf(
            "// Sum of the decimal digits of n (n >= 0)",
            "int digitSum(int n) {",
            "    int sum = 0;",
            "    while (n > 0) {",
            "        sum += n % 10;",
            "        n /= 10;",
            "    }",
            "    return sum;",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("while (n > 10) {", "while (n < 0) {", "while (sum > 0) {")),
            CBlank(4, listOf("sum += n / 10;", "sum += n;", "sum = n % 10;")),
            CBlank(5, listOf("n %= 10;", "n -= 10;", "n = sum;")),
        ),
        orderRange = 2..6,
    ),
    CSnippet(
        lines = listOf(
            "// Swap two ints through pointers",
            "void swap(int *a, int *b) {",
            "    int tmp = *a;",
            "    *a = *b;",
            "    *b = tmp;",
            "}",
            "",
            "int main(void) {",
            "    int x = 1, y = 2;",
            "    swap(&x, &y);",
            "    printf(\"%d %d\\n\", x, y);",
            "    return 0;",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("int tmp = a;", "int tmp = *b;", "int tmp = &a;")),
            CBlank(4, listOf("b = tmp;", "*b = *a;", "tmp = *b;")),
            CBlank(9, listOf("swap(x, y);", "swap(*x, *y);", "swap(&x, y);")),
        ),
        orderRange = 2..4,
    ),
    CSnippet(
        lines = listOf(
            "// Convert a string to upper case in place",
            "void toUpper(char *s) {",
            "    for (int i = 0; s[i] != '\\0'; i++) {",
            "        if (s[i] >= 'a' && s[i] <= 'z') {",
            "            s[i] = s[i] - 'a' + 'A';",
            "        }",
            "    }",
            "}",
        ),
        blanks = listOf(
            CBlank(2, listOf("for (int i = 0; s[i] == '\\0'; i++) {", "for (int i = 0; i != '\\0'; i++) {", "for (int i = 1; s[i] != '\\0'; i++) {")),
            CBlank(3, listOf("if (s[i] >= 'a' || s[i] <= 'z') {", "if (s[i] >= 'A' && s[i] <= 'Z') {", "if (s[i] > 'a' && s[i] < 'z') {")),
            CBlank(4, listOf("s[i] = s[i] + 'a' - 'A';", "s[i] = 'A';", "s[i] = s[i] - 'A';")),
        ),
        orderRange = 2..6,
    ),
    CSnippet(
        lines = listOf(
            "// Sort the array ascending (selection sort)",
            "void selectionSort(int a[], int n) {",
            "    for (int i = 0; i < n - 1; i++) {",
            "        int min = i;",
            "        for (int j = i + 1; j < n; j++) {",
            "            if (a[j] < a[min]) min = j;",
            "        }",
            "        int tmp = a[i];",
            "        a[i] = a[min];",
            "        a[min] = tmp;",
            "    }",
            "}",
        ),
        blanks = listOf(
            CBlank(3, listOf("int min = 0;", "int min = a[i];", "int min = n;")),
            CBlank(4, listOf("for (int j = 0; j < i; j++) {", "for (int j = i + 1; j <= n; j++) {", "for (int j = i; j < n - 1; j++) {")),
            CBlank(5, listOf("if (a[j] > a[min]) min = j;", "if (a[j] < a[min]) j = min;", "if (a[j] < min) min = j;")),
        ),
        orderRange = 7..9,
    ),
    CSnippet(
        lines = listOf(
            "#include <stdio.h>",
            "",
            "int main(void) {",
            "    int n, count = 0;",
            "    scanf(\"%d\", &n);",
            "    for (int i = 1; i <= n; i++) {",
            "        if (i % 2 == 0) {",
            "            count++;",
            "        }",
            "    }",
            "    printf(\"%d even numbers\\n\", count);",
            "    return 0;",
            "}",
        ),
        blanks = listOf(
            CBlank(4, listOf("scanf(\"%d\", n);", "scanf(\"%s\", &n);", "scanf(\"%d\", &count);")),
            CBlank(6, listOf("if (i / 2 == 0) {", "if (i % 2 == 1) {", "if (i % 2) {")),
            CBlank(10, listOf("printf(\"%d even numbers\\n\", n);", "printf(\"%d even numbers\\n\", &count);", "printf(\"%d even numbers\\n\", i);")),
        ),
        orderRange = 5..9,
    ),
    CSnippet(
        lines = listOf(
            "// Print all primes below 50 (sieve of Eratosthenes)",
            "int main(void) {",
            "    int isComposite[50] = {0};",
            "    for (int i = 2; i < 50; i++) {",
            "        if (isComposite[i]) continue;",
            "        printf(\"%d \", i);",
            "        for (int j = i * i; j < 50; j += i) {",
            "            isComposite[j] = 1;",
            "        }",
            "    }",
            "    return 0;",
            "}",
        ),
        blanks = listOf(
            CBlank(4, listOf("if (!isComposite[i]) continue;", "if (isComposite[i]) break;", "if (isComposite[i + 1]) continue;")),
            CBlank(6, listOf("for (int j = i * i; j < 50; j++) {", "for (int j = i * i; j < 50; j *= i) {", "for (int j = i * i; j > 50; j += i) {")),
            CBlank(7, listOf("isComposite[i] = 1;", "isComposite[j] = 0;", "j = 1;")),
        ),
        orderRange = 3..5,
    ),
)
