package org.lerchenflo.schneaggchatv3mp.games.presentation.undercover

data class UndercoverWordPair(
    val civilianWord: String,
    val undercoverWord: String
)

val UNDERCOVER_WORD_PAIRS: List<UndercoverWordPair> = listOf(
    UndercoverWordPair(civilianWord = "Dog", undercoverWord = "Cat"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Burger"),
    UndercoverWordPair(civilianWord = "Beach", undercoverWord = "Mountain"),
    UndercoverWordPair(civilianWord = "Coffee", undercoverWord = "Tea"),
    UndercoverWordPair(civilianWord = "Car", undercoverWord = "Bus"),
    UndercoverWordPair(civilianWord = "Sun", undercoverWord = "Moon"),
    UndercoverWordPair(civilianWord = "Banana", undercoverWord = "Apple"),
    UndercoverWordPair(civilianWord = "Perfume", undercoverWord = "Deodorant"),
    UndercoverWordPair(civilianWord = "Adidas", undercoverWord = "Nike"),
    UndercoverWordPair(civilianWord = "backpack", undercoverWord = "suitcase"),
    UndercoverWordPair(civilianWord = "jacuzzi", undercoverWord = "sauna"),
    UndercoverWordPair(civilianWord = "sneakers", undercoverWord = "sandals"),
    UndercoverWordPair(civilianWord = "sunglasses", undercoverWord = "eyeglasses"),
    UndercoverWordPair(civilianWord = "piano", undercoverWord = "guitar"),
    UndercoverWordPair(civilianWord = "cruise", undercoverWord = "safari"),
    UndercoverWordPair(civilianWord = "sushi", undercoverWord = "pizza"),
    UndercoverWordPair(civilianWord = "hamburger", undercoverWord = "hotdog"),
    UndercoverWordPair(civilianWord = "chocolate", undercoverWord = "vanilla"),
    UndercoverWordPair(civilianWord = "beer", undercoverWord = "wine"),
    UndercoverWordPair(civilianWord = "whiskey", undercoverWord = "vodka"),
    UndercoverWordPair(civilianWord = "milk", undercoverWord = "juice"),
    UndercoverWordPair(civilianWord = "bread", undercoverWord = "butter"),
    UndercoverWordPair(civilianWord = "rice", undercoverWord = "pasta"),
    UndercoverWordPair(civilianWord = "chicken", undercoverWord = "beef"),
    UndercoverWordPair(civilianWord = "apple", undercoverWord = "orange"),
    UndercoverWordPair(civilianWord = "banana", undercoverWord = "strawberry"),
    UndercoverWordPair(civilianWord = "carrot", undercoverWord = "broccoli"),
    UndercoverWordPair(civilianWord = "potato", undercoverWord = "tomato"),
    UndercoverWordPair(civilianWord = "onion", undercoverWord = "garlic"),
    UndercoverWordPair(civilianWord = "salt", undercoverWord = "pepper"),
    UndercoverWordPair(civilianWord = "sugar", undercoverWord = "honey"),
    UndercoverWordPair(civilianWord = "water", undercoverWord = "soda"),
    UndercoverWordPair(civilianWord = "Apple", undercoverWord = "Microsoft"),
    UndercoverWordPair(civilianWord = "Google", undercoverWord = "Facebook"),
    UndercoverWordPair(civilianWord = "Amazon", undercoverWord = "Netflix"),
    UndercoverWordPair(civilianWord = "Pancake", undercoverWord = "Doughnut"),
    UndercoverWordPair(civilianWord = "Ice cream", undercoverWord = "Cake"),
    UndercoverWordPair(civilianWord = "McDonalds", undercoverWord = "KFC"),
    UndercoverWordPair(civilianWord = "Car", undercoverWord = "Bike"),
    UndercoverWordPair(civilianWord = "virus", undercoverWord = "bacteria"),
    UndercoverWordPair(civilianWord = "Lord of the rings", undercoverWord = "Hobbit"),
    UndercoverWordPair(civilianWord = "Harry Potter", undercoverWord = "Lord Voldemort"),
    UndercoverWordPair(civilianWord = "Superman", undercoverWord = "Batman"),
    UndercoverWordPair(civilianWord = "Spiderman", undercoverWord = "Ironman"),
    UndercoverWordPair(civilianWord = "Captain America", undercoverWord = "Thor"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Pasta"),
    UndercoverWordPair(civilianWord = "Football", undercoverWord = "Basketball"),
    UndercoverWordPair(civilianWord = "Music", undercoverWord = "Dancing"),
    UndercoverWordPair(civilianWord = "Dog", undercoverWord = "Wolf"),
    UndercoverWordPair(civilianWord = "Apple", undercoverWord = "Pear"),
    UndercoverWordPair(civilianWord = "Car", undercoverWord = "Truck"),
    UndercoverWordPair(civilianWord = "Pencil", undercoverWord = "Pen"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Lasagna"),
    UndercoverWordPair(civilianWord = "Facebook", undercoverWord = "Instagram"),
    UndercoverWordPair(civilianWord = "Sunglasses", undercoverWord = "Goggles"),
    UndercoverWordPair(civilianWord = "Laptop", undercoverWord = "Tablet"),
    UndercoverWordPair(civilianWord = "Doctor", undercoverWord = "Surgeon"),
    UndercoverWordPair(civilianWord = "Bitcoin", undercoverWord = "Ethereum"),
    UndercoverWordPair(civilianWord = "Watch", undercoverWord = "Ring"),
    UndercoverWordPair(civilianWord = "Bomb", undercoverWord = "Gun"),
    UndercoverWordPair(civilianWord = "Einstein", undercoverWord = "Newton"),
    UndercoverWordPair(civilianWord = "Shirt", undercoverWord = "Sweater"),
    UndercoverWordPair(civilianWord = "Soccer", undercoverWord = "Rugby"),
    UndercoverWordPair(civilianWord = "Plane", undercoverWord = "Helicopter"),
    UndercoverWordPair(civilianWord = "River", undercoverWord = "Lake"),
    UndercoverWordPair(civilianWord = "Ocean", undercoverWord = "River"),
    UndercoverWordPair(civilianWord = "Teacher", undercoverWord = "Professor"),
    UndercoverWordPair(civilianWord = "Bicycle", undercoverWord = "Motorcycle"),
    UndercoverWordPair(civilianWord = "Salt", undercoverWord = "Sugar"),
    UndercoverWordPair(civilianWord = "Knife", undercoverWord = "Scissors"),
    UndercoverWordPair(civilianWord = "Chair", undercoverWord = "Bench"),
    UndercoverWordPair(civilianWord = "Castle", undercoverWord = "House"),
    UndercoverWordPair(civilianWord = "Train", undercoverWord = "Bus"),
    UndercoverWordPair(civilianWord = "Mirror", undercoverWord = "window pane"),
    UndercoverWordPair(civilianWord = "Mouse", undercoverWord = "Rat"),
    UndercoverWordPair(civilianWord = "Cucumber", undercoverWord = "Zucchini"),
    UndercoverWordPair(civilianWord = "Strawberry", undercoverWord = "Raspberry"),
    UndercoverWordPair(civilianWord = "Banana", undercoverWord = "Plantain"),
    UndercoverWordPair(civilianWord = "Coconut", undercoverWord = "Pineapple"),
    UndercoverWordPair(civilianWord = "Dragon", undercoverWord = "Dinosaur"),
    UndercoverWordPair(civilianWord = "Ghost", undercoverWord = "Zombie"),
    UndercoverWordPair(civilianWord = "Chef", undercoverWord = "Kitchen counter"),
    UndercoverWordPair(civilianWord = "Shovel", undercoverWord = "Axe"),
    UndercoverWordPair(civilianWord = "Pyramid", undercoverWord = "Temple"),
    UndercoverWordPair(civilianWord = "Volcano", undercoverWord = "Mountain"),
    UndercoverWordPair(civilianWord = "Desert", undercoverWord = "Sand"),
    UndercoverWordPair(civilianWord = "Cloud", undercoverWord = "Fog"),
    UndercoverWordPair(civilianWord = "Snow", undercoverWord = "Hail"),
    UndercoverWordPair(civilianWord = "Detective", undercoverWord = "Criminal"),
    UndercoverWordPair(civilianWord = "Jungle", undercoverWord = "Forest"),
    UndercoverWordPair(civilianWord = "Clock", undercoverWord = "Watch"),
    UndercoverWordPair(civilianWord = "Bread", undercoverWord = "Toast"),
    UndercoverWordPair(civilianWord = "Painting", undercoverWord = "Sketch"),
    UndercoverWordPair(civilianWord = "Umbrella", undercoverWord = "Parasol"),
    UndercoverWordPair(civilianWord = "Suit", undercoverWord = "necktie"),
    UndercoverWordPair(civilianWord = "Socks", undercoverWord = "Stockings"),
    UndercoverWordPair(civilianWord = "Belt", undercoverWord = "Jeans"),
    UndercoverWordPair(civilianWord = "Crown", undercoverWord = "Hat"),
    UndercoverWordPair(civilianWord = "Ballet", undercoverWord = "Hip Hop"),
    UndercoverWordPair(civilianWord = "Parrot", undercoverWord = "Crow"),
    UndercoverWordPair(civilianWord = "Bat", undercoverWord = "Owl"),
    UndercoverWordPair(civilianWord = "Candle", undercoverWord = "Lantern"),
    UndercoverWordPair(civilianWord = "Library", undercoverWord = "University"),
    UndercoverWordPair(civilianWord = "Museum", undercoverWord = "Gallery"),
    UndercoverWordPair(civilianWord = "Radio", undercoverWord = "Podcast"),
    UndercoverWordPair(civilianWord = "online news", undercoverWord = "Newspaper"),
    UndercoverWordPair(civilianWord = "Pen", undercoverWord = "Paper"),
    UndercoverWordPair(civilianWord = "Moon", undercoverWord = "Sun"),
    UndercoverWordPair(civilianWord = "Tennis", undercoverWord = "Badminton"),
    UndercoverWordPair(civilianWord = "Skiing", undercoverWord = "Snow"),
    UndercoverWordPair(civilianWord = "Swimming", undercoverWord = "Diving"),
    UndercoverWordPair(civilianWord = "Running", undercoverWord = "Jogging"),
    UndercoverWordPair(civilianWord = "Elevator", undercoverWord = "Escalator"),
    UndercoverWordPair(civilianWord = "Ferry", undercoverWord = "Cruise"),
    UndercoverWordPair(civilianWord = "Map", undercoverWord = "GPS"),
    UndercoverWordPair(civilianWord = "Sailboat", undercoverWord = "Yacht"),
    UndercoverWordPair(civilianWord = "Meteor", undercoverWord = "Satellite"),
    UndercoverWordPair(civilianWord = "Planet", undercoverWord = "Star"),
    UndercoverWordPair(civilianWord = "Earthquake", undercoverWord = "Tsunami"),
    UndercoverWordPair(civilianWord = "Jellyfish", undercoverWord = "Octopus"),
    UndercoverWordPair(civilianWord = "Wolf", undercoverWord = "Fox"),
    UndercoverWordPair(civilianWord = "Hawk", undercoverWord = "Vulture"),
    UndercoverWordPair(civilianWord = "Lizard", undercoverWord = "Gecko"),
    UndercoverWordPair(civilianWord = "Elvis", undercoverWord = "The Beatles"),
    UndercoverWordPair(civilianWord = "Leonardo da Vinci", undercoverWord = "Michelangelo"),
    UndercoverWordPair(civilianWord = "Napoleon", undercoverWord = "Caesar"),
    UndercoverWordPair(civilianWord = "Mario", undercoverWord = "Luigi"),
    UndercoverWordPair(civilianWord = "Sonic", undercoverWord = "Tails"),
    UndercoverWordPair(civilianWord = "Pac-Man", undercoverWord = "Tetris"),
    UndercoverWordPair(civilianWord = "Fortnite", undercoverWord = "Minecraft"),
    UndercoverWordPair(civilianWord = "Call of Duty", undercoverWord = "Battlefield"),
    UndercoverWordPair(civilianWord = "Game of Thrones", undercoverWord = "Lord of the Rings"),
    UndercoverWordPair(civilianWord = "Star Wars", undercoverWord = "Star Trek"),
    UndercoverWordPair(civilianWord = "Harry Potter", undercoverWord = "Percy Jackson"),
    UndercoverWordPair(civilianWord = "Sherlock Holmes", undercoverWord = "Hercule Poirot"),
    UndercoverWordPair(civilianWord = "Dracula", undercoverWord = "Frankenstein"),
    UndercoverWordPair(civilianWord = "James Bond", undercoverWord = "Secret Service"),
    UndercoverWordPair(civilianWord = "Homer Simpson", undercoverWord = "Peter Griffin"),
    UndercoverWordPair(civilianWord = "SpongeBob", undercoverWord = "Patrick"),
    UndercoverWordPair(civilianWord = "Godzilla", undercoverWord = "King Kong"),
    UndercoverWordPair(civilianWord = "Lego", undercoverWord = "Playmobil"),
    UndercoverWordPair(civilianWord = "UNO", undercoverWord = "Monopoly"),
    UndercoverWordPair(civilianWord = "Catan", undercoverWord = "Risk"),
    UndercoverWordPair(civilianWord = "Blackjack", undercoverWord = "Poker"),
    UndercoverWordPair(civilianWord = "Bingo", undercoverWord = "Roulette"),
    UndercoverWordPair(civilianWord = "New York", undercoverWord = "Los Angeles"),
    UndercoverWordPair(civilianWord = "Paris", undercoverWord = "London"),
    UndercoverWordPair(civilianWord = "Rome", undercoverWord = "Athens"),
    UndercoverWordPair(civilianWord = "Sydney", undercoverWord = "Melbourne"),
    UndercoverWordPair(civilianWord = "Rio de Janeiro", undercoverWord = "Buenos Aires"),
    UndercoverWordPair(civilianWord = "Mount Everest", undercoverWord = "Nepal"),
    UndercoverWordPair(civilianWord = "Amazon", undercoverWord = "Nile"),
    UndercoverWordPair(civilianWord = "Grand Canyon", undercoverWord = "Niagara Falls"),
    UndercoverWordPair(civilianWord = "Taj Mahal", undercoverWord = "Great Wall of China"),
    UndercoverWordPair(civilianWord = "Eiffel Tower", undercoverWord = "Statue of Liberty"),
    UndercoverWordPair(civilianWord = "Big Ben", undercoverWord = "Leaning Tower of Pisa"),
    UndercoverWordPair(civilianWord = "Olympics", undercoverWord = "World Cup"),
    UndercoverWordPair(civilianWord = "NBA", undercoverWord = "NFL"),
    UndercoverWordPair(civilianWord = "Golf", undercoverWord = "Cricket"),
    UndercoverWordPair(civilianWord = "UFC", undercoverWord = "WWE"),
    UndercoverWordPair(civilianWord = "Twitch", undercoverWord = "Netflix"),
    UndercoverWordPair(civilianWord = "Twitter", undercoverWord = "Facebook"),
    UndercoverWordPair(civilianWord = "SpaceX", undercoverWord = "Tesla"),
    UndercoverWordPair(civilianWord = "Burger King", undercoverWord = "McDonald’s"),
    UndercoverWordPair(civilianWord = "Sony", undercoverWord = "Samsung"),
    UndercoverWordPair(civilianWord = "Mercedes", undercoverWord = "BMW"),
    UndercoverWordPair(civilianWord = "Harvard", undercoverWord = "MIT"),
    UndercoverWordPair(civilianWord = "Oxford", undercoverWord = "Highschool"),
    UndercoverWordPair(civilianWord = "CIA", undercoverWord = "FBI"),
    UndercoverWordPair(civilianWord = "Hitler", undercoverWord = "Stalin"),
    UndercoverWordPair(civilianWord = "Tesla", undercoverWord = "Porsche"),
    UndercoverWordPair(civilianWord = "iPhone", undercoverWord = "Samsung"),
    UndercoverWordPair(civilianWord = "PlayStation", undercoverWord = "Xbox"),
    UndercoverWordPair(civilianWord = "Windows", undercoverWord = "MacOS"),
    UndercoverWordPair(civilianWord = "YouTube", undercoverWord = "TikTok"),
    UndercoverWordPair(civilianWord = "Twitch", undercoverWord = "Kick"),
    UndercoverWordPair(civilianWord = "Spotify", undercoverWord = "Apple Music"),
    UndercoverWordPair(civilianWord = "Reddit", undercoverWord = "Discord"),
    UndercoverWordPair(civilianWord = "Instagram", undercoverWord = "Snapchat"),
    UndercoverWordPair(civilianWord = "ChatGPT", undercoverWord = "Gemini"),
    UndercoverWordPair(civilianWord = "Clock", undercoverWord = "Sundial"),
    UndercoverWordPair(civilianWord = "Laptop", undercoverWord = "Desktop"),
    UndercoverWordPair(civilianWord = "Shark", undercoverWord = "Dolphin"),
    UndercoverWordPair(civilianWord = "Penguin", undercoverWord = "Seagull"),
    UndercoverWordPair(civilianWord = "Moon", undercoverWord = "Planet"),
    UndercoverWordPair(civilianWord = "Comet", undercoverWord = "Asteroid"),
    UndercoverWordPair(civilianWord = "Bridge", undercoverWord = "Tunnel"),
    UndercoverWordPair(civilianWord = "Bus", undercoverWord = "Tram"),
    UndercoverWordPair(civilianWord = "Train", undercoverWord = "Monorail"),
    UndercoverWordPair(civilianWord = "Boat", undercoverWord = "Submarine"),
    UndercoverWordPair(civilianWord = "Notebook", undercoverWord = "Diary"),
    UndercoverWordPair(civilianWord = "Spoon", undercoverWord = "Fork"),
    UndercoverWordPair(civilianWord = "Plate", undercoverWord = "Bowl"),
    UndercoverWordPair(civilianWord = "Fountain", undercoverWord = "Waterfall"),
    UndercoverWordPair(civilianWord = "Lake", undercoverWord = "Pond"),
    UndercoverWordPair(civilianWord = "Giraffe", undercoverWord = "Zebra"),
    UndercoverWordPair(civilianWord = "Elephant", undercoverWord = "Rhino"),
    UndercoverWordPair(civilianWord = "Alligator", undercoverWord = "Crocodile"),
    UndercoverWordPair(civilianWord = "Oyster", undercoverWord = "Clam"),
    UndercoverWordPair(civilianWord = "Gold", undercoverWord = "Silver"),
    UndercoverWordPair(civilianWord = "Platinum", undercoverWord = "Gold"),
    UndercoverWordPair(civilianWord = "Denim", undercoverWord = "Corduroy"),
    UndercoverWordPair(civilianWord = "Jacket", undercoverWord = "Coat"),
    UndercoverWordPair(civilianWord = "Scarf", undercoverWord = "Tie"),
    UndercoverWordPair(civilianWord = "Boots", undercoverWord = "Sneakers"),
    UndercoverWordPair(civilianWord = "Helmet", undercoverWord = "Hat"),
    UndercoverWordPair(civilianWord = "Necklace", undercoverWord = "Bracelet"),
    UndercoverWordPair(civilianWord = "Ring", undercoverWord = "Earring"),
    UndercoverWordPair(civilianWord = "Microphone", undercoverWord = "Speaker"),
    UndercoverWordPair(civilianWord = "Headphones", undercoverWord = "Earbuds"),
    UndercoverWordPair(civilianWord = "Television", undercoverWord = "Radio"),
    UndercoverWordPair(civilianWord = "Projector", undercoverWord = "Screen"),
    UndercoverWordPair(civilianWord = "Calculator", undercoverWord = "Typewriter"),
    UndercoverWordPair(civilianWord = "Flashlight", undercoverWord = "Lantern"),
    UndercoverWordPair(civilianWord = "Tent", undercoverWord = "Cabin"),
    UndercoverWordPair(civilianWord = "Compass", undercoverWord = "Map"),
    UndercoverWordPair(civilianWord = "Boarding pass", undercoverWord = "ID card"),
    UndercoverWordPair(civilianWord = "Ticket", undercoverWord = "Invoice"),
    UndercoverWordPair(civilianWord = "Passport", undercoverWord = "Ticket"),
    UndercoverWordPair(civilianWord = "Subway", undercoverWord = "Taxi"),
    UndercoverWordPair(civilianWord = "Sky", undercoverWord = "Jet"),
    UndercoverWordPair(civilianWord = "Motorcycle", undercoverWord = "Scooter"),
    UndercoverWordPair(civilianWord = "Surfboard", undercoverWord = "Skateboard"),
    UndercoverWordPair(civilianWord = "Baseball", undercoverWord = "Football"),
    UndercoverWordPair(civilianWord = "Volleyball", undercoverWord = "Basketball"),
    UndercoverWordPair(civilianWord = "Table tennis", undercoverWord = "Badminton"),
    UndercoverWordPair(civilianWord = "Bakery", undercoverWord = "Butcher"),
    UndercoverWordPair(civilianWord = "Puzzle", undercoverWord = "Crossword"),
    UndercoverWordPair(civilianWord = "Cards", undercoverWord = "Dice"),
    UndercoverWordPair(civilianWord = "Bowling", undercoverWord = "Golf"),
    UndercoverWordPair(civilianWord = "Marathon", undercoverWord = "Sprint"),
    UndercoverWordPair(civilianWord = "Fencing", undercoverWord = "Archery"),
    UndercoverWordPair(civilianWord = "Boxing", undercoverWord = "Karate"),
    UndercoverWordPair(civilianWord = "Hockey", undercoverWord = "Soccer"),
    UndercoverWordPair(civilianWord = "Concert", undercoverWord = "Festival"),
    UndercoverWordPair(civilianWord = "Novel", undercoverWord = "Poem"),
    UndercoverWordPair(civilianWord = "Dictionary", undercoverWord = "Encyclopedia"),
    UndercoverWordPair(civilianWord = "Pharmacist", undercoverWord = "Doctor"),
    UndercoverWordPair(civilianWord = "Engineer", undercoverWord = "Architect"),
    UndercoverWordPair(civilianWord = "Firefighter", undercoverWord = "Policeman"),
    UndercoverWordPair(civilianWord = "Germany", undercoverWord = "France"),
    UndercoverWordPair(civilianWord = "Pilot", undercoverWord = "Astronaut"),
    UndercoverWordPair(civilianWord = "Judge", undercoverWord = "Punishment"),
    UndercoverWordPair(civilianWord = "Baker", undercoverWord = "Chef"),
    UndercoverWordPair(civilianWord = "Farmer", undercoverWord = "Fisherman"),
    UndercoverWordPair(civilianWord = "Blacksmith", undercoverWord = "Carpenter"),
    UndercoverWordPair(civilianWord = "Heaven", undercoverWord = "Hell"),
    UndercoverWordPair(civilianWord = "Sky", undercoverWord = "Clouds"),
    UndercoverWordPair(civilianWord = "Japan", undercoverWord = "China"),
    UndercoverWordPair(civilianWord = "Germany", undercoverWord = "Beer"),
    UndercoverWordPair(civilianWord = "Movie", undercoverWord = "Actor"),
    UndercoverWordPair(civilianWord = "Screen", undercoverWord = "TV"),
    UndercoverWordPair(civilianWord = "France", undercoverWord = "Eiffel Tower"),
    UndercoverWordPair(civilianWord = "Thor", undercoverWord = "Lightning"),
    UndercoverWordPair(civilianWord = "Obi Wan", undercoverWord = "Force"),
    UndercoverWordPair(civilianWord = "UFO", undercoverWord = "Drones"),
    UndercoverWordPair(civilianWord = "God", undercoverWord = "Heaven"),
    UndercoverWordPair(civilianWord = "Tortilla", undercoverWord = "Taco"),
    UndercoverWordPair(civilianWord = "Baguette", undercoverWord = "Ciabatta"),
    UndercoverWordPair(civilianWord = "Hot Dog", undercoverWord = "Bratwurst"),
    UndercoverWordPair(civilianWord = "Energy Drink", undercoverWord = "Soda"),
    UndercoverWordPair(civilianWord = "Coconut milk", undercoverWord = "soy milk"),
    UndercoverWordPair(civilianWord = "Picasso", undercoverWord = "Van Gogh"),
    UndercoverWordPair(civilianWord = "Mozart", undercoverWord = "Beethoven"),
    UndercoverWordPair(civilianWord = "Messi", undercoverWord = "Ronaldo"),
    UndercoverWordPair(civilianWord = "Bayern Munich", undercoverWord = "Real Madrid"),
    UndercoverWordPair(civilianWord = "Ferrari", undercoverWord = "Lamborghini"),
    UndercoverWordPair(civilianWord = "Coca-Cola", undercoverWord = "Pepsi"),
    UndercoverWordPair(civilianWord = "London", undercoverWord = "Paris"),
    UndercoverWordPair(civilianWord = "Los Angeles", undercoverWord = "New York"),
    UndercoverWordPair(civilianWord = "Big Ben", undercoverWord = "Leaning Tower of Pisa"),
    UndercoverWordPair(civilianWord = "Statue of Liberty", undercoverWord = "Eiffel Tower"),
    UndercoverWordPair(civilianWord = "Mouse", undercoverWord = "Keyboard"),
    UndercoverWordPair(civilianWord = "TV", undercoverWord = "Laptop"),
    UndercoverWordPair(civilianWord = "Wardrobe", undercoverWord = "Showcase"),
    UndercoverWordPair(civilianWord = "Birch", undercoverWord = "Shrub"),
    UndercoverWordPair(civilianWord = "Radiator", undercoverWord = "Hairdryer"),
    UndercoverWordPair(civilianWord = "Lamp", undercoverWord = "Candle"),
    UndercoverWordPair(civilianWord = "Pillow", undercoverWord = "Blanket"),
    UndercoverWordPair(civilianWord = "Microphone", undercoverWord = "Camera"),
    UndercoverWordPair(civilianWord = "Oven", undercoverWord = "Microwave"),
    UndercoverWordPair(civilianWord = "Pan", undercoverWord = "Pot"),
    UndercoverWordPair(civilianWord = "Tablet", undercoverWord = "Smartphone"),
    UndercoverWordPair(civilianWord = "Stairs", undercoverWord = "Elevator"),
    UndercoverWordPair(civilianWord = "Techno", undercoverWord = "Rap"),
    UndercoverWordPair(civilianWord = "Rock", undercoverWord = "Pop"),
    UndercoverWordPair(civilianWord = "Table Tennis", undercoverWord = "Badminton"),
    UndercoverWordPair(civilianWord = "Window", undercoverWord = "Door"),
    UndercoverWordPair(civilianWord = "Oven", undercoverWord = "Heating"),
    UndercoverWordPair(civilianWord = "Wristwatch", undercoverWord = "Alarm Clock"),
    UndercoverWordPair(civilianWord = "Bed", undercoverWord = "Sofa"),
    UndercoverWordPair(civilianWord = "Book", undercoverWord = "Newspaper"),
    UndercoverWordPair(civilianWord = "Forest", undercoverWord = "Park"),
    UndercoverWordPair(civilianWord = "Cinema", undercoverWord = "Bowling"),
    UndercoverWordPair(civilianWord = "Netflix", undercoverWord = "Cinema"),
    UndercoverWordPair(civilianWord = "Swimming Pool", undercoverWord = "Beach"),
    UndercoverWordPair(civilianWord = "Glass", undercoverWord = "Cup"),
    UndercoverWordPair(civilianWord = "Job", undercoverWord = "Hobby"),
    UndercoverWordPair(civilianWord = "Jesus", undercoverWord = "Santa Claus"),
    UndercoverWordPair(civilianWord = "bra", undercoverWord = "bikini")
)

