package org.lerchenflo.schneaggchatv3mp.games.presentation.undercover

import org.koin.mp.KoinPlatform
import org.lerchenflo.schneaggchatv3mp.datasource.preferences.LanguageSetting
import org.lerchenflo.schneaggchatv3mp.utilities.LanguageService

data class UndercoverWordPair(
    val civilianWord: String,
    val undercoverWord: String,
    val mrWhiteTip: String = ""
)

val UNDERCOVER_WORD_PAIRS_EN: List<UndercoverWordPair> = listOf(
    UndercoverWordPair(civilianWord = "Dog", undercoverWord = "Cat", mrWhiteTip = "A common furry pet kept at home"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Burger", mrWhiteTip = "A popular fast food often ordered for delivery"),
    UndercoverWordPair(civilianWord = "Beach", undercoverWord = "Mountain", mrWhiteTip = "A popular vacation destination"),
    UndercoverWordPair(civilianWord = "Coffee", undercoverWord = "Tea", mrWhiteTip = "A hot drink often had in the morning"),
    UndercoverWordPair(civilianWord = "Car", undercoverWord = "Bus", mrWhiteTip = "A vehicle used to get around a city"),
    UndercoverWordPair(civilianWord = "Sun", undercoverWord = "Moon", mrWhiteTip = "A bright object visible in the sky"),
    UndercoverWordPair(civilianWord = "Banana", undercoverWord = "Apple", mrWhiteTip = "A fruit often packed as a snack"),
    UndercoverWordPair(civilianWord = "Perfume", undercoverWord = "Deodorant", mrWhiteTip = "Something you spray to smell nice"),
    UndercoverWordPair(civilianWord = "Adidas", undercoverWord = "Nike", mrWhiteTip = "A well-known sportswear brand"),
    UndercoverWordPair(civilianWord = "backpack", undercoverWord = "suitcase", mrWhiteTip = "Something you pack for a trip"),
    UndercoverWordPair(civilianWord = "jacuzzi", undercoverWord = "sauna", mrWhiteTip = "A relaxing spa amenity involving heat or water"),
    UndercoverWordPair(civilianWord = "sneakers", undercoverWord = "sandals", mrWhiteTip = "Footwear worn in warm weather"),
    UndercoverWordPair(civilianWord = "sunglasses", undercoverWord = "eyeglasses", mrWhiteTip = "Something worn to help you see or protect your eyes"),
    UndercoverWordPair(civilianWord = "piano", undercoverWord = "guitar", mrWhiteTip = "A musical instrument played with your hands"),
    UndercoverWordPair(civilianWord = "cruise", undercoverWord = "safari", mrWhiteTip = "An adventurous vacation trip"),
    UndercoverWordPair(civilianWord = "sushi", undercoverWord = "pizza", mrWhiteTip = "A dish people order for dinner"),
    UndercoverWordPair(civilianWord = "hamburger", undercoverWord = "hotdog", mrWhiteTip = "A classic food from a cookout"),
    UndercoverWordPair(civilianWord = "chocolate", undercoverWord = "vanilla", mrWhiteTip = "A common ice cream flavor"),
    UndercoverWordPair(civilianWord = "beer", undercoverWord = "wine", mrWhiteTip = "An alcoholic drink enjoyed at dinner"),
    UndercoverWordPair(civilianWord = "whiskey", undercoverWord = "vodka", mrWhiteTip = "A strong alcoholic spirit"),
    UndercoverWordPair(civilianWord = "milk", undercoverWord = "juice", mrWhiteTip = "A drink often had with breakfast"),
    UndercoverWordPair(civilianWord = "bread", undercoverWord = "butter", mrWhiteTip = "Something found on a breakfast table"),
    UndercoverWordPair(civilianWord = "rice", undercoverWord = "pasta", mrWhiteTip = "A carbohydrate side dish"),
    UndercoverWordPair(civilianWord = "chicken", undercoverWord = "beef", mrWhiteTip = "A type of meat served for dinner"),
    UndercoverWordPair(civilianWord = "apple", undercoverWord = "orange", mrWhiteTip = "A fruit found in a fruit bowl"),
    UndercoverWordPair(civilianWord = "banana", undercoverWord = "strawberry", mrWhiteTip = "A fruit often used in a smoothie"),
    UndercoverWordPair(civilianWord = "carrot", undercoverWord = "broccoli", mrWhiteTip = "A vegetable that is good for you"),
    UndercoverWordPair(civilianWord = "potato", undercoverWord = "tomato", mrWhiteTip = "A vegetable grown in a garden"),
    UndercoverWordPair(civilianWord = "onion", undercoverWord = "garlic", mrWhiteTip = "A flavorful ingredient used in cooking"),
    UndercoverWordPair(civilianWord = "salt", undercoverWord = "pepper", mrWhiteTip = "A seasoning found on the dinner table"),
    UndercoverWordPair(civilianWord = "sugar", undercoverWord = "honey", mrWhiteTip = "Something sweet added to tea"),
    UndercoverWordPair(civilianWord = "water", undercoverWord = "soda", mrWhiteTip = "A drink you have with a meal"),
    UndercoverWordPair(civilianWord = "Apple", undercoverWord = "Microsoft", mrWhiteTip = "A major technology company"),
    UndercoverWordPair(civilianWord = "Google", undercoverWord = "Facebook", mrWhiteTip = "A giant internet company"),
    UndercoverWordPair(civilianWord = "Amazon", undercoverWord = "Netflix", mrWhiteTip = "A popular online service you pay a subscription for"),
    UndercoverWordPair(civilianWord = "Pancake", undercoverWord = "Doughnut", mrWhiteTip = "A sweet breakfast treat"),
    UndercoverWordPair(civilianWord = "Ice cream", undercoverWord = "Cake", mrWhiteTip = "A dessert served at a birthday party"),
    UndercoverWordPair(civilianWord = "McDonalds", undercoverWord = "KFC", mrWhiteTip = "A fast food restaurant chain"),
    UndercoverWordPair(civilianWord = "Car", undercoverWord = "Bike", mrWhiteTip = "Something used to travel short distances"),
    UndercoverWordPair(civilianWord = "virus", undercoverWord = "bacteria", mrWhiteTip = "A tiny organism that can make you sick"),
    UndercoverWordPair(civilianWord = "Lord of the rings", undercoverWord = "Hobbit", mrWhiteTip = "A famous fantasy story"),
    UndercoverWordPair(civilianWord = "Harry Potter", undercoverWord = "Lord Voldemort", mrWhiteTip = "A well-known character from a wizard story"),
    UndercoverWordPair(civilianWord = "Superman", undercoverWord = "Batman", mrWhiteTip = "A superhero from a comic book"),
    UndercoverWordPair(civilianWord = "Spiderman", undercoverWord = "Ironman", mrWhiteTip = "A Marvel superhero"),
    UndercoverWordPair(civilianWord = "Captain America", undercoverWord = "Thor", mrWhiteTip = "An Avengers superhero"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Pasta", mrWhiteTip = "A classic Italian food"),
    UndercoverWordPair(civilianWord = "Football", undercoverWord = "Basketball", mrWhiteTip = "A popular team sport"),
    UndercoverWordPair(civilianWord = "Music", undercoverWord = "Dancing", mrWhiteTip = "Something people enjoy at a party"),
    UndercoverWordPair(civilianWord = "Dog", undercoverWord = "Wolf", mrWhiteTip = "An animal from the canine family"),
    UndercoverWordPair(civilianWord = "Apple", undercoverWord = "Pear", mrWhiteTip = "A fruit that grows on a tree"),
    UndercoverWordPair(civilianWord = "Car", undercoverWord = "Truck", mrWhiteTip = "A vehicle with an engine"),
    UndercoverWordPair(civilianWord = "Pencil", undercoverWord = "Pen", mrWhiteTip = "A tool used for writing"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Lasagna", mrWhiteTip = "A cheesy Italian dish"),
    UndercoverWordPair(civilianWord = "Facebook", undercoverWord = "Instagram", mrWhiteTip = "A social media app"),
    UndercoverWordPair(civilianWord = "Sunglasses", undercoverWord = "Goggles", mrWhiteTip = "Eyewear worn for protection"),
    UndercoverWordPair(civilianWord = "Laptop", undercoverWord = "Tablet", mrWhiteTip = "An electronic device used for browsing"),
    UndercoverWordPair(civilianWord = "Doctor", undercoverWord = "Surgeon", mrWhiteTip = "A profession that helps sick people"),
    UndercoverWordPair(civilianWord = "Bitcoin", undercoverWord = "Ethereum", mrWhiteTip = "A type of digital currency"),
    UndercoverWordPair(civilianWord = "Watch", undercoverWord = "Ring", mrWhiteTip = "A piece of jewelry worn on your hand or wrist"),
    UndercoverWordPair(civilianWord = "Bomb", undercoverWord = "Gun", mrWhiteTip = "A dangerous weapon"),
    UndercoverWordPair(civilianWord = "Einstein", undercoverWord = "Newton", mrWhiteTip = "A famous scientist"),
    UndercoverWordPair(civilianWord = "Shirt", undercoverWord = "Sweater", mrWhiteTip = "A piece of clothing worn on your upper body"),
    UndercoverWordPair(civilianWord = "Soccer", undercoverWord = "Rugby", mrWhiteTip = "A sport played with a ball on a field"),
    UndercoverWordPair(civilianWord = "Plane", undercoverWord = "Helicopter", mrWhiteTip = "A flying vehicle"),
    UndercoverWordPair(civilianWord = "River", undercoverWord = "Lake", mrWhiteTip = "A body of fresh water"),
    UndercoverWordPair(civilianWord = "Ocean", undercoverWord = "River", mrWhiteTip = "A large body of water"),
    UndercoverWordPair(civilianWord = "Teacher", undercoverWord = "Professor", mrWhiteTip = "Someone who teaches students"),
    UndercoverWordPair(civilianWord = "Bicycle", undercoverWord = "Motorcycle", mrWhiteTip = "A two-wheeled vehicle"),
    UndercoverWordPair(civilianWord = "Salt", undercoverWord = "Sugar", mrWhiteTip = "A white seasoning found in the kitchen"),
    UndercoverWordPair(civilianWord = "Knife", undercoverWord = "Scissors", mrWhiteTip = "A sharp tool used for cutting"),
    UndercoverWordPair(civilianWord = "Chair", undercoverWord = "Bench", mrWhiteTip = "Something you sit on"),
    UndercoverWordPair(civilianWord = "Castle", undercoverWord = "House", mrWhiteTip = "A place where people live"),
    UndercoverWordPair(civilianWord = "Train", undercoverWord = "Bus", mrWhiteTip = "A form of public transportation"),
    UndercoverWordPair(civilianWord = "Mirror", undercoverWord = "window pane", mrWhiteTip = "Something made of glass"),
    UndercoverWordPair(civilianWord = "Mouse", undercoverWord = "Rat", mrWhiteTip = "A small rodent"),
    UndercoverWordPair(civilianWord = "Cucumber", undercoverWord = "Zucchini", mrWhiteTip = "A green vegetable"),
    UndercoverWordPair(civilianWord = "Strawberry", undercoverWord = "Raspberry", mrWhiteTip = "A small red berry"),
    UndercoverWordPair(civilianWord = "Banana", undercoverWord = "Plantain", mrWhiteTip = "A long yellow fruit"),
    UndercoverWordPair(civilianWord = "Coconut", undercoverWord = "Pineapple", mrWhiteTip = "A tropical fruit"),
    UndercoverWordPair(civilianWord = "Dragon", undercoverWord = "Dinosaur", mrWhiteTip = "A giant creature from myths or the past"),
    UndercoverWordPair(civilianWord = "Ghost", undercoverWord = "Zombie", mrWhiteTip = "A scary creature from horror movies"),
    UndercoverWordPair(civilianWord = "Chef", undercoverWord = "Kitchen counter", mrWhiteTip = "Something found in a restaurant kitchen"),
    UndercoverWordPair(civilianWord = "Shovel", undercoverWord = "Axe", mrWhiteTip = "A tool used outdoors"),
    UndercoverWordPair(civilianWord = "Pyramid", undercoverWord = "Temple", mrWhiteTip = "An ancient stone structure"),
    UndercoverWordPair(civilianWord = "Volcano", undercoverWord = "Mountain", mrWhiteTip = "A tall natural landform"),
    UndercoverWordPair(civilianWord = "Desert", undercoverWord = "Sand", mrWhiteTip = "A hot dry place"),
    UndercoverWordPair(civilianWord = "Cloud", undercoverWord = "Fog", mrWhiteTip = "Something that makes the sky hazy"),
    UndercoverWordPair(civilianWord = "Snow", undercoverWord = "Hail", mrWhiteTip = "Something that falls from the sky in winter"),
    UndercoverWordPair(civilianWord = "Detective", undercoverWord = "Criminal", mrWhiteTip = "A character from a crime story"),
    UndercoverWordPair(civilianWord = "Jungle", undercoverWord = "Forest", mrWhiteTip = "A place full of trees"),
    UndercoverWordPair(civilianWord = "Clock", undercoverWord = "Watch", mrWhiteTip = "Something that tells the time"),
    UndercoverWordPair(civilianWord = "Bread", undercoverWord = "Toast", mrWhiteTip = "Something made from baked dough"),
    UndercoverWordPair(civilianWord = "Painting", undercoverWord = "Sketch", mrWhiteTip = "A piece of art"),
    UndercoverWordPair(civilianWord = "Umbrella", undercoverWord = "Parasol", mrWhiteTip = "Something you carry to block sun or rain"),
    UndercoverWordPair(civilianWord = "Suit", undercoverWord = "necktie", mrWhiteTip = "Formal clothing worn to work"),
    UndercoverWordPair(civilianWord = "Socks", undercoverWord = "Stockings", mrWhiteTip = "Something worn on your feet or legs"),
    UndercoverWordPair(civilianWord = "Belt", undercoverWord = "Jeans", mrWhiteTip = "An item of clothing worn around the waist"),
    UndercoverWordPair(civilianWord = "Crown", undercoverWord = "Hat", mrWhiteTip = "Something worn on your head"),
    UndercoverWordPair(civilianWord = "Ballet", undercoverWord = "Hip Hop", mrWhiteTip = "A style of dance"),
    UndercoverWordPair(civilianWord = "Parrot", undercoverWord = "Crow", mrWhiteTip = "A type of bird"),
    UndercoverWordPair(civilianWord = "Bat", undercoverWord = "Owl", mrWhiteTip = "A nocturnal animal"),
    UndercoverWordPair(civilianWord = "Candle", undercoverWord = "Lantern", mrWhiteTip = "Something used to light a dark room"),
    UndercoverWordPair(civilianWord = "Library", undercoverWord = "University", mrWhiteTip = "A place full of books and students"),
    UndercoverWordPair(civilianWord = "Museum", undercoverWord = "Gallery", mrWhiteTip = "A place to see art or history"),
    UndercoverWordPair(civilianWord = "Radio", undercoverWord = "Podcast", mrWhiteTip = "Something you listen to for entertainment"),
    UndercoverWordPair(civilianWord = "online news", undercoverWord = "Newspaper", mrWhiteTip = "A source of daily news"),
    UndercoverWordPair(civilianWord = "Pen", undercoverWord = "Paper", mrWhiteTip = "Something used for writing a letter"),
    UndercoverWordPair(civilianWord = "Moon", undercoverWord = "Sun", mrWhiteTip = "An object that lights up the sky"),
    UndercoverWordPair(civilianWord = "Tennis", undercoverWord = "Badminton", mrWhiteTip = "A racket sport"),
    UndercoverWordPair(civilianWord = "Skiing", undercoverWord = "Snow", mrWhiteTip = "A winter activity"),
    UndercoverWordPair(civilianWord = "Swimming", undercoverWord = "Diving", mrWhiteTip = "An activity done in water"),
    UndercoverWordPair(civilianWord = "Running", undercoverWord = "Jogging", mrWhiteTip = "A form of cardio exercise"),
    UndercoverWordPair(civilianWord = "Elevator", undercoverWord = "Escalator", mrWhiteTip = "Something that moves you between floors"),
    UndercoverWordPair(civilianWord = "Ferry", undercoverWord = "Cruise", mrWhiteTip = "A boat trip"),
    UndercoverWordPair(civilianWord = "Map", undercoverWord = "GPS", mrWhiteTip = "Something that helps you find your way"),
    UndercoverWordPair(civilianWord = "Sailboat", undercoverWord = "Yacht", mrWhiteTip = "A boat used on the water"),
    UndercoverWordPair(civilianWord = "Meteor", undercoverWord = "Satellite", mrWhiteTip = "Something seen in the night sky"),
    UndercoverWordPair(civilianWord = "Planet", undercoverWord = "Star", mrWhiteTip = "A celestial object in space"),
    UndercoverWordPair(civilianWord = "Earthquake", undercoverWord = "Tsunami", mrWhiteTip = "A dangerous natural disaster"),
    UndercoverWordPair(civilianWord = "Jellyfish", undercoverWord = "Octopus", mrWhiteTip = "A sea creature"),
    UndercoverWordPair(civilianWord = "Wolf", undercoverWord = "Fox", mrWhiteTip = "A wild canine animal"),
    UndercoverWordPair(civilianWord = "Hawk", undercoverWord = "Vulture", mrWhiteTip = "A bird of prey"),
    UndercoverWordPair(civilianWord = "Lizard", undercoverWord = "Gecko", mrWhiteTip = "A small reptile"),
    UndercoverWordPair(civilianWord = "Elvis", undercoverWord = "The Beatles", mrWhiteTip = "A famous musician from the past"),
    UndercoverWordPair(civilianWord = "Leonardo da Vinci", undercoverWord = "Michelangelo", mrWhiteTip = "A famous Renaissance artist"),
    UndercoverWordPair(civilianWord = "Napoleon", undercoverWord = "Caesar", mrWhiteTip = "A powerful historical military leader"),
    UndercoverWordPair(civilianWord = "Mario", undercoverWord = "Luigi", mrWhiteTip = "A character from a video game"),
    UndercoverWordPair(civilianWord = "Sonic", undercoverWord = "Tails", mrWhiteTip = "A character from a video game"),
    UndercoverWordPair(civilianWord = "Pac-Man", undercoverWord = "Tetris", mrWhiteTip = "A classic video game"),
    UndercoverWordPair(civilianWord = "Fortnite", undercoverWord = "Minecraft", mrWhiteTip = "A popular video game"),
    UndercoverWordPair(civilianWord = "Call of Duty", undercoverWord = "Battlefield", mrWhiteTip = "A war-themed video game"),
    UndercoverWordPair(civilianWord = "Game of Thrones", undercoverWord = "Lord of the Rings", mrWhiteTip = "A famous fantasy TV series or book"),
    UndercoverWordPair(civilianWord = "Star Wars", undercoverWord = "Star Trek", mrWhiteTip = "A famous sci-fi franchise"),
    UndercoverWordPair(civilianWord = "Harry Potter", undercoverWord = "Percy Jackson", mrWhiteTip = "A book series about a young hero"),
    UndercoverWordPair(civilianWord = "Sherlock Holmes", undercoverWord = "Hercule Poirot", mrWhiteTip = "A famous fictional detective"),
    UndercoverWordPair(civilianWord = "Dracula", undercoverWord = "Frankenstein", mrWhiteTip = "A classic horror movie monster"),
    UndercoverWordPair(civilianWord = "James Bond", undercoverWord = "Secret Service", mrWhiteTip = "A famous spy character"),
    UndercoverWordPair(civilianWord = "Homer Simpson", undercoverWord = "Peter Griffin", mrWhiteTip = "A character from an animated sitcom"),
    UndercoverWordPair(civilianWord = "SpongeBob", undercoverWord = "Patrick", mrWhiteTip = "A character from a cartoon under the sea"),
    UndercoverWordPair(civilianWord = "Godzilla", undercoverWord = "King Kong", mrWhiteTip = "A giant movie monster"),
    UndercoverWordPair(civilianWord = "Lego", undercoverWord = "Playmobil", mrWhiteTip = "A children's building toy"),
    UndercoverWordPair(civilianWord = "UNO", undercoverWord = "Monopoly", mrWhiteTip = "A classic board or card game"),
    UndercoverWordPair(civilianWord = "Catan", undercoverWord = "Risk", mrWhiteTip = "A strategy board game"),
    UndercoverWordPair(civilianWord = "Blackjack", undercoverWord = "Poker", mrWhiteTip = "A card game played in a casino"),
    UndercoverWordPair(civilianWord = "Bingo", undercoverWord = "Roulette", mrWhiteTip = "A casino game of chance"),
    UndercoverWordPair(civilianWord = "New York", undercoverWord = "Los Angeles", mrWhiteTip = "A famous US city"),
    UndercoverWordPair(civilianWord = "Paris", undercoverWord = "London", mrWhiteTip = "A major European capital city"),
    UndercoverWordPair(civilianWord = "Rome", undercoverWord = "Athens", mrWhiteTip = "An ancient European capital city"),
    UndercoverWordPair(civilianWord = "Sydney", undercoverWord = "Melbourne", mrWhiteTip = "A major Australian city"),
    UndercoverWordPair(civilianWord = "Rio de Janeiro", undercoverWord = "Buenos Aires", mrWhiteTip = "A major South American city"),
    UndercoverWordPair(civilianWord = "Mount Everest", undercoverWord = "Nepal", mrWhiteTip = "Something related to the tallest mountain in the world"),
    UndercoverWordPair(civilianWord = "Amazon", undercoverWord = "Nile", mrWhiteTip = "One of the world's longest rivers"),
    UndercoverWordPair(civilianWord = "Grand Canyon", undercoverWord = "Niagara Falls", mrWhiteTip = "A famous natural landmark in North America"),
    UndercoverWordPair(civilianWord = "Taj Mahal", undercoverWord = "Great Wall of China", mrWhiteTip = "A famous world landmark"),
    UndercoverWordPair(civilianWord = "Eiffel Tower", undercoverWord = "Statue of Liberty", mrWhiteTip = "A famous monument you can visit"),
    UndercoverWordPair(civilianWord = "Big Ben", undercoverWord = "Leaning Tower of Pisa", mrWhiteTip = "A famous tower landmark"),
    UndercoverWordPair(civilianWord = "Olympics", undercoverWord = "World Cup", mrWhiteTip = "A major international sports event"),
    UndercoverWordPair(civilianWord = "NBA", undercoverWord = "NFL", mrWhiteTip = "A major American sports league"),
    UndercoverWordPair(civilianWord = "Golf", undercoverWord = "Cricket", mrWhiteTip = "A sport played with a bat or club"),
    UndercoverWordPair(civilianWord = "UFC", undercoverWord = "WWE", mrWhiteTip = "A televised fighting sport or show"),
    UndercoverWordPair(civilianWord = "Twitch", undercoverWord = "Netflix", mrWhiteTip = "A platform for watching video content"),
    UndercoverWordPair(civilianWord = "Twitter", undercoverWord = "Facebook", mrWhiteTip = "A well-known social media platform"),
    UndercoverWordPair(civilianWord = "SpaceX", undercoverWord = "Tesla", mrWhiteTip = "A company founded by Elon Musk"),
    UndercoverWordPair(civilianWord = "Burger King", undercoverWord = "McDonald’s", mrWhiteTip = "A fast food burger chain"),
    UndercoverWordPair(civilianWord = "Sony", undercoverWord = "Samsung", mrWhiteTip = "A major electronics brand"),
    UndercoverWordPair(civilianWord = "Mercedes", undercoverWord = "BMW", mrWhiteTip = "A German luxury car brand"),
    UndercoverWordPair(civilianWord = "Harvard", undercoverWord = "MIT", mrWhiteTip = "A prestigious American university"),
    UndercoverWordPair(civilianWord = "Oxford", undercoverWord = "Highschool", mrWhiteTip = "A well-known place of education"),
    UndercoverWordPair(civilianWord = "CIA", undercoverWord = "FBI", mrWhiteTip = "A US government agency"),
    UndercoverWordPair(civilianWord = "Tesla", undercoverWord = "Porsche", mrWhiteTip = "A brand known for fast cars"),
    UndercoverWordPair(civilianWord = "iPhone", undercoverWord = "Samsung", mrWhiteTip = "A popular smartphone brand"),
    UndercoverWordPair(civilianWord = "PlayStation", undercoverWord = "Xbox", mrWhiteTip = "A video game console"),
    UndercoverWordPair(civilianWord = "Windows", undercoverWord = "MacOS", mrWhiteTip = "A computer operating system"),
    UndercoverWordPair(civilianWord = "YouTube", undercoverWord = "TikTok", mrWhiteTip = "A video sharing platform"),
    UndercoverWordPair(civilianWord = "Twitch", undercoverWord = "Kick", mrWhiteTip = "A live streaming platform"),
    UndercoverWordPair(civilianWord = "Spotify", undercoverWord = "Apple Music", mrWhiteTip = "A music streaming service"),
    UndercoverWordPair(civilianWord = "Reddit", undercoverWord = "Discord", mrWhiteTip = "An online community platform"),
    UndercoverWordPair(civilianWord = "Instagram", undercoverWord = "Snapchat", mrWhiteTip = "A photo sharing social app"),
    UndercoverWordPair(civilianWord = "ChatGPT", undercoverWord = "Gemini", mrWhiteTip = "An AI chatbot"),
    UndercoverWordPair(civilianWord = "Clock", undercoverWord = "Sundial", mrWhiteTip = "A device used to tell the time"),
    UndercoverWordPair(civilianWord = "Laptop", undercoverWord = "Desktop", mrWhiteTip = "A computer used for work"),
    UndercoverWordPair(civilianWord = "Shark", undercoverWord = "Dolphin", mrWhiteTip = "A large sea animal"),
    UndercoverWordPair(civilianWord = "Penguin", undercoverWord = "Seagull", mrWhiteTip = "A bird found near the ocean"),
    UndercoverWordPair(civilianWord = "Moon", undercoverWord = "Planet", mrWhiteTip = "An object you see in the night sky"),
    UndercoverWordPair(civilianWord = "Comet", undercoverWord = "Asteroid", mrWhiteTip = "A small object moving through space"),
    UndercoverWordPair(civilianWord = "Bridge", undercoverWord = "Tunnel", mrWhiteTip = "Something built to cross an obstacle"),
    UndercoverWordPair(civilianWord = "Bus", undercoverWord = "Tram", mrWhiteTip = "A form of public transport in a city"),
    UndercoverWordPair(civilianWord = "Train", undercoverWord = "Monorail", mrWhiteTip = "A vehicle that runs on rails"),
    UndercoverWordPair(civilianWord = "Boat", undercoverWord = "Submarine", mrWhiteTip = "A vehicle used to travel on or under water"),
    UndercoverWordPair(civilianWord = "Notebook", undercoverWord = "Diary", mrWhiteTip = "Something you write your thoughts in"),
    UndercoverWordPair(civilianWord = "Spoon", undercoverWord = "Fork", mrWhiteTip = "A utensil used for eating"),
    UndercoverWordPair(civilianWord = "Plate", undercoverWord = "Bowl", mrWhiteTip = "Something you eat food from"),
    UndercoverWordPair(civilianWord = "Fountain", undercoverWord = "Waterfall", mrWhiteTip = "Falling or flowing water"),
    UndercoverWordPair(civilianWord = "Lake", undercoverWord = "Pond", mrWhiteTip = "A small body of still water"),
    UndercoverWordPair(civilianWord = "Giraffe", undercoverWord = "Zebra", mrWhiteTip = "A tall animal found in Africa"),
    UndercoverWordPair(civilianWord = "Elephant", undercoverWord = "Rhino", mrWhiteTip = "A large animal with thick skin"),
    UndercoverWordPair(civilianWord = "Alligator", undercoverWord = "Crocodile", mrWhiteTip = "A large reptile living near water"),
    UndercoverWordPair(civilianWord = "Oyster", undercoverWord = "Clam", mrWhiteTip = "A shellfish found in the ocean"),
    UndercoverWordPair(civilianWord = "Gold", undercoverWord = "Silver", mrWhiteTip = "A precious metal"),
    UndercoverWordPair(civilianWord = "Platinum", undercoverWord = "Gold", mrWhiteTip = "A valuable metal used in jewelry"),
    UndercoverWordPair(civilianWord = "Denim", undercoverWord = "Corduroy", mrWhiteTip = "A type of fabric used for pants"),
    UndercoverWordPair(civilianWord = "Jacket", undercoverWord = "Coat", mrWhiteTip = "Clothing worn to stay warm outside"),
    UndercoverWordPair(civilianWord = "Scarf", undercoverWord = "Tie", mrWhiteTip = "Something worn around your neck"),
    UndercoverWordPair(civilianWord = "Boots", undercoverWord = "Sneakers", mrWhiteTip = "A type of shoe"),
    UndercoverWordPair(civilianWord = "Helmet", undercoverWord = "Hat", mrWhiteTip = "Something worn to protect your head"),
    UndercoverWordPair(civilianWord = "Necklace", undercoverWord = "Bracelet", mrWhiteTip = "A piece of jewelry"),
    UndercoverWordPair(civilianWord = "Ring", undercoverWord = "Earring", mrWhiteTip = "A small piece of jewelry"),
    UndercoverWordPair(civilianWord = "Microphone", undercoverWord = "Speaker", mrWhiteTip = "Something used for sound"),
    UndercoverWordPair(civilianWord = "Headphones", undercoverWord = "Earbuds", mrWhiteTip = "Something you wear to listen to music"),
    UndercoverWordPair(civilianWord = "Television", undercoverWord = "Radio", mrWhiteTip = "A device used for entertainment at home"),
    UndercoverWordPair(civilianWord = "Projector", undercoverWord = "Screen", mrWhiteTip = "Something used to show a movie"),
    UndercoverWordPair(civilianWord = "Calculator", undercoverWord = "Typewriter", mrWhiteTip = "An old-fashioned office device"),
    UndercoverWordPair(civilianWord = "Flashlight", undercoverWord = "Lantern", mrWhiteTip = "Something used to light your way at night"),
    UndercoverWordPair(civilianWord = "Tent", undercoverWord = "Cabin", mrWhiteTip = "A place to sleep while camping"),
    UndercoverWordPair(civilianWord = "Compass", undercoverWord = "Map", mrWhiteTip = "Something that helps you navigate"),
    UndercoverWordPair(civilianWord = "Boarding pass", undercoverWord = "ID card", mrWhiteTip = "Something you need at the airport"),
    UndercoverWordPair(civilianWord = "Ticket", undercoverWord = "Invoice", mrWhiteTip = "A piece of paper proving a payment"),
    UndercoverWordPair(civilianWord = "Passport", undercoverWord = "Ticket", mrWhiteTip = "Something you need to travel"),
    UndercoverWordPair(civilianWord = "Subway", undercoverWord = "Taxi", mrWhiteTip = "A way to get around a big city"),
    UndercoverWordPair(civilianWord = "Sky", undercoverWord = "Jet", mrWhiteTip = "Something seen flying above you"),
    UndercoverWordPair(civilianWord = "Motorcycle", undercoverWord = "Scooter", mrWhiteTip = "A two-wheeled motor vehicle"),
    UndercoverWordPair(civilianWord = "Surfboard", undercoverWord = "Skateboard", mrWhiteTip = "A board used for a sport"),
    UndercoverWordPair(civilianWord = "Baseball", undercoverWord = "Football", mrWhiteTip = "A popular American sport"),
    UndercoverWordPair(civilianWord = "Volleyball", undercoverWord = "Basketball", mrWhiteTip = "A sport played with a ball and a net or hoop"),
    UndercoverWordPair(civilianWord = "Table tennis", undercoverWord = "Badminton", mrWhiteTip = "A sport played with a small racket"),
    UndercoverWordPair(civilianWord = "Bakery", undercoverWord = "Butcher", mrWhiteTip = "A shop that sells fresh food"),
    UndercoverWordPair(civilianWord = "Puzzle", undercoverWord = "Crossword", mrWhiteTip = "A brain game solved for fun"),
    UndercoverWordPair(civilianWord = "Cards", undercoverWord = "Dice", mrWhiteTip = "Something used to play a game of chance"),
    UndercoverWordPair(civilianWord = "Bowling", undercoverWord = "Golf", mrWhiteTip = "A leisure sport played at a club"),
    UndercoverWordPair(civilianWord = "Marathon", undercoverWord = "Sprint", mrWhiteTip = "A running race"),
    UndercoverWordPair(civilianWord = "Fencing", undercoverWord = "Archery", mrWhiteTip = "An Olympic sport using a weapon"),
    UndercoverWordPair(civilianWord = "Boxing", undercoverWord = "Karate", mrWhiteTip = "A combat sport"),
    UndercoverWordPair(civilianWord = "Hockey", undercoverWord = "Soccer", mrWhiteTip = "A team sport played with a ball or puck"),
    UndercoverWordPair(civilianWord = "Concert", undercoverWord = "Festival", mrWhiteTip = "A live music event"),
    UndercoverWordPair(civilianWord = "Novel", undercoverWord = "Poem", mrWhiteTip = "A piece of written literature"),
    UndercoverWordPair(civilianWord = "Dictionary", undercoverWord = "Encyclopedia", mrWhiteTip = "A reference book"),
    UndercoverWordPair(civilianWord = "Pharmacist", undercoverWord = "Doctor", mrWhiteTip = "Someone who works in healthcare"),
    UndercoverWordPair(civilianWord = "Engineer", undercoverWord = "Architect", mrWhiteTip = "A profession that designs things"),
    UndercoverWordPair(civilianWord = "Firefighter", undercoverWord = "Policeman", mrWhiteTip = "A profession that keeps people safe"),
    UndercoverWordPair(civilianWord = "Germany", undercoverWord = "France", mrWhiteTip = "A country in Europe"),
    UndercoverWordPair(civilianWord = "Pilot", undercoverWord = "Astronaut", mrWhiteTip = "A profession that involves flying"),
    UndercoverWordPair(civilianWord = "Judge", undercoverWord = "Punishment", mrWhiteTip = "Something related to a courtroom"),
    UndercoverWordPair(civilianWord = "Baker", undercoverWord = "Chef", mrWhiteTip = "Someone who prepares food"),
    UndercoverWordPair(civilianWord = "Farmer", undercoverWord = "Fisherman", mrWhiteTip = "Someone who works outdoors gathering food"),
    UndercoverWordPair(civilianWord = "Blacksmith", undercoverWord = "Carpenter", mrWhiteTip = "A traditional craftsman's job"),
    UndercoverWordPair(civilianWord = "Heaven", undercoverWord = "Hell", mrWhiteTip = "A place people imagine after death"),
    UndercoverWordPair(civilianWord = "Sky", undercoverWord = "Clouds", mrWhiteTip = "Something you see when you look up"),
    UndercoverWordPair(civilianWord = "Japan", undercoverWord = "China", mrWhiteTip = "A large country in East Asia"),
    UndercoverWordPair(civilianWord = "Germany", undercoverWord = "Beer", mrWhiteTip = "Something associated with Oktoberfest"),
    UndercoverWordPair(civilianWord = "Movie", undercoverWord = "Actor", mrWhiteTip = "Something related to Hollywood"),
    UndercoverWordPair(civilianWord = "Screen", undercoverWord = "TV", mrWhiteTip = "Something you watch shows on"),
    UndercoverWordPair(civilianWord = "France", undercoverWord = "Eiffel Tower", mrWhiteTip = "Something associated with Paris"),
    UndercoverWordPair(civilianWord = "Thor", undercoverWord = "Lightning", mrWhiteTip = "Something with electric power"),
    UndercoverWordPair(civilianWord = "Obi Wan", undercoverWord = "Force", mrWhiteTip = "Something from the Star Wars universe"),
    UndercoverWordPair(civilianWord = "UFO", undercoverWord = "Drones", mrWhiteTip = "An unidentified flying object"),
    UndercoverWordPair(civilianWord = "God", undercoverWord = "Heaven", mrWhiteTip = "Something related to religion"),
    UndercoverWordPair(civilianWord = "Tortilla", undercoverWord = "Taco", mrWhiteTip = "A Mexican food staple"),
    UndercoverWordPair(civilianWord = "Baguette", undercoverWord = "Ciabatta", mrWhiteTip = "A type of bread"),
    UndercoverWordPair(civilianWord = "Hot Dog", undercoverWord = "Bratwurst", mrWhiteTip = "A sausage served in a bun"),
    UndercoverWordPair(civilianWord = "Energy Drink", undercoverWord = "Soda", mrWhiteTip = "A fizzy or caffeinated drink"),
    UndercoverWordPair(civilianWord = "Coconut milk", undercoverWord = "soy milk", mrWhiteTip = "A dairy-free milk alternative"),
    UndercoverWordPair(civilianWord = "Picasso", undercoverWord = "Van Gogh", mrWhiteTip = "A famous painter"),
    UndercoverWordPair(civilianWord = "Mozart", undercoverWord = "Beethoven", mrWhiteTip = "A famous classical composer"),
    UndercoverWordPair(civilianWord = "Messi", undercoverWord = "Ronaldo", mrWhiteTip = "A world-famous soccer player"),
    UndercoverWordPair(civilianWord = "Bayern Munich", undercoverWord = "Real Madrid", mrWhiteTip = "A top European football club"),
    UndercoverWordPair(civilianWord = "Ferrari", undercoverWord = "Lamborghini", mrWhiteTip = "An expensive Italian sports car"),
    UndercoverWordPair(civilianWord = "Coca-Cola", undercoverWord = "Pepsi", mrWhiteTip = "A popular soft drink brand"),
    UndercoverWordPair(civilianWord = "London", undercoverWord = "Paris", mrWhiteTip = "A major European capital"),
    UndercoverWordPair(civilianWord = "Los Angeles", undercoverWord = "New York", mrWhiteTip = "A major US city"),
    UndercoverWordPair(civilianWord = "Big Ben", undercoverWord = "Leaning Tower of Pisa", mrWhiteTip = "A famous European tower"),
    UndercoverWordPair(civilianWord = "Statue of Liberty", undercoverWord = "Eiffel Tower", mrWhiteTip = "A tall famous monument"),
    UndercoverWordPair(civilianWord = "Mouse", undercoverWord = "Keyboard", mrWhiteTip = "Something used with a computer"),
    UndercoverWordPair(civilianWord = "TV", undercoverWord = "Laptop", mrWhiteTip = "A screen used for entertainment or work"),
    UndercoverWordPair(civilianWord = "Wardrobe", undercoverWord = "Showcase", mrWhiteTip = "Furniture used for storage or display"),
    UndercoverWordPair(civilianWord = "Birch", undercoverWord = "Shrub", mrWhiteTip = "Something that grows in a garden"),
    UndercoverWordPair(civilianWord = "Radiator", undercoverWord = "Hairdryer", mrWhiteTip = "Something that produces heat"),
    UndercoverWordPair(civilianWord = "Lamp", undercoverWord = "Candle", mrWhiteTip = "Something used to light a room"),
    UndercoverWordPair(civilianWord = "Pillow", undercoverWord = "Blanket", mrWhiteTip = "Something used on a bed"),
    UndercoverWordPair(civilianWord = "Microphone", undercoverWord = "Camera", mrWhiteTip = "Equipment used for recording"),
    UndercoverWordPair(civilianWord = "Oven", undercoverWord = "Microwave", mrWhiteTip = "A kitchen appliance for cooking"),
    UndercoverWordPair(civilianWord = "Pan", undercoverWord = "Pot", mrWhiteTip = "Cookware used on a stove"),
    UndercoverWordPair(civilianWord = "Tablet", undercoverWord = "Smartphone", mrWhiteTip = "A touchscreen electronic device"),
    UndercoverWordPair(civilianWord = "Stairs", undercoverWord = "Elevator", mrWhiteTip = "A way to get to another floor"),
    UndercoverWordPair(civilianWord = "Techno", undercoverWord = "Rap", mrWhiteTip = "A music genre"),
    UndercoverWordPair(civilianWord = "Rock", undercoverWord = "Pop", mrWhiteTip = "A popular music genre"),
    UndercoverWordPair(civilianWord = "Table Tennis", undercoverWord = "Badminton", mrWhiteTip = "A sport played over a net"),
    UndercoverWordPair(civilianWord = "Window", undercoverWord = "Door", mrWhiteTip = "An opening in a wall"),
    UndercoverWordPair(civilianWord = "Oven", undercoverWord = "Heating", mrWhiteTip = "Something that keeps a house warm"),
    UndercoverWordPair(civilianWord = "Wristwatch", undercoverWord = "Alarm Clock", mrWhiteTip = "A device that tells the time"),
    UndercoverWordPair(civilianWord = "Bed", undercoverWord = "Sofa", mrWhiteTip = "Furniture used for sitting or lying down"),
    UndercoverWordPair(civilianWord = "Book", undercoverWord = "Newspaper", mrWhiteTip = "Something you read"),
    UndercoverWordPair(civilianWord = "Forest", undercoverWord = "Park", mrWhiteTip = "A green outdoor space"),
    UndercoverWordPair(civilianWord = "Cinema", undercoverWord = "Bowling", mrWhiteTip = "A fun evening activity"),
    UndercoverWordPair(civilianWord = "Netflix", undercoverWord = "Cinema", mrWhiteTip = "A way to watch a movie"),
    UndercoverWordPair(civilianWord = "Swimming Pool", undercoverWord = "Beach", mrWhiteTip = "A place to cool off on a hot day"),
    UndercoverWordPair(civilianWord = "Glass", undercoverWord = "Cup", mrWhiteTip = "Something you drink from"),
    UndercoverWordPair(civilianWord = "Job", undercoverWord = "Hobby", mrWhiteTip = "Something you spend your time on"),
    UndercoverWordPair(civilianWord = "Jesus", undercoverWord = "Santa Claus", mrWhiteTip = "A figure associated with a December holiday"),
    UndercoverWordPair(civilianWord = "bra", undercoverWord = "bikini", mrWhiteTip = "An item of women's clothing"),
    UndercoverWordPair(civilianWord = "Volcano", undercoverWord = "Geyser", mrWhiteTip = "A natural feature that can erupt"),
    UndercoverWordPair(civilianWord = "Camel", undercoverWord = "Llama", mrWhiteTip = "An animal that can carry heavy loads"),
    UndercoverWordPair(civilianWord = "Kangaroo", undercoverWord = "Koala", mrWhiteTip = "An animal found in Australia"),
    UndercoverWordPair(civilianWord = "Waffle", undercoverWord = "Crepe", mrWhiteTip = "A sweet breakfast food"),
    UndercoverWordPair(civilianWord = "Croissant", undercoverWord = "Bagel", mrWhiteTip = "A baked good for breakfast"),
    UndercoverWordPair(civilianWord = "Yoga", undercoverWord = "Pilates", mrWhiteTip = "A calm form of exercise"),
    UndercoverWordPair(civilianWord = "Hiking", undercoverWord = "Camping", mrWhiteTip = "An outdoor weekend activity"),
    UndercoverWordPair(civilianWord = "Snowboarding", undercoverWord = "Skiing", mrWhiteTip = "A winter sport down a slope"),
    UndercoverWordPair(civilianWord = "Chess", undercoverWord = "Checkers", mrWhiteTip = "A strategy game played on a board"),
    UndercoverWordPair(civilianWord = "Origami", undercoverWord = "Calligraphy", mrWhiteTip = "A traditional art form from Asia"),
    UndercoverWordPair(civilianWord = "Telescope", undercoverWord = "Binoculars", mrWhiteTip = "Something used to see far away"),
    UndercoverWordPair(civilianWord = "Thermometer", undercoverWord = "Stethoscope", mrWhiteTip = "A tool used by a doctor"),
    UndercoverWordPair(civilianWord = "Wheelchair", undercoverWord = "Crutches", mrWhiteTip = "Something that helps you move after an injury"),
    UndercoverWordPair(civilianWord = "Firework", undercoverWord = "Sparkler", mrWhiteTip = "Something that lights up the sky at a celebration"),
    UndercoverWordPair(civilianWord = "Balloon", undercoverWord = "Confetti", mrWhiteTip = "Something used to decorate a party"),
    UndercoverWordPair(civilianWord = "Birthday", undercoverWord = "Anniversary", mrWhiteTip = "A special date celebrated every year"),
    UndercoverWordPair(civilianWord = "Wedding", undercoverWord = "Funeral", mrWhiteTip = "A formal event where people gather"),
    UndercoverWordPair(civilianWord = "Graduation", undercoverWord = "Promotion", mrWhiteTip = "A milestone worth celebrating"),
    UndercoverWordPair(civilianWord = "Backpacking", undercoverWord = "Roadtrip", mrWhiteTip = "A trip taken with very little planning"),
    UndercoverWordPair(civilianWord = "Airport", undercoverWord = "Train Station", mrWhiteTip = "A place where you catch a ride to travel"),
    UndercoverWordPair(civilianWord = "Hotel", undercoverWord = "Hostel", mrWhiteTip = "A place to sleep while traveling"),
    UndercoverWordPair(civilianWord = "Waiter", undercoverWord = "Bartender", mrWhiteTip = "Someone who serves you at a restaurant"),
    UndercoverWordPair(civilianWord = "Barista", undercoverWord = "Chef", mrWhiteTip = "Someone who prepares something you consume"),
    UndercoverWordPair(civilianWord = "Umbrella", undercoverWord = "Raincoat", mrWhiteTip = "Something that keeps you dry"),
    UndercoverWordPair(civilianWord = "Thunder", undercoverWord = "Lightning", mrWhiteTip = "Something that happens during a storm"),
    UndercoverWordPair(civilianWord = "Rainbow", undercoverWord = "Sunset", mrWhiteTip = "A colorful sight in the sky"),
    UndercoverWordPair(civilianWord = "Campfire", undercoverWord = "Fireplace", mrWhiteTip = "A place where wood is burned for warmth"),
    UndercoverWordPair(civilianWord = "Igloo", undercoverWord = "Cabin", mrWhiteTip = "A shelter built in a cold place"),
    UndercoverWordPair(civilianWord = "Penguin", undercoverWord = "Polar Bear", mrWhiteTip = "An animal that lives somewhere cold"),
    UndercoverWordPair(civilianWord = "Cactus", undercoverWord = "Palm Tree", mrWhiteTip = "A plant that thrives in a hot climate"),
    UndercoverWordPair(civilianWord = "Spider", undercoverWord = "Ant", mrWhiteTip = "A small crawling creature"),
    UndercoverWordPair(civilianWord = "Bee", undercoverWord = "Wasp", mrWhiteTip = "An insect that can sting"),
    UndercoverWordPair(civilianWord = "Butterfly", undercoverWord = "Moth", mrWhiteTip = "An insect with colorful wings"),
    UndercoverWordPair(civilianWord = "Recycling", undercoverWord = "Composting", mrWhiteTip = "Something people do to help the environment"),
    UndercoverWordPair(civilianWord = "Solar Panel", undercoverWord = "Wind Turbine", mrWhiteTip = "A way to generate clean energy"),
    UndercoverWordPair(civilianWord = "Electric Car", undercoverWord = "Hybrid Car", mrWhiteTip = "A vehicle that saves fuel"),
    UndercoverWordPair(civilianWord = "Marathon", undercoverWord = "Triathlon", mrWhiteTip = "A grueling endurance event"),
    UndercoverWordPair(civilianWord = "Referee", undercoverWord = "Coach", mrWhiteTip = "Someone involved in running a sports match"),
    UndercoverWordPair(civilianWord = "Stadium", undercoverWord = "Arena", mrWhiteTip = "A big venue where fans watch a game"),
    UndercoverWordPair(civilianWord = "Trophy", undercoverWord = "Medal", mrWhiteTip = "Something you win as a prize"),
    UndercoverWordPair(civilianWord = "Spring", undercoverWord = "Autumn", mrWhiteTip = "A mild season of the year"),
    UndercoverWordPair(civilianWord = "Winter", undercoverWord = "Summer", mrWhiteTip = "A season with distinct weather"),
    UndercoverWordPair(civilianWord = "Earthquake", undercoverWord = "Landslide", mrWhiteTip = "A sudden geological disaster"),
    UndercoverWordPair(civilianWord = "Rainforest", undercoverWord = "Savanna", mrWhiteTip = "A type of natural biome"),
    UndercoverWordPair(civilianWord = "Glacier", undercoverWord = "Iceberg", mrWhiteTip = "A massive chunk of ice"),
    UndercoverWordPair(civilianWord = "Astronaut", undercoverWord = "Cosmonaut", mrWhiteTip = "Someone who travels to space"),
    UndercoverWordPair(civilianWord = "Telescope", undercoverWord = "Microscope", mrWhiteTip = "A scientific instrument for looking closely at something"),
    UndercoverWordPair(civilianWord = "Chemistry", undercoverWord = "Physics", mrWhiteTip = "A science subject taught at school"),
    UndercoverWordPair(civilianWord = "History", undercoverWord = "Geography", mrWhiteTip = "A subject taught at school"),
    UndercoverWordPair(civilianWord = "Algebra", undercoverWord = "Geometry", mrWhiteTip = "A branch of mathematics"),
    UndercoverWordPair(civilianWord = "Violin", undercoverWord = "Cello", mrWhiteTip = "A stringed instrument played with a bow"),
    UndercoverWordPair(civilianWord = "Trumpet", undercoverWord = "Saxophone", mrWhiteTip = "A brass or wind instrument"),
    UndercoverWordPair(civilianWord = "Drums", undercoverWord = "Bass", mrWhiteTip = "An instrument that keeps the rhythm in a band"),
    UndercoverWordPair(civilianWord = "Opera", undercoverWord = "Musical", mrWhiteTip = "A performance with singing on stage"),
    UndercoverWordPair(civilianWord = "Circus", undercoverWord = "Carnival", mrWhiteTip = "A colorful traveling event with entertainment"),
    UndercoverWordPair(civilianWord = "Magician", undercoverWord = "Clown", mrWhiteTip = "A performer who entertains a crowd"),
    UndercoverWordPair(civilianWord = "Zoo", undercoverWord = "Aquarium", mrWhiteTip = "A place where you can see animals"),
    UndercoverWordPair(civilianWord = "Amusement Park", undercoverWord = "Water Park", mrWhiteTip = "A place with rides for a fun day out"),
    UndercoverWordPair(civilianWord = "Roller Coaster", undercoverWord = "Ferris Wheel", mrWhiteTip = "A thrilling ride at a theme park"),
    UndercoverWordPair(civilianWord = "Skydiving", undercoverWord = "Bungee Jumping", mrWhiteTip = "An extreme adventure activity"),
    UndercoverWordPair(civilianWord = "Snorkeling", undercoverWord = "Scuba Diving", mrWhiteTip = "An activity to explore underwater"),
    UndercoverWordPair(civilianWord = "Kayak", undercoverWord = "Canoe", mrWhiteTip = "A small boat you paddle yourself"),
    UndercoverWordPair(civilianWord = "Fishing Rod", undercoverWord = "Net", mrWhiteTip = "A tool used to catch fish"),
    UndercoverWordPair(civilianWord = "Tractor", undercoverWord = "Bulldozer", mrWhiteTip = "A heavy vehicle used for work"),
    UndercoverWordPair(civilianWord = "Crane", undercoverWord = "Forklift", mrWhiteTip = "Machinery used to lift heavy things"),
    UndercoverWordPair(civilianWord = "Skyscraper", undercoverWord = "Tower Block", mrWhiteTip = "A very tall building"),
    UndercoverWordPair(civilianWord = "Cottage", undercoverWord = "Bungalow", mrWhiteTip = "A small cozy house"),
    UndercoverWordPair(civilianWord = "Mansion", undercoverWord = "Villa", mrWhiteTip = "A large luxurious house"),
    UndercoverWordPair(civilianWord = "Balcony", undercoverWord = "Terrace", mrWhiteTip = "An outdoor area attached to a home"),
    UndercoverWordPair(civilianWord = "Garden", undercoverWord = "Backyard", mrWhiteTip = "An outdoor space behind a house"),
    UndercoverWordPair(civilianWord = "Greenhouse", undercoverWord = "Nursery", mrWhiteTip = "A place where plants are grown"),
    UndercoverWordPair(civilianWord = "Beehive", undercoverWord = "Anthill", mrWhiteTip = "A home built by insects"),
    UndercoverWordPair(civilianWord = "Nest", undercoverWord = "Burrow", mrWhiteTip = "A home built by an animal"),
    UndercoverWordPair(civilianWord = "Compass", undercoverWord = "GPS", mrWhiteTip = "Something used for direction"),
    UndercoverWordPair(civilianWord = "Anchor", undercoverWord = "Sail", mrWhiteTip = "Part of a sailing ship"),
    UndercoverWordPair(civilianWord = "Lighthouse", undercoverWord = "Pier", mrWhiteTip = "A structure found along the coast"),
    UndercoverWordPair(civilianWord = "Harbor", undercoverWord = "Marina", mrWhiteTip = "A place where boats are docked"),
    UndercoverWordPair(civilianWord = "Snail", undercoverWord = "Slug", mrWhiteTip = "A slow crawling creature"),
    UndercoverWordPair(civilianWord = "Hedgehog", undercoverWord = "Porcupine", mrWhiteTip = "A small spiky animal"),
    UndercoverWordPair(civilianWord = "Squirrel", undercoverWord = "Chipmunk", mrWhiteTip = "A small animal that collects nuts"),
    UndercoverWordPair(civilianWord = "Owl", undercoverWord = "Falcon", mrWhiteTip = "A bird known for its sharp eyesight"),
    UndercoverWordPair(civilianWord = "Peacock", undercoverWord = "Flamingo", mrWhiteTip = "A bird known for its bright feathers"),
    UndercoverWordPair(civilianWord = "Cheetah", undercoverWord = "Leopard", mrWhiteTip = "A fast wild cat with spots"),
    UndercoverWordPair(civilianWord = "Suitcase", undercoverWord = "Duffel Bag", mrWhiteTip = "Something used to carry luggage"),
    UndercoverWordPair(civilianWord = "Sunscreen", undercoverWord = "Sun Hat", mrWhiteTip = "Something used to protect you from the sun"),
)

val UNDERCOVER_WORD_PAIRS_DE: List<UndercoverWordPair> = listOf(
    UndercoverWordPair(civilianWord = "Hund", undercoverWord = "Katze", mrWhiteTip = "Ein häufiges Haustier mit Fell"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Burger", mrWhiteTip = "Ein beliebtes Fast-Food-Gericht"),
    UndercoverWordPair(civilianWord = "Strand", undercoverWord = "Berg", mrWhiteTip = "Ein beliebtes Urlaubsziel"),
    UndercoverWordPair(civilianWord = "Kaffee", undercoverWord = "Tee", mrWhiteTip = "Ein heißes Getränk am Morgen"),
    UndercoverWordPair(civilianWord = "Auto", undercoverWord = "Bus", mrWhiteTip = "Ein Fahrzeug, mit dem man durch die Stadt kommt"),
    UndercoverWordPair(civilianWord = "Sonne", undercoverWord = "Mond", mrWhiteTip = "Etwas Helles am Himmel"),
    UndercoverWordPair(civilianWord = "Banane", undercoverWord = "Apfel", mrWhiteTip = "Ein Obst als Pausensnack"),
    UndercoverWordPair(civilianWord = "Parfüm", undercoverWord = "Deo", mrWhiteTip = "Etwas, das man sprüht, um gut zu riechen"),
    UndercoverWordPair(civilianWord = "Adidas", undercoverWord = "Nike", mrWhiteTip = "Eine bekannte Sportbekleidungsmarke"),
    UndercoverWordPair(civilianWord = "Rucksack", undercoverWord = "Koffer", mrWhiteTip = "Etwas, das man für eine Reise packt"),
    UndercoverWordPair(civilianWord = "Whirlpool", undercoverWord = "Sauna", mrWhiteTip = "Ein entspannendes Wellness-Angebot mit Wärme oder Wasser"),
    UndercoverWordPair(civilianWord = "Turnschuhe", undercoverWord = "Sandalen", mrWhiteTip = "Schuhe für warmes Wetter"),
    UndercoverWordPair(civilianWord = "Sonnenbrille", undercoverWord = "Taucherbrille", mrWhiteTip = "Etwas, das man vor den Augen trägt"),
    UndercoverWordPair(civilianWord = "Klavier", undercoverWord = "Gitarre", mrWhiteTip = "Ein Musikinstrument, das man mit den Händen spielt"),
    UndercoverWordPair(civilianWord = "Kreuzfahrt", undercoverWord = "Safari", mrWhiteTip = "Ein abenteuerlicher Urlaub"),
    UndercoverWordPair(civilianWord = "Sushi", undercoverWord = "Pizza", mrWhiteTip = "Ein Gericht, das man zum Abendessen bestellt"),
    UndercoverWordPair(civilianWord = "Hamburger", undercoverWord = "Hotdog", mrWhiteTip = "Klassisches Essen vom Grillfest"),
    UndercoverWordPair(civilianWord = "Schokolade", undercoverWord = "Vanille", mrWhiteTip = "Eine beliebte Eissorte"),
    UndercoverWordPair(civilianWord = "Bier", undercoverWord = "Wein", mrWhiteTip = "Ein alkoholisches Getränk zum Essen"),
    UndercoverWordPair(civilianWord = "Whiskey", undercoverWord = "Wodka", mrWhiteTip = "Ein starker alkoholischer Schnaps"),
    UndercoverWordPair(civilianWord = "Milch", undercoverWord = "Saft", mrWhiteTip = "Ein Getränk zum Frühstück"),
    UndercoverWordPair(civilianWord = "Brot", undercoverWord = "Butter", mrWhiteTip = "Etwas, das auf dem Frühstückstisch steht"),
    UndercoverWordPair(civilianWord = "Reis", undercoverWord = "Nudeln", mrWhiteTip = "Eine Kohlenhydrat-Beilage"),
    UndercoverWordPair(civilianWord = "Hühnchen", undercoverWord = "Rindfleisch", mrWhiteTip = "Eine Fleischsorte zum Abendessen"),
    UndercoverWordPair(civilianWord = "Apfel", undercoverWord = "Orange", mrWhiteTip = "Ein Obst in der Obstschale"),
    UndercoverWordPair(civilianWord = "Banane", undercoverWord = "Erdbeere", mrWhiteTip = "Ein Obst für einen Smoothie"),
    UndercoverWordPair(civilianWord = "Karotte", undercoverWord = "Brokkoli", mrWhiteTip = "Ein gesundes Gemüse"),
    UndercoverWordPair(civilianWord = "Kartoffel", undercoverWord = "Tomate", mrWhiteTip = "Ein Gemüse aus dem Garten"),
    UndercoverWordPair(civilianWord = "Zwiebel", undercoverWord = "Knoblauch", mrWhiteTip = "Eine würzige Zutat beim Kochen"),
    UndercoverWordPair(civilianWord = "Salz", undercoverWord = "Pfeffer", mrWhiteTip = "Ein Gewürz auf dem Esstisch"),
    UndercoverWordPair(civilianWord = "Zucker", undercoverWord = "Honig", mrWhiteTip = "Etwas Süßes für den Tee"),
    UndercoverWordPair(civilianWord = "Wasser", undercoverWord = "Limonade", mrWhiteTip = "Ein Getränk zum Essen"),
    UndercoverWordPair(civilianWord = "Apple", undercoverWord = "Microsoft", mrWhiteTip = "Ein großer Technologiekonzern"),
    UndercoverWordPair(civilianWord = "Google", undercoverWord = "Facebook", mrWhiteTip = "Ein riesiges Internetunternehmen"),
    UndercoverWordPair(civilianWord = "Amazon", undercoverWord = "Netflix", mrWhiteTip = "Ein Online-Dienst mit Abo"),
    UndercoverWordPair(civilianWord = "Pfannkuchen", undercoverWord = "Donut", mrWhiteTip = "Eine süße Leckerei zum Frühstück"),
    UndercoverWordPair(civilianWord = "Eiscreme", undercoverWord = "Kuchen", mrWhiteTip = "Ein Dessert bei einer Geburtstagsfeier"),
    UndercoverWordPair(civilianWord = "McDonalds", undercoverWord = "KFC", mrWhiteTip = "Eine Fast-Food-Kette"),
    UndercoverWordPair(civilianWord = "Auto", undercoverWord = "Fahrrad", mrWhiteTip = "Etwas für kurze Strecken"),
    UndercoverWordPair(civilianWord = "Virus", undercoverWord = "Bakterien", mrWhiteTip = "Ein winziger Erreger, der krank macht"),
    UndercoverWordPair(civilianWord = "Herr der Ringe", undercoverWord = "Der Hobbit", mrWhiteTip = "Eine bekannte Fantasy-Geschichte"),
    UndercoverWordPair(civilianWord = "Harry Potter", undercoverWord = "Lord Voldemort", mrWhiteTip = "Eine bekannte Figur aus einer Zaubergeschichte"),
    UndercoverWordPair(civilianWord = "Superman", undercoverWord = "Batman", mrWhiteTip = "Ein Superheld aus einem Comic"),
    UndercoverWordPair(civilianWord = "Spiderman", undercoverWord = "Ironman", mrWhiteTip = "Ein Marvel-Superheld"),
    UndercoverWordPair(civilianWord = "Captain America", undercoverWord = "Thor", mrWhiteTip = "Ein Avengers-Superheld"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Pasta", mrWhiteTip = "Ein klassisches italienisches Gericht"),
    UndercoverWordPair(civilianWord = "Fußball", undercoverWord = "Basketball", mrWhiteTip = "Eine beliebte Mannschaftssportart"),
    UndercoverWordPair(civilianWord = "Musik", undercoverWord = "Tanzen", mrWhiteTip = "Etwas, das man auf einer Party genießt"),
    UndercoverWordPair(civilianWord = "Hund", undercoverWord = "Wolf", mrWhiteTip = "Ein Tier aus der Hundefamilie"),
    UndercoverWordPair(civilianWord = "Apfel", undercoverWord = "Birne", mrWhiteTip = "Ein Obst, das auf einem Baum wächst"),
    UndercoverWordPair(civilianWord = "Auto", undercoverWord = "LKW", mrWhiteTip = "Ein Fahrzeug mit Motor"),
    UndercoverWordPair(civilianWord = "Bleistift", undercoverWord = "Kugelschreiber", mrWhiteTip = "Ein Schreibwerkzeug"),
    UndercoverWordPair(civilianWord = "Pizza", undercoverWord = "Lasagne", mrWhiteTip = "Ein italienisches Käsegericht"),
    UndercoverWordPair(civilianWord = "Facebook", undercoverWord = "Instagram", mrWhiteTip = "Eine Social-Media-App"),
    UndercoverWordPair(civilianWord = "Sonnenbrille", undercoverWord = "Taucherbrille", mrWhiteTip = "Eine Schutzbrille"),
    UndercoverWordPair(civilianWord = "Laptop", undercoverWord = "Tablet", mrWhiteTip = "Ein elektronisches Gerät zum Surfen"),
    UndercoverWordPair(civilianWord = "Arzt", undercoverWord = "Chirurg", mrWhiteTip = "Ein Beruf, der kranken Menschen hilft"),
    UndercoverWordPair(civilianWord = "Bitcoin", undercoverWord = "Ethereum", mrWhiteTip = "Eine digitale Währung"),
    UndercoverWordPair(civilianWord = "Bombe", undercoverWord = "Gewehr", mrWhiteTip = "Eine gefährliche Waffe"),
    UndercoverWordPair(civilianWord = "Einstein", undercoverWord = "Newton", mrWhiteTip = "Ein berühmter Wissenschaftler"),
    UndercoverWordPair(civilianWord = "Hemd", undercoverWord = "Pullover", mrWhiteTip = "Ein Kleidungsstück für den Oberkörper"),
    UndercoverWordPair(civilianWord = "Uhr", undercoverWord = "Ring", mrWhiteTip = "Ein Schmuckstück für Hand oder Handgelenk"),
    UndercoverWordPair(civilianWord = "Fußball", undercoverWord = "Rugby", mrWhiteTip = "Ein Sport auf einem Feld mit Ball"),
    UndercoverWordPair(civilianWord = "Flugzeug", undercoverWord = "Hubschrauber", mrWhiteTip = "Ein fliegendes Fahrzeug"),
    UndercoverWordPair(civilianWord = "Fluss", undercoverWord = "See", mrWhiteTip = "Ein Gewässer mit Süßwasser"),
    UndercoverWordPair(civilianWord = "Ozean", undercoverWord = "Fluss", mrWhiteTip = "Ein großes Gewässer"),
    UndercoverWordPair(civilianWord = "Lehrer", undercoverWord = "Professor", mrWhiteTip = "Jemand, der Schüler unterrichtet"),
    UndercoverWordPair(civilianWord = "Fahrrad", undercoverWord = "Motorrad", mrWhiteTip = "Ein Fahrzeug mit zwei Rädern"),
    UndercoverWordPair(civilianWord = "Salz", undercoverWord = "Zucker", mrWhiteTip = "Ein weißes Gewürz in der Küche"),
    UndercoverWordPair(civilianWord = "Messer", undercoverWord = "Schere", mrWhiteTip = "Ein scharfes Werkzeug zum Schneiden"),
    UndercoverWordPair(civilianWord = "Stuhl", undercoverWord = "Bank", mrWhiteTip = "Etwas, worauf man sitzt"),
    UndercoverWordPair(civilianWord = "Burg", undercoverWord = "Haus", mrWhiteTip = "Ein Ort, an dem Menschen leben"),
    UndercoverWordPair(civilianWord = "Zug", undercoverWord = "U-Bahn", mrWhiteTip = "Ein öffentliches Verkehrsmittel"),
    UndercoverWordPair(civilianWord = "Spiegel", undercoverWord = "Fensterscheibe", mrWhiteTip = "Etwas aus Glas"),
    UndercoverWordPair(civilianWord = "Maus", undercoverWord = "Ratte", mrWhiteTip = "Ein kleines Nagetier"),
    UndercoverWordPair(civilianWord = "Schaufel", undercoverWord = "Axt", mrWhiteTip = "Ein Werkzeug für draußen"),
    UndercoverWordPair(civilianWord = "Gurke", undercoverWord = "Zucchini", mrWhiteTip = "Ein grünes Gemüse"),
    UndercoverWordPair(civilianWord = "Erdbeere", undercoverWord = "Himbeere", mrWhiteTip = "Eine kleine rote Beere"),
    UndercoverWordPair(civilianWord = "Banane", undercoverWord = "Kochbanane", mrWhiteTip = "Eine lange gelbe Frucht"),
    UndercoverWordPair(civilianWord = "Kokosnuss", undercoverWord = "Ananas", mrWhiteTip = "Eine tropische Frucht"),
    UndercoverWordPair(civilianWord = "Drache", undercoverWord = "Dinosaurier", mrWhiteTip = "Ein riesiges Wesen aus Sagen oder der Urzeit"),
    UndercoverWordPair(civilianWord = "Geist", undercoverWord = "Zombie", mrWhiteTip = "Ein gruseliges Wesen aus Horrorfilmen"),
    UndercoverWordPair(civilianWord = "Küchentheke", undercoverWord = "Küchenchef", mrWhiteTip = "Etwas in einer Restaurantküche"),
    UndercoverWordPair(civilianWord = "Pyramide", undercoverWord = "Tempel", mrWhiteTip = "Ein antikes Steinbauwerk"),
    UndercoverWordPair(civilianWord = "Vulkan", undercoverWord = "Berg", mrWhiteTip = "Eine hohe natürliche Landform"),
    UndercoverWordPair(civilianWord = "Wüste", undercoverWord = "Sand", mrWhiteTip = "Ein heißer trockener Ort"),
    UndercoverWordPair(civilianWord = "Wolke", undercoverWord = "Nebel", mrWhiteTip = "Etwas, das den Himmel diesig macht"),
    UndercoverWordPair(civilianWord = "Schnee", undercoverWord = "Hagel", mrWhiteTip = "Etwas, das im Winter vom Himmel fällt"),
    UndercoverWordPair(civilianWord = "Detektiv", undercoverWord = "Verbrecher", mrWhiteTip = "Eine Figur aus einer Krimigeschichte"),
    UndercoverWordPair(civilianWord = "Dschungel", undercoverWord = "Wald", mrWhiteTip = "Ein Ort voller Bäume"),
    UndercoverWordPair(civilianWord = "Uhr", undercoverWord = "Armbanduhr", mrWhiteTip = "Etwas, das die Uhrzeit zeigt"),
    UndercoverWordPair(civilianWord = "Brot", undercoverWord = "Toast", mrWhiteTip = "Etwas aus gebackenem Teig"),
    UndercoverWordPair(civilianWord = "Gemälde", undercoverWord = "Skizze", mrWhiteTip = "Ein Kunstwerk"),
    UndercoverWordPair(civilianWord = "Regenschirm", undercoverWord = "Sonnenschirm", mrWhiteTip = "Etwas, das man gegen Sonne oder Regen mitnimmt"),
    UndercoverWordPair(civilianWord = "Anzug", undercoverWord = "Krawatte", mrWhiteTip = "Formelle Kleidung für die Arbeit"),
    UndercoverWordPair(civilianWord = "Socken", undercoverWord = "Strumpfhosen", mrWhiteTip = "Etwas, das man an Füßen oder Beinen trägt"),
    UndercoverWordPair(civilianWord = "Gürtel", undercoverWord = "Jeans", mrWhiteTip = "Ein Kleidungsstück um die Hüfte"),
    UndercoverWordPair(civilianWord = "Krone", undercoverWord = "Hut", mrWhiteTip = "Etwas, das man auf dem Kopf trägt"),
    UndercoverWordPair(civilianWord = "Ballett", undercoverWord = "Hip Hop", mrWhiteTip = "Ein Tanzstil"),
    UndercoverWordPair(civilianWord = "Papagei", undercoverWord = "Krähe", mrWhiteTip = "Eine Vogelart"),
    UndercoverWordPair(civilianWord = "Fledermaus", undercoverWord = "Eule", mrWhiteTip = "Ein nachtaktives Tier"),
    UndercoverWordPair(civilianWord = "Kerze", undercoverWord = "Laterne", mrWhiteTip = "Etwas, das einen dunklen Raum beleuchtet"),
    UndercoverWordPair(civilianWord = "Bibliothek", undercoverWord = "Universität", mrWhiteTip = "Ein Ort voller Bücher und Studenten"),
    UndercoverWordPair(civilianWord = "Museum", undercoverWord = "Galerie", mrWhiteTip = "Ein Ort, um Kunst oder Geschichte zu sehen"),
    UndercoverWordPair(civilianWord = "Radio", undercoverWord = "Podcast", mrWhiteTip = "Etwas, das man zur Unterhaltung hört"),
    UndercoverWordPair(civilianWord = "Online Nachrichten", undercoverWord = "Zeitung", mrWhiteTip = "Eine tägliche Nachrichtenquelle"),
    UndercoverWordPair(civilianWord = "Kugelschreiber", undercoverWord = "Blatt Papier", mrWhiteTip = "Etwas zum Schreiben eines Briefes"),
    UndercoverWordPair(civilianWord = "Mond", undercoverWord = "Sonne", mrWhiteTip = "Ein Objekt, das den Himmel erhellt"),
    UndercoverWordPair(civilianWord = "Tennis", undercoverWord = "Badminton", mrWhiteTip = "Ein Schlägersport"),
    UndercoverWordPair(civilianWord = "Skifahren", undercoverWord = "Schnee", mrWhiteTip = "Eine Winteraktivität"),
    UndercoverWordPair(civilianWord = "Schwimmen", undercoverWord = "Tauchen", mrWhiteTip = "Eine Aktivität im Wasser"),
    UndercoverWordPair(civilianWord = "Laufen", undercoverWord = "Joggen", mrWhiteTip = "Eine Ausdauersportart"),
    UndercoverWordPair(civilianWord = "Aufzug", undercoverWord = "Rolltreppe", mrWhiteTip = "Etwas, das dich zwischen Stockwerken bewegt"),
    UndercoverWordPair(civilianWord = "Fähre", undercoverWord = "Kreuzfahrt", mrWhiteTip = "Eine Bootsreise"),
    UndercoverWordPair(civilianWord = "Karte", undercoverWord = "GPS", mrWhiteTip = "Etwas, das dir hilft, den Weg zu finden"),
    UndercoverWordPair(civilianWord = "Segelboot", undercoverWord = "Yacht", mrWhiteTip = "Ein Boot auf dem Wasser"),
    UndercoverWordPair(civilianWord = "Meteor", undercoverWord = "Satellit", mrWhiteTip = "Etwas am Nachthimmel"),
    UndercoverWordPair(civilianWord = "Planet", undercoverWord = "Stern", mrWhiteTip = "Ein Himmelskörper im Weltraum"),
    UndercoverWordPair(civilianWord = "Erdbeben", undercoverWord = "Tsunami", mrWhiteTip = "Eine gefährliche Naturkatastrophe"),
    UndercoverWordPair(civilianWord = "Qualle", undercoverWord = "Tintenfisch", mrWhiteTip = "Ein Meerestier"),
    UndercoverWordPair(civilianWord = "Wolf", undercoverWord = "Fuchs", mrWhiteTip = "Ein wildes Tier aus der Hundefamilie"),
    UndercoverWordPair(civilianWord = "Elvis", undercoverWord = "The Beatles", mrWhiteTip = "Ein berühmter Musiker aus der Vergangenheit"),
    UndercoverWordPair(civilianWord = "Leonardo da Vinci", undercoverWord = "Michelangelo", mrWhiteTip = "Ein berühmter Künstler der Renaissance"),
    UndercoverWordPair(civilianWord = "Napoleon", undercoverWord = "Cäsar", mrWhiteTip = "Ein mächtiger Feldherr der Geschichte"),
    UndercoverWordPair(civilianWord = "Mario", undercoverWord = "Luigi", mrWhiteTip = "Eine Figur aus einem Videospiel"),
    UndercoverWordPair(civilianWord = "Sonic", undercoverWord = "Tails", mrWhiteTip = "Eine Figur aus einem Videospiel"),
    UndercoverWordPair(civilianWord = "Pac-Man", undercoverWord = "Tetris", mrWhiteTip = "Ein klassisches Videospiel"),
    UndercoverWordPair(civilianWord = "Fortnite", undercoverWord = "Minecraft", mrWhiteTip = "Ein beliebtes Videospiel"),
    UndercoverWordPair(civilianWord = "Call of Duty", undercoverWord = "Battlefield", mrWhiteTip = "Ein Kriegsvideospiel"),
    UndercoverWordPair(civilianWord = "Game of Thrones", undercoverWord = "Herr der Ringe", mrWhiteTip = "Eine berühmte Fantasy-Serie oder -Buch"),
    UndercoverWordPair(civilianWord = "Star Wars", undercoverWord = "Star Trek", mrWhiteTip = "Ein berühmtes Science-Fiction-Franchise"),
    UndercoverWordPair(civilianWord = "Harry Potter", undercoverWord = "Percy Jackson", mrWhiteTip = "Eine Buchreihe über einen jungen Helden"),
    UndercoverWordPair(civilianWord = "Sherlock Holmes", undercoverWord = "Hercule Poirot", mrWhiteTip = "Ein berühmter fiktiver Detektiv"),
    UndercoverWordPair(civilianWord = "Dracula", undercoverWord = "Frankenstein", mrWhiteTip = "Ein klassisches Horrorfilm-Monster"),
    UndercoverWordPair(civilianWord = "James Bond", undercoverWord = "Geheimdienst", mrWhiteTip = "Eine berühmte Spionagefigur"),
    UndercoverWordPair(civilianWord = "Homer Simpson", undercoverWord = "Peter Griffin", mrWhiteTip = "Eine Figur aus einer Zeichentrickserie"),
    UndercoverWordPair(civilianWord = "SpongeBob", undercoverWord = "Patrick", mrWhiteTip = "Eine Figur aus einem Cartoon unter Wasser"),
    UndercoverWordPair(civilianWord = "Godzilla", undercoverWord = "King Kong", mrWhiteTip = "Ein riesiges Filmmonster"),
    UndercoverWordPair(civilianWord = "Lego", undercoverWord = "Playmobil", mrWhiteTip = "Ein Bauspielzeug für Kinder"),
    UndercoverWordPair(civilianWord = "UNO", undercoverWord = "Monopoly", mrWhiteTip = "Ein klassisches Karten- oder Brettspiel"),
    UndercoverWordPair(civilianWord = "Catan", undercoverWord = "Risiko", mrWhiteTip = "Ein Strategie-Brettspiel"),
    UndercoverWordPair(civilianWord = "Blackjack", undercoverWord = "Poker", mrWhiteTip = "Ein Kartenspiel im Casino"),
    UndercoverWordPair(civilianWord = "Bingo", undercoverWord = "Roulette", mrWhiteTip = "Ein Glücksspiel im Casino"),
    UndercoverWordPair(civilianWord = "New York", undercoverWord = "Los Angeles", mrWhiteTip = "Eine berühmte US-Stadt"),
    UndercoverWordPair(civilianWord = "Paris", undercoverWord = "London", mrWhiteTip = "Eine große europäische Hauptstadt"),
    UndercoverWordPair(civilianWord = "Rom", undercoverWord = "Athen", mrWhiteTip = "Eine antike europäische Hauptstadt"),
    UndercoverWordPair(civilianWord = "Sydney", undercoverWord = "Melbourne", mrWhiteTip = "Eine große australische Stadt"),
    UndercoverWordPair(civilianWord = "Rio de Janeiro", undercoverWord = "Buenos Aires", mrWhiteTip = "Eine große südamerikanische Stadt"),
    UndercoverWordPair(civilianWord = "Mount Everest", undercoverWord = "Nepal", mrWhiteTip = "Etwas rund um den höchsten Berg der Welt"),
    UndercoverWordPair(civilianWord = "Amazonas", undercoverWord = "Nil", mrWhiteTip = "Einer der längsten Flüsse der Welt"),
    UndercoverWordPair(civilianWord = "Grand Canyon", undercoverWord = "Niagarafälle", mrWhiteTip = "Ein berühmtes Naturwunder in Nordamerika"),
    UndercoverWordPair(civilianWord = "Taj Mahal", undercoverWord = "Chinesische Mauer", mrWhiteTip = "Ein berühmtes Weltwunder"),
    UndercoverWordPair(civilianWord = "Eiffelturm", undercoverWord = "Freiheitsstatue", mrWhiteTip = "Ein berühmtes Denkmal zum Besichtigen"),
    UndercoverWordPair(civilianWord = "Big Ben", undercoverWord = "Schiefer Turm von Pisa", mrWhiteTip = "Ein berühmter Turm"),
    UndercoverWordPair(civilianWord = "Olympia", undercoverWord = "WM", mrWhiteTip = "Ein großes internationales Sportereignis"),
    UndercoverWordPair(civilianWord = "NBA", undercoverWord = "NFL", mrWhiteTip = "Eine große amerikanische Sportliga"),
    UndercoverWordPair(civilianWord = "Golf", undercoverWord = "Cricket", mrWhiteTip = "Ein Sport mit Schläger oder Keule"),
    UndercoverWordPair(civilianWord = "UFC", undercoverWord = "WWE", mrWhiteTip = "Ein Kampfsport im Fernsehen"),
    UndercoverWordPair(civilianWord = "Twitch", undercoverWord = "Netflix", mrWhiteTip = "Eine Plattform für Videoinhalte"),
    UndercoverWordPair(civilianWord = "Twitter", undercoverWord = "Facebook", mrWhiteTip = "Eine bekannte Social-Media-Plattform"),
    UndercoverWordPair(civilianWord = "SpaceX", undercoverWord = "Tesla", mrWhiteTip = "Ein Unternehmen von Elon Musk"),
    UndercoverWordPair(civilianWord = "Burger King", undercoverWord = "McDonald’s", mrWhiteTip = "Eine Fast-Food-Burgerkette"),
    UndercoverWordPair(civilianWord = "Sony", undercoverWord = "Samsung", mrWhiteTip = "Eine große Elektronikmarke"),
    UndercoverWordPair(civilianWord = "Mercedes", undercoverWord = "BMW", mrWhiteTip = "Eine deutsche Luxusautomarke"),
    UndercoverWordPair(civilianWord = "Harvard", undercoverWord = "MIT", mrWhiteTip = "Eine angesehene amerikanische Universität"),
    UndercoverWordPair(civilianWord = "Oxford", undercoverWord = "Schule", mrWhiteTip = "Ein bekannter Bildungsort"),
    UndercoverWordPair(civilianWord = "CIA", undercoverWord = "FBI", mrWhiteTip = "Eine US-Behörde"),
    UndercoverWordPair(civilianWord = "Tesla", undercoverWord = "Porsche", mrWhiteTip = "Eine Marke für schnelle Autos"),
    UndercoverWordPair(civilianWord = "iPhone", undercoverWord = "Samsung", mrWhiteTip = "Eine beliebte Smartphone-Marke"),
    UndercoverWordPair(civilianWord = "PlayStation", undercoverWord = "Xbox", mrWhiteTip = "Eine Videospielkonsole"),
    UndercoverWordPair(civilianWord = "Windows", undercoverWord = "MacOS", mrWhiteTip = "Ein Computer-Betriebssystem"),
    UndercoverWordPair(civilianWord = "YouTube", undercoverWord = "TikTok", mrWhiteTip = "Eine Videoplattform"),
    UndercoverWordPair(civilianWord = "Twitch", undercoverWord = "Kick", mrWhiteTip = "Eine Live-Streaming-Plattform"),
    UndercoverWordPair(civilianWord = "Spotify", undercoverWord = "Apple Music", mrWhiteTip = "Ein Musik-Streamingdienst"),
    UndercoverWordPair(civilianWord = "Reddit", undercoverWord = "Discord", mrWhiteTip = "Eine Online-Community-Plattform"),
    UndercoverWordPair(civilianWord = "Instagram", undercoverWord = "Snapchat", mrWhiteTip = "Eine Foto-Social-App"),
    UndercoverWordPair(civilianWord = "ChatGPT", undercoverWord = "Gemini", mrWhiteTip = "Ein KI-Chatbot"),
    UndercoverWordPair(civilianWord = "Uhr", undercoverWord = "Sonnenuhr", mrWhiteTip = "Ein Gerät zur Zeitanzeige"),
    UndercoverWordPair(civilianWord = "Tiger", undercoverWord = "Gepard", mrWhiteTip = "Eine schnelle Raubkatze"),
    UndercoverWordPair(civilianWord = "Laptop", undercoverWord = "Desktop", mrWhiteTip = "Ein Computer für die Arbeit"),
    UndercoverWordPair(civilianWord = "Hai", undercoverWord = "Delfin", mrWhiteTip = "Ein großes Meerestier"),
    UndercoverWordPair(civilianWord = "Pinguin", undercoverWord = "Möwe", mrWhiteTip = "Ein Vogel am Meer"),
    UndercoverWordPair(civilianWord = "Mond", undercoverWord = "Planet", mrWhiteTip = "Ein Objekt am Nachthimmel"),
    UndercoverWordPair(civilianWord = "Komet", undercoverWord = "Asteroid", mrWhiteTip = "Ein kleines Objekt im Weltraum"),
    UndercoverWordPair(civilianWord = "Brücke", undercoverWord = "Tunnel", mrWhiteTip = "Etwas, das ein Hindernis überquert"),
    UndercoverWordPair(civilianWord = "Bus", undercoverWord = "Straßenbahn", mrWhiteTip = "Ein öffentliches Verkehrsmittel in der Stadt"),
    UndercoverWordPair(civilianWord = "Zug", undercoverWord = "Bus", mrWhiteTip = "Ein Fahrzeug auf Schienen oder Straße"),
    UndercoverWordPair(civilianWord = "Boot", undercoverWord = "U-Boot", mrWhiteTip = "Ein Fahrzeug auf oder unter Wasser"),
    UndercoverWordPair(civilianWord = "Notizbuch", undercoverWord = "Tagebuch", mrWhiteTip = "Etwas, in das man seine Gedanken schreibt"),
    UndercoverWordPair(civilianWord = "Löffel", undercoverWord = "Gabel", mrWhiteTip = "Ein Besteckteil zum Essen"),
    UndercoverWordPair(civilianWord = "Bäckerei", undercoverWord = "Metzgerei", mrWhiteTip = "Ein Geschäft mit frischen Lebensmitteln"),
    UndercoverWordPair(civilianWord = "Teller", undercoverWord = "Schüssel", mrWhiteTip = "Etwas, aus dem man isst"),
    UndercoverWordPair(civilianWord = "Brunnen", undercoverWord = "Wasserfall", mrWhiteTip = "Fließendes oder fallendes Wasser"),
    UndercoverWordPair(civilianWord = "See", undercoverWord = "Teich", mrWhiteTip = "Ein kleines stehendes Gewässer"),
    UndercoverWordPair(civilianWord = "Giraffe", undercoverWord = "Zebra", mrWhiteTip = "Ein großes Tier aus Afrika"),
    UndercoverWordPair(civilianWord = "Elefant", undercoverWord = "Nashorn", mrWhiteTip = "Ein großes Tier mit dicker Haut"),
    UndercoverWordPair(civilianWord = "Skorpion", undercoverWord = "Spinne", mrWhiteTip = "Ein giftiges Krabbeltier"),
    UndercoverWordPair(civilianWord = "Tintenfisch", undercoverWord = "Oktopus", mrWhiteTip = "Ein Meerestier mit vielen Armen"),
    UndercoverWordPair(civilianWord = "Gold", undercoverWord = "Silber", mrWhiteTip = "Ein wertvolles Metall"),
    UndercoverWordPair(civilianWord = "Platin", undercoverWord = "Gold", mrWhiteTip = "Ein wertvolles Metall im Schmuck"),
    UndercoverWordPair(civilianWord = "Jacke", undercoverWord = "Mantel", mrWhiteTip = "Kleidung, die draußen warmhält"),
    UndercoverWordPair(civilianWord = "Schal", undercoverWord = "Krawatte", mrWhiteTip = "Etwas, das man um den Hals trägt"),
    UndercoverWordPair(civilianWord = "Stiefel", undercoverWord = "Turnschuhe", mrWhiteTip = "Eine Art Schuh"),
    UndercoverWordPair(civilianWord = "Helm", undercoverWord = "Hut", mrWhiteTip = "Etwas, das den Kopf schützt"),
    UndercoverWordPair(civilianWord = "Halskette", undercoverWord = "Armband", mrWhiteTip = "Ein Schmuckstück"),
    UndercoverWordPair(civilianWord = "Ring", undercoverWord = "Ohrring", mrWhiteTip = "Ein kleines Schmuckstück"),
    UndercoverWordPair(civilianWord = "Mikrofon", undercoverWord = "Lautsprecher", mrWhiteTip = "Etwas für den Ton"),
    UndercoverWordPair(civilianWord = "Kopfhörer", undercoverWord = "Ohrstöpsel", mrWhiteTip = "Etwas, das man zum Musikhören trägt"),
    UndercoverWordPair(civilianWord = "Fernseher", undercoverWord = "Radio", mrWhiteTip = "Ein Gerät für Unterhaltung zu Hause"),
    UndercoverWordPair(civilianWord = "Projektor", undercoverWord = "Leinwand", mrWhiteTip = "Etwas, um einen Film zu zeigen"),
    UndercoverWordPair(civilianWord = "Taschenrechner", undercoverWord = "Schreibmaschine", mrWhiteTip = "Ein altmodisches Bürogerät"),
    UndercoverWordPair(civilianWord = "Taschenlampe", undercoverWord = "Laterne", mrWhiteTip = "Etwas, um nachts den Weg zu beleuchten"),
    UndercoverWordPair(civilianWord = "Zelt", undercoverWord = "Hütte", mrWhiteTip = "Ein Schlafplatz beim Camping"),
    UndercoverWordPair(civilianWord = "Kompass", undercoverWord = "Karte", mrWhiteTip = "Etwas, das bei der Navigation hilft"),
    UndercoverWordPair(civilianWord = "Bordkarte", undercoverWord = "Ausweis", mrWhiteTip = "Etwas, das man am Flughafen braucht"),
    UndercoverWordPair(civilianWord = "Ticket", undercoverWord = "Rechnung", mrWhiteTip = "Ein Zettel als Zahlungsnachweis"),
    UndercoverWordPair(civilianWord = "Reisepass", undercoverWord = "Ticket", mrWhiteTip = "Etwas, das man zum Reisen braucht"),
    UndercoverWordPair(civilianWord = "U-Bahn", undercoverWord = "Taxi", mrWhiteTip = "Eine Möglichkeit, sich in der Stadt fortzubewegen"),
    UndercoverWordPair(civilianWord = "Himmel", undercoverWord = "Jet", mrWhiteTip = "Etwas, das man über sich fliegen sieht"),
    UndercoverWordPair(civilianWord = "Motorrad", undercoverWord = "Roller", mrWhiteTip = "Ein zweirädriges Motorfahrzeug"),
    UndercoverWordPair(civilianWord = "Surfbrett", undercoverWord = "Skateboard", mrWhiteTip = "Ein Brett für eine Sportart"),
    UndercoverWordPair(civilianWord = "Baseball", undercoverWord = "Football", mrWhiteTip = "Ein beliebter amerikanischer Sport"),
    UndercoverWordPair(civilianWord = "Volleyball", undercoverWord = "Basketball", mrWhiteTip = "Ein Sport mit Ball und Netz oder Korb"),
    UndercoverWordPair(civilianWord = "Tischtennis", undercoverWord = "Badminton", mrWhiteTip = "Ein Sport mit kleinem Schläger"),
    UndercoverWordPair(civilianWord = "Puzzle", undercoverWord = "Kreuzworträtsel", mrWhiteTip = "Ein Denkspiel zum Vergnügen"),
    UndercoverWordPair(civilianWord = "Kartenspiel", undercoverWord = "Würfel", mrWhiteTip = "Etwas für ein Glücksspiel"),
    UndercoverWordPair(civilianWord = "Bowling", undercoverWord = "Golf", mrWhiteTip = "Ein Freizeitsport in einem Club"),
    UndercoverWordPair(civilianWord = "Marathon", undercoverWord = "Sprint", mrWhiteTip = "Ein Laufwettbewerb"),
    UndercoverWordPair(civilianWord = "Fechten", undercoverWord = "Bogenschießen", mrWhiteTip = "Eine olympische Sportart mit einer Waffe"),
    UndercoverWordPair(civilianWord = "Boxen", undercoverWord = "Karate", mrWhiteTip = "Ein Kampfsport"),
    UndercoverWordPair(civilianWord = "Hockey", undercoverWord = "Fußball", mrWhiteTip = "Ein Mannschaftssport mit Ball oder Puck"),
    UndercoverWordPair(civilianWord = "Konzert", undercoverWord = "Festival", mrWhiteTip = "Ein Live-Musikevent"),
    UndercoverWordPair(civilianWord = "Netflix", undercoverWord = "Kino", mrWhiteTip = "Eine Art, einen Film zu sehen"),
    UndercoverWordPair(civilianWord = "Roman", undercoverWord = "Gedicht", mrWhiteTip = "Ein literarisches Werk"),
    UndercoverWordPair(civilianWord = "Enzyklopädie", undercoverWord = "Wörterbuch", mrWhiteTip = "Ein Nachschlagewerk"),
    UndercoverWordPair(civilianWord = "Apotheker", undercoverWord = "Arzt", mrWhiteTip = "Jemand, der im Gesundheitswesen arbeitet"),
    UndercoverWordPair(civilianWord = "Ingenieur", undercoverWord = "Architekt", mrWhiteTip = "Ein Beruf, der Dinge entwirft"),
    UndercoverWordPair(civilianWord = "Feuerwehrmann", undercoverWord = "Polizist", mrWhiteTip = "Ein Beruf, der Menschen beschützt"),
    UndercoverWordPair(civilianWord = "Pilot", undercoverWord = "Astronaut", mrWhiteTip = "Ein Beruf, bei dem man fliegt"),
    UndercoverWordPair(civilianWord = "Richter", undercoverWord = "Strafe", mrWhiteTip = "Etwas rund um ein Gericht"),
    UndercoverWordPair(civilianWord = "Bäcker", undercoverWord = "Koch", mrWhiteTip = "Jemand, der Essen zubereitet"),
    UndercoverWordPair(civilianWord = "Bauer", undercoverWord = "Fischer", mrWhiteTip = "Jemand, der draußen Nahrung sammelt"),
    UndercoverWordPair(civilianWord = "Schmied", undercoverWord = "Zimmermann", mrWhiteTip = "Ein traditioneller Handwerksberuf"),
    UndercoverWordPair(civilianWord = "Himmel", undercoverWord = "Hölle", mrWhiteTip = "Ein Ort, den man sich nach dem Tod vorstellt"),
    UndercoverWordPair(civilianWord = "Himmel", undercoverWord = "Wolken", mrWhiteTip = "Etwas, das man beim Nachobenschauen sieht"),
    UndercoverWordPair(civilianWord = "Japan", undercoverWord = "China", mrWhiteTip = "Ein großes Land in Ostasien"),
    UndercoverWordPair(civilianWord = "Deutschland", undercoverWord = "Bier", mrWhiteTip = "Etwas rund ums Oktoberfest"),
    UndercoverWordPair(civilianWord = "Film", undercoverWord = "Schauspieler", mrWhiteTip = "Etwas rund um Hollywood"),
    UndercoverWordPair(civilianWord = "Leinwand", undercoverWord = "Fernseher", mrWhiteTip = "Etwas, auf dem man Sendungen schaut"),
    UndercoverWordPair(civilianWord = "Frankreich", undercoverWord = "Eiffelturm", mrWhiteTip = "Etwas, das mit Paris verbunden ist"),
    UndercoverWordPair(civilianWord = "Deutschland", undercoverWord = "Frankreich", mrWhiteTip = "Ein Nachbarland in Europa"),
    UndercoverWordPair(civilianWord = "Thor", undercoverWord = "Blitz", mrWhiteTip = "Etwas mit elektrischer Kraft"),
    UndercoverWordPair(civilianWord = "Obi Wan", undercoverWord = "Macht", mrWhiteTip = "Etwas aus dem Star-Wars-Universum"),
    UndercoverWordPair(civilianWord = "UFO", undercoverWord = "Drohnen", mrWhiteTip = "Ein unbekanntes Flugobjekt"),
    UndercoverWordPair(civilianWord = "Gott", undercoverWord = "Himmel", mrWhiteTip = "Etwas mit Bezug zur Religion"),
    UndercoverWordPair(civilianWord = "Tortilla", undercoverWord = "Taco", mrWhiteTip = "Ein mexikanisches Grundnahrungsmittel"),
    UndercoverWordPair(civilianWord = "Baguette", undercoverWord = "Ciabatta", mrWhiteTip = "Eine Brotsorte"),
    UndercoverWordPair(civilianWord = "Hot Dog", undercoverWord = "Bratwurst", mrWhiteTip = "Eine Wurst im Brötchen"),
    UndercoverWordPair(civilianWord = "Energy Drink", undercoverWord = "Limonade", mrWhiteTip = "Ein prickelndes oder koffeinhaltiges Getränk"),
    UndercoverWordPair(civilianWord = "Kokosmilch", undercoverWord = "Sojamilch", mrWhiteTip = "Eine milchfreie Milchalternative"),
    UndercoverWordPair(civilianWord = "Picasso", undercoverWord = "Van Gogh", mrWhiteTip = "Ein berühmter Maler"),
    UndercoverWordPair(civilianWord = "Mozart", undercoverWord = "Beethoven", mrWhiteTip = "Ein berühmter klassischer Komponist"),
    UndercoverWordPair(civilianWord = "Messi", undercoverWord = "Ronaldo", mrWhiteTip = "Ein weltberühmter Fußballspieler"),
    UndercoverWordPair(civilianWord = "Bayern München", undercoverWord = "Real Madrid", mrWhiteTip = "Ein europäischer Top-Fußballverein"),
    UndercoverWordPair(civilianWord = "Ferrari", undercoverWord = "Lamborghini", mrWhiteTip = "Ein teurer italienischer Sportwagen"),
    UndercoverWordPair(civilianWord = "Coca-Cola", undercoverWord = "Pepsi", mrWhiteTip = "Eine beliebte Softdrink-Marke"),
    UndercoverWordPair(civilianWord = "London", undercoverWord = "Paris", mrWhiteTip = "Eine große europäische Hauptstadt"),
    UndercoverWordPair(civilianWord = "Los Angeles", undercoverWord = "New York", mrWhiteTip = "Eine große US-Stadt"),
    UndercoverWordPair(civilianWord = "Big Ben", undercoverWord = "Schiefer Turm von Pisa", mrWhiteTip = "Ein berühmter europäischer Turm"),
    UndercoverWordPair(civilianWord = "Freiheitsstatue", undercoverWord = "Eiffelturm", mrWhiteTip = "Ein hohes berühmtes Denkmal"),
    UndercoverWordPair(civilianWord = "Maus", undercoverWord = "Tastatur", mrWhiteTip = "Etwas, das man am Computer benutzt"),
    UndercoverWordPair(civilianWord = "Fernseher", undercoverWord = "Laptop", mrWhiteTip = "Ein Bildschirm für Unterhaltung oder Arbeit"),
    UndercoverWordPair(civilianWord = "Schrank", undercoverWord = "Vitrine", mrWhiteTip = "Möbel zum Aufbewahren oder Ausstellen"),
    UndercoverWordPair(civilianWord = "Birke", undercoverWord = "Strauch", mrWhiteTip = "Etwas, das im Garten wächst"),
    UndercoverWordPair(civilianWord = "Heizung", undercoverWord = "Föhn", mrWhiteTip = "Etwas, das Wärme erzeugt"),
    UndercoverWordPair(civilianWord = "Lampe", undercoverWord = "Kerze", mrWhiteTip = "Etwas, das einen Raum beleuchtet"),
    UndercoverWordPair(civilianWord = "Kissen", undercoverWord = "Decke", mrWhiteTip = "Etwas, das man im Bett benutzt"),
    UndercoverWordPair(civilianWord = "Mikrofon", undercoverWord = "Kamera", mrWhiteTip = "Ausrüstung zum Aufnehmen"),
    UndercoverWordPair(civilianWord = "Ofen", undercoverWord = "Mikrowelle", mrWhiteTip = "Ein Küchengerät zum Kochen"),
    UndercoverWordPair(civilianWord = "Pfanne", undercoverWord = "Topf", mrWhiteTip = "Kochgeschirr für den Herd"),
    UndercoverWordPair(civilianWord = "Tablet", undercoverWord = "Smartphone", mrWhiteTip = "Ein Touchscreen-Gerät"),
    UndercoverWordPair(civilianWord = "Treppe", undercoverWord = "Aufzug", mrWhiteTip = "Ein Weg in ein anderes Stockwerk"),
    UndercoverWordPair(civilianWord = "Techno", undercoverWord = "Rap", mrWhiteTip = "Ein Musikgenre"),
    UndercoverWordPair(civilianWord = "Rock", undercoverWord = "Pop", mrWhiteTip = "Ein beliebtes Musikgenre"),
    UndercoverWordPair(civilianWord = "Tischtennis", undercoverWord = "Badminton", mrWhiteTip = "Ein Sport über ein Netz"),
    UndercoverWordPair(civilianWord = "Fenster", undercoverWord = "Tür", mrWhiteTip = "Eine Öffnung in einer Wand"),
    UndercoverWordPair(civilianWord = "Ofen", undercoverWord = "Heizung", mrWhiteTip = "Etwas, das ein Haus warmhält"),
    UndercoverWordPair(civilianWord = "Armbanduhr", undercoverWord = "Wecker", mrWhiteTip = "Ein Gerät zur Zeitanzeige"),
    UndercoverWordPair(civilianWord = "Bett", undercoverWord = "Sofa", mrWhiteTip = "Möbel zum Sitzen oder Liegen"),
    UndercoverWordPair(civilianWord = "Buch", undercoverWord = "Zeitung", mrWhiteTip = "Etwas zum Lesen"),
    UndercoverWordPair(civilianWord = "Wald", undercoverWord = "Park", mrWhiteTip = "Ein grüner Ort im Freien"),
    UndercoverWordPair(civilianWord = "Kino", undercoverWord = "Bowling", mrWhiteTip = "Eine unterhaltsame Abendaktivität"),
    UndercoverWordPair(civilianWord = "Schwimmbad", undercoverWord = "Strand", mrWhiteTip = "Ein Ort, um sich an einem heißen Tag abzukühlen"),
    UndercoverWordPair(civilianWord = "Glas", undercoverWord = "Tasse", mrWhiteTip = "Etwas, woraus man trinkt"),
    UndercoverWordPair(civilianWord = "Job", undercoverWord = "Hobby", mrWhiteTip = "Etwas, womit man seine Zeit verbringt"),
    UndercoverWordPair(civilianWord = "Jesus", undercoverWord = "Weihnachtsmann", mrWhiteTip = "Eine Figur rund um ein Dezemberfest"),
    UndercoverWordPair(civilianWord = "BH", undercoverWord = "Bikini", mrWhiteTip = "Ein Kleidungsstück für Frauen"),
    UndercoverWordPair(civilianWord = "Vulkan", undercoverWord = "Geysir", mrWhiteTip = "Eine Naturerscheinung, die ausbrechen kann"),
    UndercoverWordPair(civilianWord = "Kamel", undercoverWord = "Lama", mrWhiteTip = "Ein Tier, das schwere Lasten tragen kann"),
    UndercoverWordPair(civilianWord = "Känguru", undercoverWord = "Koala", mrWhiteTip = "Ein Tier aus Australien"),
    UndercoverWordPair(civilianWord = "Waffel", undercoverWord = "Crêpe", mrWhiteTip = "Eine süße Speise zum Frühstück"),
    UndercoverWordPair(civilianWord = "Croissant", undercoverWord = "Bagel", mrWhiteTip = "Ein Gebäck zum Frühstück"),
    UndercoverWordPair(civilianWord = "Yoga", undercoverWord = "Pilates", mrWhiteTip = "Eine ruhige Form von Sport"),
    UndercoverWordPair(civilianWord = "Wandern", undercoverWord = "Camping", mrWhiteTip = "Eine Aktivität am Wochenende in der Natur"),
    UndercoverWordPair(civilianWord = "Snowboarden", undercoverWord = "Skifahren", mrWhiteTip = "Ein Wintersport auf einer Piste"),
    UndercoverWordPair(civilianWord = "Schach", undercoverWord = "Dame", mrWhiteTip = "Ein Strategiespiel auf einem Brett"),
    UndercoverWordPair(civilianWord = "Origami", undercoverWord = "Kalligrafie", mrWhiteTip = "Eine traditionelle Kunstform aus Asien"),
    UndercoverWordPair(civilianWord = "Teleskop", undercoverWord = "Fernglas", mrWhiteTip = "Etwas, um weit entfernte Dinge zu sehen"),
    UndercoverWordPair(civilianWord = "Thermometer", undercoverWord = "Stethoskop", mrWhiteTip = "Ein Werkzeug, das ein Arzt benutzt"),
    UndercoverWordPair(civilianWord = "Rollstuhl", undercoverWord = "Krücken", mrWhiteTip = "Etwas, das nach einer Verletzung beim Bewegen hilft"),
    UndercoverWordPair(civilianWord = "Feuerwerk", undercoverWord = "Wunderkerze", mrWhiteTip = "Etwas, das den Himmel bei einer Feier erhellt"),
    UndercoverWordPair(civilianWord = "Luftballon", undercoverWord = "Konfetti", mrWhiteTip = "Etwas zur Partydekoration"),
    UndercoverWordPair(civilianWord = "Geburtstag", undercoverWord = "Jahrestag", mrWhiteTip = "Ein besonderes Datum, das jedes Jahr gefeiert wird"),
    UndercoverWordPair(civilianWord = "Hochzeit", undercoverWord = "Beerdigung", mrWhiteTip = "Ein feierliches Ereignis, bei dem Menschen zusammenkommen"),
    UndercoverWordPair(civilianWord = "Abschlussfeier", undercoverWord = "Beförderung", mrWhiteTip = "Ein Meilenstein, den man feiert"),
    UndercoverWordPair(civilianWord = "Rucksackreise", undercoverWord = "Roadtrip", mrWhiteTip = "Eine Reise mit wenig Planung"),
    UndercoverWordPair(civilianWord = "Flughafen", undercoverWord = "Bahnhof", mrWhiteTip = "Ein Ort, an dem man in ein Verkehrsmittel steigt"),
    UndercoverWordPair(civilianWord = "Hotel", undercoverWord = "Hostel", mrWhiteTip = "Ein Ort zum Übernachten auf Reisen"),
    UndercoverWordPair(civilianWord = "Kellner", undercoverWord = "Barkeeper", mrWhiteTip = "Jemand, der dich in einem Restaurant bedient"),
    UndercoverWordPair(civilianWord = "Barista", undercoverWord = "Koch", mrWhiteTip = "Jemand, der etwas zubereitet, das du konsumierst"),
    UndercoverWordPair(civilianWord = "Regenschirm", undercoverWord = "Regenmantel", mrWhiteTip = "Etwas, das dich trocken hält"),
    UndercoverWordPair(civilianWord = "Donner", undercoverWord = "Blitz", mrWhiteTip = "Etwas, das während eines Gewitters passiert"),
    UndercoverWordPair(civilianWord = "Regenbogen", undercoverWord = "Sonnenuntergang", mrWhiteTip = "Ein farbenfroher Anblick am Himmel"),
    UndercoverWordPair(civilianWord = "Lagerfeuer", undercoverWord = "Kamin", mrWhiteTip = "Ein Ort, an dem Holz zum Wärmen verbrannt wird"),
    UndercoverWordPair(civilianWord = "Iglu", undercoverWord = "Hütte", mrWhiteTip = "Eine Unterkunft an einem kalten Ort"),
    UndercoverWordPair(civilianWord = "Pinguin", undercoverWord = "Eisbär", mrWhiteTip = "Ein Tier, das an einem kalten Ort lebt"),
    UndercoverWordPair(civilianWord = "Kaktus", undercoverWord = "Palme", mrWhiteTip = "Eine Pflanze, die in heißem Klima wächst"),
    UndercoverWordPair(civilianWord = "Spinne", undercoverWord = "Ameise", mrWhiteTip = "Ein kleines krabbelndes Tier"),
    UndercoverWordPair(civilianWord = "Biene", undercoverWord = "Wespe", mrWhiteTip = "Ein Insekt, das stechen kann"),
    UndercoverWordPair(civilianWord = "Schmetterling", undercoverWord = "Motte", mrWhiteTip = "Ein Insekt mit bunten Flügeln"),
    UndercoverWordPair(civilianWord = "Recycling", undercoverWord = "Kompostieren", mrWhiteTip = "Etwas, das man für die Umwelt tut"),
    UndercoverWordPair(civilianWord = "Solarpanel", undercoverWord = "Windrad", mrWhiteTip = "Eine Möglichkeit, saubere Energie zu erzeugen"),
    UndercoverWordPair(civilianWord = "Elektroauto", undercoverWord = "Hybridauto", mrWhiteTip = "Ein Fahrzeug, das Kraftstoff spart"),
    UndercoverWordPair(civilianWord = "Marathon", undercoverWord = "Triathlon", mrWhiteTip = "Ein anstrengender Ausdauerwettbewerb"),
    UndercoverWordPair(civilianWord = "Schiedsrichter", undercoverWord = "Trainer", mrWhiteTip = "Jemand, der bei einem Sportspiel eine Rolle spielt"),
    UndercoverWordPair(civilianWord = "Stadion", undercoverWord = "Arena", mrWhiteTip = "Ein großer Ort, an dem Fans ein Spiel verfolgen"),
    UndercoverWordPair(civilianWord = "Pokal", undercoverWord = "Medaille", mrWhiteTip = "Etwas, das man als Preis gewinnt"),
    UndercoverWordPair(civilianWord = "Frühling", undercoverWord = "Herbst", mrWhiteTip = "Eine milde Jahreszeit"),
    UndercoverWordPair(civilianWord = "Winter", undercoverWord = "Sommer", mrWhiteTip = "Eine Jahreszeit mit typischem Wetter"),
    UndercoverWordPair(civilianWord = "Erdbeben", undercoverWord = "Erdrutsch", mrWhiteTip = "Eine plötzliche geologische Katastrophe"),
    UndercoverWordPair(civilianWord = "Regenwald", undercoverWord = "Savanne", mrWhiteTip = "Ein natürlicher Lebensraum"),
    UndercoverWordPair(civilianWord = "Gletscher", undercoverWord = "Eisberg", mrWhiteTip = "Ein riesiger Eisblock"),
    UndercoverWordPair(civilianWord = "Astronaut", undercoverWord = "Kosmonaut", mrWhiteTip = "Jemand, der ins Weltall reist"),
    UndercoverWordPair(civilianWord = "Teleskop", undercoverWord = "Mikroskop", mrWhiteTip = "Ein wissenschaftliches Gerät zum genauen Betrachten"),
    UndercoverWordPair(civilianWord = "Chemie", undercoverWord = "Physik", mrWhiteTip = "Ein naturwissenschaftliches Schulfach"),
    UndercoverWordPair(civilianWord = "Geschichte", undercoverWord = "Erdkunde", mrWhiteTip = "Ein Schulfach"),
    UndercoverWordPair(civilianWord = "Algebra", undercoverWord = "Geometrie", mrWhiteTip = "Ein Teilgebiet der Mathematik"),
    UndercoverWordPair(civilianWord = "Geige", undercoverWord = "Cello", mrWhiteTip = "Ein Streichinstrument, das mit einem Bogen gespielt wird"),
    UndercoverWordPair(civilianWord = "Trompete", undercoverWord = "Saxophon", mrWhiteTip = "Ein Blasinstrument"),
    UndercoverWordPair(civilianWord = "Schlagzeug", undercoverWord = "Bass", mrWhiteTip = "Ein Instrument, das den Rhythmus einer Band vorgibt"),
    UndercoverWordPair(civilianWord = "Oper", undercoverWord = "Musical", mrWhiteTip = "Eine Aufführung mit Gesang auf der Bühne"),
    UndercoverWordPair(civilianWord = "Zirkus", undercoverWord = "Jahrmarkt", mrWhiteTip = "Ein buntes Unterhaltungsevent"),
    UndercoverWordPair(civilianWord = "Zauberer", undercoverWord = "Clown", mrWhiteTip = "Ein Künstler, der ein Publikum unterhält"),
    UndercoverWordPair(civilianWord = "Zoo", undercoverWord = "Aquarium", mrWhiteTip = "Ein Ort, an dem man Tiere sehen kann"),
    UndercoverWordPair(civilianWord = "Freizeitpark", undercoverWord = "Wasserpark", mrWhiteTip = "Ein Ort mit Fahrgeschäften für einen Ausflug"),
    UndercoverWordPair(civilianWord = "Achterbahn", undercoverWord = "Riesenrad", mrWhiteTip = "Eine aufregende Fahrt im Freizeitpark"),
    UndercoverWordPair(civilianWord = "Fallschirmspringen", undercoverWord = "Bungee-Jumping", mrWhiteTip = "Eine extreme Abenteueraktivität"),
    UndercoverWordPair(civilianWord = "Schnorcheln", undercoverWord = "Tauchen", mrWhiteTip = "Eine Aktivität, um die Unterwasserwelt zu erkunden"),
    UndercoverWordPair(civilianWord = "Kajak", undercoverWord = "Kanu", mrWhiteTip = "Ein kleines Boot, das man selbst paddelt"),
    UndercoverWordPair(civilianWord = "Angelrute", undercoverWord = "Netz", mrWhiteTip = "Ein Werkzeug zum Fischfang"),
    UndercoverWordPair(civilianWord = "Traktor", undercoverWord = "Bulldozer", mrWhiteTip = "Ein schweres Arbeitsfahrzeug"),
    UndercoverWordPair(civilianWord = "Kran", undercoverWord = "Gabelstapler", mrWhiteTip = "Eine Maschine zum Heben schwerer Dinge"),
    UndercoverWordPair(civilianWord = "Wolkenkratzer", undercoverWord = "Hochhaus", mrWhiteTip = "Ein sehr hohes Gebäude"),
    UndercoverWordPair(civilianWord = "Cottage", undercoverWord = "Bungalow", mrWhiteTip = "Ein kleines gemütliches Haus"),
    UndercoverWordPair(civilianWord = "Villa", undercoverWord = "Herrenhaus", mrWhiteTip = "Ein großes luxuriöses Haus"),
    UndercoverWordPair(civilianWord = "Balkon", undercoverWord = "Terrasse", mrWhiteTip = "Ein Außenbereich an einem Haus"),
    UndercoverWordPair(civilianWord = "Garten", undercoverWord = "Hinterhof", mrWhiteTip = "Ein Außenbereich hinter einem Haus"),
    UndercoverWordPair(civilianWord = "Gewächshaus", undercoverWord = "Gärtnerei", mrWhiteTip = "Ein Ort, an dem Pflanzen gezogen werden"),
    UndercoverWordPair(civilianWord = "Bienenstock", undercoverWord = "Ameisenhaufen", mrWhiteTip = "Ein Zuhause, das von Insekten gebaut wird"),
    UndercoverWordPair(civilianWord = "Nest", undercoverWord = "Bau", mrWhiteTip = "Ein Zuhause, das von einem Tier gebaut wird"),
    UndercoverWordPair(civilianWord = "Kompass", undercoverWord = "GPS", mrWhiteTip = "Etwas zur Orientierung"),
    UndercoverWordPair(civilianWord = "Anker", undercoverWord = "Segel", mrWhiteTip = "Ein Teil eines Segelschiffs"),
    UndercoverWordPair(civilianWord = "Leuchtturm", undercoverWord = "Pier", mrWhiteTip = "Ein Bauwerk an der Küste"),
    UndercoverWordPair(civilianWord = "Hafen", undercoverWord = "Yachthafen", mrWhiteTip = "Ein Ort, an dem Boote anlegen"),
    UndercoverWordPair(civilianWord = "Schnecke", undercoverWord = "Nacktschnecke", mrWhiteTip = "Ein langsames kriechendes Tier"),
    UndercoverWordPair(civilianWord = "Igel", undercoverWord = "Stachelschwein", mrWhiteTip = "Ein kleines stacheliges Tier"),
    UndercoverWordPair(civilianWord = "Eichhörnchen", undercoverWord = "Streifenhörnchen", mrWhiteTip = "Ein kleines Tier, das Nüsse sammelt"),
    UndercoverWordPair(civilianWord = "Eule", undercoverWord = "Falke", mrWhiteTip = "Ein Vogel mit scharfen Augen"),
    UndercoverWordPair(civilianWord = "Pfau", undercoverWord = "Flamingo", mrWhiteTip = "Ein Vogel mit buntem Gefieder"),
    UndercoverWordPair(civilianWord = "Gepard", undercoverWord = "Leopard", mrWhiteTip = "Eine schnelle Raubkatze mit Flecken"),
    UndercoverWordPair(civilianWord = "Koffer", undercoverWord = "Reisetasche", mrWhiteTip = "Etwas, um Gepäck zu tragen"),
    UndercoverWordPair(civilianWord = "Sonnencreme", undercoverWord = "Sonnenhut", mrWhiteTip = "Etwas, das dich vor der Sonne schützt"),
)

/**
 * Returns the appropriate word list based on the current language setting
 */
fun getUndercoverWordPairs(languageSetting: LanguageSetting): List<UndercoverWordPair> {
    return when (languageSetting) {
        LanguageSetting.ENGLISH, LanguageSetting.ITALIAN -> UNDERCOVER_WORD_PAIRS_EN
        LanguageSetting.GERMAN, LanguageSetting.VORI -> UNDERCOVER_WORD_PAIRS_DE
        LanguageSetting.SYSTEM -> {
            val languageService = KoinPlatform.getKoin().get<LanguageService>()
            // getSystemLanguageSetting() falls back to SYSTEM itself for an unmapped device
            // locale (e.g. French), so default to English instead of recursing back into
            // this same branch and overflowing the stack.
            when (val systemLanguage = languageService.getSystemLanguageSetting()) {
                LanguageSetting.SYSTEM -> UNDERCOVER_WORD_PAIRS_EN
                else -> getUndercoverWordPairs(systemLanguage)
            }
        }
    }
}