package org.lerchenflo.schneaggchatv3mp.games.presentation.crossword

/**
 * Word/clue pool for the locally generated German crosswords.
 * Words are A-Z only (crossword convention: Ä→AE, Ö→OE, Ü→UE, ß→SS);
 * clues keep normal German spelling. Content lives in code like the other
 * game word lists (Morse, Undercover) — not in string resources.
 */
data class GermanCrosswordEntry(
    val word: String,
    val clue: String,
)

val germanCrosswordWords: List<GermanCrosswordEntry> = listOf(
    GermanCrosswordEntry("DONAU", "Fluss durch Wien"),
    GermanCrosswordEntry("RHEIN", "Fluss durch Köln"),
    GermanCrosswordEntry("ALPEN", "Höchstes Gebirge Europas"),
    GermanCrosswordEntry("BERLIN", "Hauptstadt Deutschlands"),
    GermanCrosswordEntry("WIEN", "Hauptstadt Österreichs"),
    GermanCrosswordEntry("BERN", "Hauptstadt der Schweiz"),
    GermanCrosswordEntry("ROM", "Hauptstadt Italiens"),
    GermanCrosswordEntry("PARIS", "Stadt an der Seine"),
    GermanCrosswordEntry("TIROL", "Bundesland mit Innsbruck"),
    GermanCrosswordEntry("BREGENZ", "Hauptstadt Vorarlbergs"),
    GermanCrosswordEntry("BODENSEE", "See zwischen drei Ländern"),
    GermanCrosswordEntry("EUROPA", "Kontinent mit Deutschland"),
    GermanCrosswordEntry("AFRIKA", "Kontinent mit der Sahara"),
    GermanCrosswordEntry("ASIEN", "Größter Kontinent"),
    GermanCrosswordEntry("NIL", "Längster Fluss Afrikas"),
    GermanCrosswordEntry("SAHARA", "Größte Wüste der Erde"),
    GermanCrosswordEntry("INSEL", "Land, das von Wasser umgeben ist"),
    GermanCrosswordEntry("VULKAN", "Feuerspeiender Berg"),
    GermanCrosswordEntry("GLETSCHER", "Ewiges Eis im Gebirge"),
    GermanCrosswordEntry("WUESTE", "Sehr trockene Landschaft"),
    GermanCrosswordEntry("OZEAN", "Weltmeer"),
    GermanCrosswordEntry("EBBE", "Niedrigwasser am Meer"),
    GermanCrosswordEntry("FLUT", "Hochwasser am Meer"),
    GermanCrosswordEntry("HAFEN", "Anlegestelle für Schiffe"),
    GermanCrosswordEntry("ANKER", "Hält das Schiff an Ort und Stelle"),
    GermanCrosswordEntry("SEGEL", "Windfänger am Boot"),
    GermanCrosswordEntry("KOMPASS", "Zeigt immer nach Norden"),
    GermanCrosswordEntry("NORDEN", "Himmelsrichtung mit Polarstern"),
    GermanCrosswordEntry("SUEDEN", "Himmelsrichtung Richtung Mittag"),
    GermanCrosswordEntry("OSTEN", "Himmelsrichtung des Sonnenaufgangs"),
    GermanCrosswordEntry("WESTEN", "Himmelsrichtung des Sonnenuntergangs"),
    GermanCrosswordEntry("SONNE", "Stern im Zentrum unseres Systems"),
    GermanCrosswordEntry("MOND", "Erdtrabant"),
    GermanCrosswordEntry("STERN", "Leuchtet am Nachthimmel"),
    GermanCrosswordEntry("PLANET", "Erde, Mars oder Venus"),
    GermanCrosswordEntry("MARS", "Roter Planet"),
    GermanCrosswordEntry("VENUS", "Planet und römische Liebesgöttin"),
    GermanCrosswordEntry("KOMET", "Schweifstern"),
    GermanCrosswordEntry("RAKETE", "Fahrzeug für den Weltraum"),
    GermanCrosswordEntry("WOLKE", "Schwebt am Himmel und bringt Regen"),
    GermanCrosswordEntry("REGEN", "Wasser vom Himmel"),
    GermanCrosswordEntry("SCHNEE", "Weiße Winterpracht"),
    GermanCrosswordEntry("NEBEL", "Trübt die Sicht am Morgen"),
    GermanCrosswordEntry("BLITZ", "Grelles Leuchten beim Gewitter"),
    GermanCrosswordEntry("DONNER", "Grollen nach dem Blitz"),
    GermanCrosswordEntry("STURM", "Sehr starker Wind"),
    GermanCrosswordEntry("FROST", "Temperatur unter null Grad"),
    GermanCrosswordEntry("SOMMER", "Wärmste Jahreszeit"),
    GermanCrosswordEntry("WINTER", "Kälteste Jahreszeit"),
    GermanCrosswordEntry("HERBST", "Jahreszeit des Laubfalls"),
    GermanCrosswordEntry("APRIL", "Monat, der macht, was er will"),
    GermanCrosswordEntry("MONTAG", "Erster Tag der Arbeitswoche"),
    GermanCrosswordEntry("FREITAG", "Letzter Arbeitstag vor dem Wochenende"),
    GermanCrosswordEntry("ADLER", "Wappenvogel vieler Länder"),
    GermanCrosswordEntry("AMSEL", "Schwarzer Singvogel"),
    GermanCrosswordEntry("EULE", "Nachtaktiver Vogel"),
    GermanCrosswordEntry("PINGUIN", "Frackträger der Antarktis"),
    GermanCrosswordEntry("DELFIN", "Kluger Meeressäuger"),
    GermanCrosswordEntry("WAL", "Größtes Tier der Erde"),
    GermanCrosswordEntry("HAI", "Gefürchteter Meeresräuber"),
    GermanCrosswordEntry("FORELLE", "Fisch aus Schuberts Quintett"),
    GermanCrosswordEntry("BIENE", "Fleißige Honigmacherin"),
    GermanCrosswordEntry("AMEISE", "Fleißiges Krabbeltier im Staat"),
    GermanCrosswordEntry("SPINNE", "Achtbeiniger Netzbauer"),
    GermanCrosswordEntry("IGEL", "Stacheliger Gartenbewohner"),
    GermanCrosswordEntry("FUCHS", "Schlauer Waldbewohner"),
    GermanCrosswordEntry("WOLF", "Wilder Verwandter des Hundes"),
    GermanCrosswordEntry("BAER", "Meister Petz"),
    GermanCrosswordEntry("HIRSCH", "Waldtier mit Geweih"),
    GermanCrosswordEntry("REH", "Scheues Waldtier"),
    GermanCrosswordEntry("HASE", "Langohr auf dem Feld"),
    GermanCrosswordEntry("PFERD", "Reittier mit Mähne"),
    GermanCrosswordEntry("ESEL", "Grautier mit langen Ohren"),
    GermanCrosswordEntry("ZIEGE", "Meckerndes Haustier"),
    GermanCrosswordEntry("SCHAF", "Liefert Wolle"),
    GermanCrosswordEntry("KUH", "Gibt Milch"),
    GermanCrosswordEntry("KAMEL", "Wüstenschiff"),
    GermanCrosswordEntry("LOEWE", "König der Tiere"),
    GermanCrosswordEntry("TIGER", "Gestreifte Raubkatze"),
    GermanCrosswordEntry("ZEBRA", "Gestreiftes Steppentier"),
    GermanCrosswordEntry("GIRAFFE", "Tier mit dem längsten Hals"),
    GermanCrosswordEntry("ELEFANT", "Dickhäuter mit Rüssel"),
    GermanCrosswordEntry("AFFE", "Kletterkünstler im Dschungel"),
    GermanCrosswordEntry("SCHLANGE", "Kriechtier ohne Beine"),
    GermanCrosswordEntry("EIDECHSE", "Flinkes Reptil auf sonnigen Steinen"),
    GermanCrosswordEntry("FROSCH", "Quakender Teichbewohner"),
    GermanCrosswordEntry("EICHE", "Baum mit Eicheln"),
    GermanCrosswordEntry("BIRKE", "Baum mit weißer Rinde"),
    GermanCrosswordEntry("TANNE", "Beliebter Weihnachtsbaum"),
    GermanCrosswordEntry("AHORN", "Baum im kanadischen Wappen"),
    GermanCrosswordEntry("LINDE", "Baum vieler Dorfplätze"),
    GermanCrosswordEntry("ROSE", "Blume mit Dornen"),
    GermanCrosswordEntry("TULPE", "Blume aus Holland"),
    GermanCrosswordEntry("NELKE", "Blume und Gewürz"),
    GermanCrosswordEntry("VEILCHEN", "Blaue Frühlingsblume"),
    GermanCrosswordEntry("KLEE", "Glücksbringer mit vier Blättern"),
    GermanCrosswordEntry("MOOS", "Weicher grüner Waldteppich"),
    GermanCrosswordEntry("PILZ", "Wächst nach dem Regen im Wald"),
    GermanCrosswordEntry("APFEL", "Frucht vom Baum der Erkenntnis"),
    GermanCrosswordEntry("BIRNE", "Frucht und Glühlampe"),
    GermanCrosswordEntry("KIRSCHE", "Kleine rote Steinfrucht"),
    GermanCrosswordEntry("TRAUBE", "Frucht für den Wein"),
    GermanCrosswordEntry("ZITRONE", "Saure gelbe Frucht"),
    GermanCrosswordEntry("ORANGE", "Apfelsine"),
    GermanCrosswordEntry("BANANE", "Krumme gelbe Frucht"),
    GermanCrosswordEntry("ANANAS", "Tropenfrucht mit Blätterkrone"),
    GermanCrosswordEntry("MELONE", "Große Sommerfrucht und Hutform"),
    GermanCrosswordEntry("ERDBEERE", "Rote Frucht mit Kernen außen"),
    GermanCrosswordEntry("GURKE", "Grünes Salatgemüse"),
    GermanCrosswordEntry("TOMATE", "Rotes Salatgemüse"),
    GermanCrosswordEntry("KAROTTE", "Lieblingsgemüse der Hasen"),
    GermanCrosswordEntry("ZWIEBEL", "Gemüse, das zum Weinen bringt"),
    GermanCrosswordEntry("KARTOFFEL", "Erdapfel"),
    GermanCrosswordEntry("SALAT", "Grünes Blattgemüse"),
    GermanCrosswordEntry("HONIG", "Süßes Bienenprodukt"),
    GermanCrosswordEntry("ZUCKER", "Süßungsmittel"),
    GermanCrosswordEntry("SALZ", "Weißes Gold der Küche"),
    GermanCrosswordEntry("PFEFFER", "Scharfes schwarzes Gewürz"),
    GermanCrosswordEntry("SENF", "Gelbe Würzpaste"),
    GermanCrosswordEntry("BUTTER", "Streichfett aus Milch"),
    GermanCrosswordEntry("KAESE", "Reift mit Löchern im Laib"),
    GermanCrosswordEntry("BROT", "Grundnahrungsmittel vom Bäcker"),
    GermanCrosswordEntry("KUCHEN", "Süßes Gebäck zum Kaffee"),
    GermanCrosswordEntry("TORTE", "Festliches Schichtgebäck"),
    GermanCrosswordEntry("NUDEL", "Teigware"),
    GermanCrosswordEntry("REIS", "Grundnahrungsmittel Asiens"),
    GermanCrosswordEntry("SUPPE", "Flüssige Vorspeise"),
    GermanCrosswordEntry("KAFFEE", "Schwarzes Wachmacher-Getränk"),
    GermanCrosswordEntry("TEE", "Aufgussgetränk"),
    GermanCrosswordEntry("SAFT", "Gepresstes Fruchtgetränk"),
    GermanCrosswordEntry("WEIN", "Getränk aus Trauben"),
    GermanCrosswordEntry("BIER", "Getränk aus Hopfen und Malz"),
    GermanCrosswordEntry("MILCH", "Weißes Getränk von der Kuh"),
    GermanCrosswordEntry("WASSER", "H2O"),
    GermanCrosswordEntry("GEIGE", "Streichinstrument"),
    GermanCrosswordEntry("KLAVIER", "Tasteninstrument"),
    GermanCrosswordEntry("TROMPETE", "Blechblasinstrument"),
    GermanCrosswordEntry("FLOETE", "Holzblasinstrument"),
    GermanCrosswordEntry("HARFE", "Zupfinstrument mit vielen Saiten"),
    GermanCrosswordEntry("TROMMEL", "Schlaginstrument"),
    GermanCrosswordEntry("OPER", "Musiktheater"),
    GermanCrosswordEntry("CHOR", "Singende Gemeinschaft"),
    GermanCrosswordEntry("MOZART", "Komponist der Zauberflöte"),
    GermanCrosswordEntry("GOETHE", "Dichter des Faust"),
    GermanCrosswordEntry("SCHILLER", "Dichter der Räuber"),
    GermanCrosswordEntry("MUSEUM", "Haus für Kunst und Geschichte"),
    GermanCrosswordEntry("THEATER", "Haus der Schauspielkunst"),
    GermanCrosswordEntry("KINO", "Haus der bewegten Bilder"),
    GermanCrosswordEntry("BUCH", "Gedrucktes Lesewerk"),
    GermanCrosswordEntry("ROMAN", "Langes Erzählwerk"),
    GermanCrosswordEntry("MAERCHEN", "Es war einmal..."),
    GermanCrosswordEntry("RAETSEL", "Knifflige Denkaufgabe"),
    GermanCrosswordEntry("SCHACH", "Königliches Brettspiel"),
    GermanCrosswordEntry("DAME", "Brettspiel und Spielkarte"),
    GermanCrosswordEntry("WUERFEL", "Sechsseitiger Spielstein"),
    GermanCrosswordEntry("TENNIS", "Sport mit Schläger und Filzball"),
    GermanCrosswordEntry("FUSSBALL", "Beliebtester Sport der Welt"),
    GermanCrosswordEntry("TOR", "Ziel beim Fußball"),
    GermanCrosswordEntry("SKI", "Bretter für den Schnee"),
    GermanCrosswordEntry("RODEL", "Schlitten"),
    GermanCrosswordEntry("MARATHON", "Lauf über 42 Kilometer"),
    GermanCrosswordEntry("STADION", "Große Sportarena"),
    GermanCrosswordEntry("MEDAILLE", "Auszeichnung für Sieger"),
    GermanCrosswordEntry("ARZT", "Doktor im Krankenhaus"),
    GermanCrosswordEntry("LEHRER", "Unterrichtet in der Schule"),
    GermanCrosswordEntry("BAECKER", "Backt Brot und Semmeln"),
    GermanCrosswordEntry("KOCH", "Meister in der Küche"),
    GermanCrosswordEntry("PILOT", "Steuert das Flugzeug"),
    GermanCrosswordEntry("RICHTER", "Spricht Recht im Gericht"),
    GermanCrosswordEntry("CLOWN", "Spaßmacher im Zirkus"),
    GermanCrosswordEntry("SCHULE", "Ort des Lernens"),
    GermanCrosswordEntry("TAFEL", "Schreibfläche im Klassenzimmer"),
    GermanCrosswordEntry("KREIDE", "Schreibstift für die Tafel"),
    GermanCrosswordEntry("HEFT", "Schreibblock für die Schule"),
    GermanCrosswordEntry("FERIEN", "Schulfreie Zeit"),
    GermanCrosswordEntry("ZEUGNIS", "Notenblatt am Schuljahresende"),
    GermanCrosswordEntry("FENSTER", "Glasöffnung in der Wand"),
    GermanCrosswordEntry("TUER", "Eingang zum Zimmer"),
    GermanCrosswordEntry("DACH", "Oberster Abschluss des Hauses"),
    GermanCrosswordEntry("KELLER", "Raum unter dem Haus"),
    GermanCrosswordEntry("KAMIN", "Offene Feuerstelle im Haus"),
    GermanCrosswordEntry("TREPPE", "Verbindet Stockwerke"),
    GermanCrosswordEntry("GARTEN", "Grünes Reich hinter dem Haus"),
    GermanCrosswordEntry("ZAUN", "Grenze um den Garten"),
    GermanCrosswordEntry("BRUNNEN", "Wasserquelle auf dem Dorfplatz"),
    GermanCrosswordEntry("KERZE", "Spendet Licht mit Docht und Wachs"),
    GermanCrosswordEntry("LAMPE", "Elektrische Lichtquelle"),
    GermanCrosswordEntry("SPIEGEL", "Zeigt das eigene Bild"),
    GermanCrosswordEntry("TEPPICH", "Weicher Bodenbelag"),
    GermanCrosswordEntry("SOFA", "Bequemes Sitzmöbel"),
    GermanCrosswordEntry("REGAL", "Möbel für Bücher"),
    GermanCrosswordEntry("SCHRANK", "Möbel für Kleidung"),
    GermanCrosswordEntry("KISSEN", "Weiche Kopfunterlage"),
    GermanCrosswordEntry("DECKE", "Wärmt im Bett"),
    GermanCrosswordEntry("WECKER", "Klingelt am Morgen"),
    GermanCrosswordEntry("SCHERE", "Werkzeug zum Schneiden"),
    GermanCrosswordEntry("HAMMER", "Werkzeug zum Nageln"),
    GermanCrosswordEntry("SAEGE", "Werkzeug mit Zähnen"),
    GermanCrosswordEntry("NAGEL", "Wird in die Wand geschlagen"),
    GermanCrosswordEntry("LEITER", "Hilft beim Hochklettern"),
    GermanCrosswordEntry("EIMER", "Gefäß mit Henkel"),
    GermanCrosswordEntry("BESEN", "Kehrgerät"),
    GermanCrosswordEntry("SEIFE", "Schäumt beim Händewaschen"),
    GermanCrosswordEntry("KAMM", "Ordnet die Haare"),
    GermanCrosswordEntry("BRILLE", "Sehhilfe auf der Nase"),
    GermanCrosswordEntry("HUT", "Kopfbedeckung"),
    GermanCrosswordEntry("SCHAL", "Wärmt den Hals"),
    GermanCrosswordEntry("MANTEL", "Langes Kleidungsstück für kalte Tage"),
    GermanCrosswordEntry("STIEFEL", "Hoher Schuh"),
    GermanCrosswordEntry("KNOPF", "Verschluss am Hemd"),
    GermanCrosswordEntry("TASCHE", "Behältnis zum Tragen"),
    GermanCrosswordEntry("KOFFER", "Reisegepäck"),
    GermanCrosswordEntry("ZUG", "Fährt auf Schienen"),
    GermanCrosswordEntry("GLEIS", "Schienenweg am Bahnhof"),
    GermanCrosswordEntry("AMPEL", "Regelt den Verkehr mit drei Farben"),
    GermanCrosswordEntry("REIFEN", "Rundes Gummiteil am Auto"),
    GermanCrosswordEntry("MOTOR", "Antrieb des Autos"),
    GermanCrosswordEntry("TANKEN", "Kraftstoff nachfüllen"),
    GermanCrosswordEntry("FAEHRE", "Schiff für die Überfahrt"),
    GermanCrosswordEntry("BRUECKE", "Führt über den Fluss"),
    GermanCrosswordEntry("TUNNEL", "Weg durch den Berg"),
    GermanCrosswordEntry("STRASSE", "Weg für Autos"),
    GermanCrosswordEntry("PLATZ", "Freie Fläche in der Stadt"),
    GermanCrosswordEntry("TURM", "Hohes schmales Bauwerk"),
    GermanCrosswordEntry("BURG", "Mittelalterliche Festung"),
    GermanCrosswordEntry("SCHLOSS", "Prunkbau und Türverriegelung"),
    GermanCrosswordEntry("KIRCHE", "Gotteshaus mit Glockenturm"),
    GermanCrosswordEntry("GLOCKE", "Läutet im Kirchturm"),
    GermanCrosswordEntry("KOENIG", "Herrscher mit Krone"),
    GermanCrosswordEntry("KRONE", "Kopfschmuck des Königs"),
    GermanCrosswordEntry("RITTER", "Kämpfer in Rüstung"),
    GermanCrosswordEntry("DRACHE", "Feuerspeiendes Fabelwesen"),
    GermanCrosswordEntry("ZWERG", "Kleiner Märchengeselle"),
    GermanCrosswordEntry("RIESE", "Großer Märchengeselle"),
    GermanCrosswordEntry("HEXE", "Reitet auf dem Besen"),
    GermanCrosswordEntry("ZAUBER", "Magisches Kunststück"),
    GermanCrosswordEntry("SCHATZ", "Vergrabene Kostbarkeit"),
    GermanCrosswordEntry("GOLD", "Edles gelbes Metall"),
    GermanCrosswordEntry("SILBER", "Edles weißes Metall"),
    GermanCrosswordEntry("EISEN", "Metall für Stahl"),
    GermanCrosswordEntry("DIAMANT", "Härtester Edelstein"),
    GermanCrosswordEntry("PERLE", "Schmuck aus der Muschel"),
    GermanCrosswordEntry("RING", "Schmuck am Finger"),
    GermanCrosswordEntry("KETTE", "Schmuck um den Hals"),
    GermanCrosswordEntry("UHR", "Zeigt die Zeit"),
    GermanCrosswordEntry("SEKUNDE", "Kürzeste gängige Zeiteinheit"),
    GermanCrosswordEntry("STUNDE", "Sechzig Minuten"),
    GermanCrosswordEntry("JAHR", "Zwölf Monate"),
    GermanCrosswordEntry("ZAHL", "Mathematisches Zeichen"),
    GermanCrosswordEntry("NULL", "Zahl ohne Wert"),
    GermanCrosswordEntry("DUTZEND", "Zwölf Stück"),
    GermanCrosswordEntry("KREIS", "Runde geometrische Form"),
    GermanCrosswordEntry("DREIECK", "Form mit drei Ecken"),
    GermanCrosswordEntry("QUADRAT", "Form mit vier gleichen Seiten"),
    GermanCrosswordEntry("LINEAL", "Hilfsmittel für gerade Linien"),
    GermanCrosswordEntry("ZIRKEL", "Zeichengerät für Kreise"),
    GermanCrosswordEntry("ATOM", "Kleinster Baustein der Elemente"),
    GermanCrosswordEntry("ENERGIE", "Kraft zum Arbeiten"),
    GermanCrosswordEntry("STROM", "Elektrizität oder großer Fluss"),
    GermanCrosswordEntry("MAGNET", "Zieht Eisen an"),
    GermanCrosswordEntry("LUPE", "Vergrößerungsglas"),
    GermanCrosswordEntry("MIKROSKOP", "Gerät für winzig Kleines"),
    GermanCrosswordEntry("TELESKOP", "Gerät für den Sternenhimmel"),
    GermanCrosswordEntry("ROBOTER", "Maschinenmensch"),
    GermanCrosswordEntry("COMPUTER", "Elektronischer Rechner"),
    GermanCrosswordEntry("TASTATUR", "Eingabegerät mit Tasten"),
    GermanCrosswordEntry("BILDSCHIRM", "Anzeigefläche des Computers"),
    GermanCrosswordEntry("INTERNET", "Weltweites Datennetz"),
    GermanCrosswordEntry("EMAIL", "Elektronische Post"),
    GermanCrosswordEntry("HANDY", "Mobiltelefon"),
    GermanCrosswordEntry("AKKU", "Wiederaufladbare Batterie"),
    GermanCrosswordEntry("FOTO", "Aufnahme mit der Kamera"),
    GermanCrosswordEntry("RADIO", "Gerät für Hörfunk"),
    GermanCrosswordEntry("ANTENNE", "Empfängt Funkwellen"),
    GermanCrosswordEntry("ZEITUNG", "Tägliches Nachrichtenblatt"),
    GermanCrosswordEntry("BRIEF", "Post im Umschlag"),
    GermanCrosswordEntry("MARKE", "Klebt auf dem Briefumschlag"),
    GermanCrosswordEntry("STEMPEL", "Drückt Tinte aufs Papier"),
    GermanCrosswordEntry("TINTE", "Flüssigkeit im Füller"),
    GermanCrosswordEntry("PAPIER", "Beschreibbarer Bogen"),
    GermanCrosswordEntry("FEDER", "Historisches Schreibgerät vom Vogel"),
    GermanCrosswordEntry("PINSEL", "Werkzeug des Malers"),
    GermanCrosswordEntry("FARBE", "Rot, Gelb oder Blau"),
    GermanCrosswordEntry("BILD", "Hängt gerahmt an der Wand"),
    GermanCrosswordEntry("RAHMEN", "Fasst das Bild ein"),
    GermanCrosswordEntry("SCHATTEN", "Dunkler Begleiter bei Sonne"),
    GermanCrosswordEntry("ECHO", "Widerhall im Gebirge"),
    GermanCrosswordEntry("TRAUM", "Nächtliches Kopfkino"),
    GermanCrosswordEntry("GLUECK", "Gegenteil von Pech"),
    GermanCrosswordEntry("MUT", "Tapferkeit"),
    GermanCrosswordEntry("RUHE", "Stille und Frieden"),
    GermanCrosswordEntry("LAERM", "Störender Krach"),
    GermanCrosswordEntry("DUFT", "Angenehmer Geruch"),
    GermanCrosswordEntry("GERUCH", "Wahrnehmung der Nase"),
    GermanCrosswordEntry("STIMME", "Klang beim Sprechen"),
    GermanCrosswordEntry("SPRACHE", "Deutsch oder Italienisch"),
    GermanCrosswordEntry("WORT", "Baustein des Satzes"),
    GermanCrosswordEntry("SILBE", "Teil eines Wortes"),
    GermanCrosswordEntry("FRAGE", "Satz mit Fragezeichen"),
    GermanCrosswordEntry("ANTWORT", "Erwiderung auf eine Frage"),
    GermanCrosswordEntry("LONDON", "Hauptstadt Englands"),
    GermanCrosswordEntry("MADRID", "Hauptstadt Spaniens"),
    GermanCrosswordEntry("ATHEN", "Hauptstadt Griechenlands"),
    GermanCrosswordEntry("PRAG", "Hauptstadt Tschechiens"),
    GermanCrosswordEntry("OSLO", "Hauptstadt Norwegens"),
    GermanCrosswordEntry("DUBLIN", "Hauptstadt Irlands"),
    GermanCrosswordEntry("BUDAPEST", "Hauptstadt Ungarns"),
    GermanCrosswordEntry("LISSABON", "Hauptstadt Portugals"),
    GermanCrosswordEntry("MOSKAU", "Hauptstadt Russlands"),
    GermanCrosswordEntry("TOKIO", "Hauptstadt Japans"),
    GermanCrosswordEntry("KAIRO", "Hauptstadt Ägyptens"),
    GermanCrosswordEntry("PEKING", "Hauptstadt Chinas"),
    GermanCrosswordEntry("ANKARA", "Hauptstadt der Türkei"),
    GermanCrosswordEntry("BRUESSEL", "Hauptstadt Belgiens"),
    GermanCrosswordEntry("ZUERICH", "Größte Stadt der Schweiz"),
    GermanCrosswordEntry("MUENCHEN", "Bayerische Landeshauptstadt"),
    GermanCrosswordEntry("HAMBURG", "Deutsche Stadt mit großem Hafen"),
    GermanCrosswordEntry("KOELN", "Stadt mit berühmtem Dom am Rhein"),
    GermanCrosswordEntry("DRESDEN", "Hauptstadt Sachsens"),
    GermanCrosswordEntry("SALZBURG", "Geburtsstadt Mozarts"),
    GermanCrosswordEntry("INNSBRUCK", "Hauptstadt Tirols"),
    GermanCrosswordEntry("GRAZ", "Zweitgrößte Stadt Österreichs"),
    GermanCrosswordEntry("LINZ", "Stadt an der Donau in Oberösterreich"),
    GermanCrosswordEntry("VENEDIG", "Italienische Stadt mit Kanälen"),
    GermanCrosswordEntry("MAILAND", "Italienische Modestadt"),
    GermanCrosswordEntry("NEAPEL", "Italienische Stadt am Vesuv"),
    GermanCrosswordEntry("FLORENZ", "Stadt der Uffizien"),
    GermanCrosswordEntry("SIZILIEN", "Größte Insel im Mittelmeer"),
    GermanCrosswordEntry("SARDINIEN", "Italienische Mittelmeerinsel"),
    GermanCrosswordEntry("KRETA", "Größte griechische Insel"),
    GermanCrosswordEntry("MALLORCA", "Beliebte Baleareninsel"),
    GermanCrosswordEntry("ISLAND", "Inselstaat im Nordatlantik"),
    GermanCrosswordEntry("IRLAND", "Grüne Insel im Westen Europas"),
    GermanCrosswordEntry("SPANIEN", "Land des Flamenco"),
    GermanCrosswordEntry("NORWEGEN", "Land der Fjorde"),
    GermanCrosswordEntry("SCHWEDEN", "Land mit der Hauptstadt Stockholm"),
    GermanCrosswordEntry("FINNLAND", "Land der tausend Seen"),
    GermanCrosswordEntry("POLEN", "Nachbarland im Osten Deutschlands"),
    GermanCrosswordEntry("UNGARN", "Land mit der Hauptstadt Budapest"),
    GermanCrosswordEntry("TUERKEI", "Land zwischen Europa und Asien"),
    GermanCrosswordEntry("JAPAN", "Land der aufgehenden Sonne"),
    GermanCrosswordEntry("CHINA", "Land der Großen Mauer"),
    GermanCrosswordEntry("INDIEN", "Land des Taj Mahal"),
    GermanCrosswordEntry("KANADA", "Land mit dem Ahornblatt"),
    GermanCrosswordEntry("MEXIKO", "Land der Sombreros"),
    GermanCrosswordEntry("AEGYPTEN", "Land der Pyramiden"),
    GermanCrosswordEntry("KENIA", "Land der Safaris in Ostafrika"),
    GermanCrosswordEntry("AMERIKA", "Kontinent mit Nord und Süd"),
    GermanCrosswordEntry("ANTARKTIS", "Kalter Kontinent am Südpol"),
    GermanCrosswordEntry("ATLANTIK", "Ozean zwischen Europa und Amerika"),
    GermanCrosswordEntry("PAZIFIK", "Größter Ozean der Erde"),
    GermanCrosswordEntry("NORDSEE", "Meer vor Hamburg"),
    GermanCrosswordEntry("OSTSEE", "Meer zwischen Deutschland und Schweden"),
    GermanCrosswordEntry("ELBE", "Fluss durch Hamburg"),
    GermanCrosswordEntry("SEINE", "Fluss durch Paris"),
    GermanCrosswordEntry("THEMSE", "Fluss durch London"),
    GermanCrosswordEntry("AMAZONAS", "Fluss durch den Regenwald"),
    GermanCrosswordEntry("WOLGA", "Längster Fluss Europas"),
    GermanCrosswordEntry("MAIN", "Fluss durch Frankfurt"),
    GermanCrosswordEntry("ISAR", "Fluss durch München"),
    GermanCrosswordEntry("INN", "Fluss durch Innsbruck"),
    GermanCrosswordEntry("ILL", "Fluss durch Vorarlberg"),
    GermanCrosswordEntry("ARLBERG", "Pass zwischen Tirol und Vorarlberg"),
    GermanCrosswordEntry("MATTERHORN", "Berühmter Berg der Schweiz"),
    GermanCrosswordEntry("EVEREST", "Höchster Berg der Erde"),
    GermanCrosswordEntry("ETNA", "Vulkan auf Sizilien"),
    GermanCrosswordEntry("FJORD", "Schmale Meeresbucht in Norwegen"),
    GermanCrosswordEntry("KANAL", "Künstlicher Wasserweg"),
    GermanCrosswordEntry("KUESTE", "Wo Land auf Meer trifft"),
    GermanCrosswordEntry("STRAND", "Sandiger Uferstreifen"),
    GermanCrosswordEntry("DUENE", "Sandhügel am Meer"),
    GermanCrosswordEntry("KLIPPE", "Steile Felswand am Meer"),
    GermanCrosswordEntry("LEUCHTTURM", "Warnt Schiffe vor der Küste"),
    GermanCrosswordEntry("HUEGEL", "Kleine Erhebung im Gelände"),
    GermanCrosswordEntry("TAL", "Senke zwischen zwei Bergen"),
    GermanCrosswordEntry("GIPFEL", "Höchster Punkt eines Berges"),
    GermanCrosswordEntry("HOEHLE", "Hohlraum im Berg"),
    GermanCrosswordEntry("QUELLE", "Ursprung eines Baches"),
    GermanCrosswordEntry("BACH", "Kleines Fließgewässer"),
    GermanCrosswordEntry("SEE", "Stehendes Binnengewässer"),
    GermanCrosswordEntry("TEICH", "Kleines stehendes Gewässer"),
    GermanCrosswordEntry("SUMPF", "Nasser, weicher Boden"),
    GermanCrosswordEntry("MOOR", "Feuchtes Torfgebiet"),
    GermanCrosswordEntry("WALD", "Viele Bäume beisammen"),
    GermanCrosswordEntry("WIESE", "Grüne Fläche mit Gras"),
    GermanCrosswordEntry("FELD", "Bestellte Ackerfläche"),
    GermanCrosswordEntry("ACKER", "Bearbeiteter Boden des Bauern"),
    GermanCrosswordEntry("ERDE", "Unser Planet"),
    GermanCrosswordEntry("NORDPOL", "Nördlichster Punkt der Erde"),
    GermanCrosswordEntry("AEQUATOR", "Gedachte Linie um die Erdmitte"),
    GermanCrosswordEntry("ATLAS", "Buch mit Landkarten"),
    GermanCrosswordEntry("GLOBUS", "Kugelförmiges Erdmodell"),
    GermanCrosswordEntry("KARTE", "Zeigt Wege und Orte"),
    GermanCrosswordEntry("GRENZE", "Trennt zwei Länder"),
    GermanCrosswordEntry("LUCHS", "Wildkatze mit Pinselohren"),
    GermanCrosswordEntry("DACHS", "Nachtaktiver Waldbewohner mit Streifen"),
    GermanCrosswordEntry("MARDER", "Tier, das gern Kabel anknabbert"),
    GermanCrosswordEntry("BIBER", "Nagetier, das Dämme baut"),
    GermanCrosswordEntry("OTTER", "Schwimmendes Raubtier am Fluss"),
    GermanCrosswordEntry("MAUS", "Kleines Nagetier mit langem Schwanz"),
    GermanCrosswordEntry("RATTE", "Nagetier in der Kanalisation"),
    GermanCrosswordEntry("HAMSTER", "Nagetier mit Backentaschen"),
    GermanCrosswordEntry("KANINCHEN", "Verwandter des Hasen"),
    GermanCrosswordEntry("MAULWURF", "Gräbt Gänge im Garten"),
    GermanCrosswordEntry("FLEDERMAUS", "Fliegt nachts und hängt kopfüber"),
    GermanCrosswordEntry("STORCH", "Langbeiniger Vogel im Nest auf dem Dach"),
    GermanCrosswordEntry("SPATZ", "Kleiner grauer Stadtvogel"),
    GermanCrosswordEntry("RABE", "Schwarzer kluger Vogel"),
    GermanCrosswordEntry("MOEWE", "Vogel an der Küste"),
    GermanCrosswordEntry("SCHWAN", "Weißer Vogel auf dem See"),
    GermanCrosswordEntry("ENTE", "Wasservogel mit breitem Schnabel"),
    GermanCrosswordEntry("GANS", "Größer als die Ente"),
    GermanCrosswordEntry("HUHN", "Legt Eier im Stall"),
    GermanCrosswordEntry("HAHN", "Kräht am Morgen"),
    GermanCrosswordEntry("TAUBE", "Symbol des Friedens"),
    GermanCrosswordEntry("FALKE", "Schneller Greifvogel"),
    GermanCrosswordEntry("GEIER", "Aasfresser mit kahlem Hals"),
    GermanCrosswordEntry("PAPAGEI", "Bunter Vogel, der sprechen kann"),
    GermanCrosswordEntry("SPECHT", "Klopft an den Baumstamm"),
    GermanCrosswordEntry("KUCKUCK", "Vogel, der fremde Nester nutzt"),
    GermanCrosswordEntry("MEISE", "Kleiner Gartenvogel mit gelber Brust"),
    GermanCrosswordEntry("SCHWALBE", "Zugvogel, der tief fliegt"),
    GermanCrosswordEntry("STRAUSS", "Größter Vogel der Welt"),
    GermanCrosswordEntry("PFAU", "Vogel mit prächtigem Rad"),
    GermanCrosswordEntry("KROKODIL", "Panzerechse im Fluss"),
    GermanCrosswordEntry("SCHILDKROETE", "Reptil mit Panzer"),
    GermanCrosswordEntry("KROETE", "Warzige Verwandte des Frosches"),
    GermanCrosswordEntry("SALAMANDER", "Schwarz-gelber Lurch"),
    GermanCrosswordEntry("HECHT", "Räuberischer Süßwasserfisch"),
    GermanCrosswordEntry("KARPFEN", "Fisch im Teich"),
    GermanCrosswordEntry("LACHS", "Fisch, der flussaufwärts wandert"),
    GermanCrosswordEntry("HERING", "Fisch aus der Nordsee"),
    GermanCrosswordEntry("QUALLE", "Glibberiges Meerestier"),
    GermanCrosswordEntry("KRABBE", "Krebstier am Strand"),
    GermanCrosswordEntry("HUMMER", "Meerestier mit großen Scheren"),
    GermanCrosswordEntry("MUSCHEL", "Rauscht am Ohr"),
    GermanCrosswordEntry("SEESTERN", "Fünfarmiges Meerestier"),
    GermanCrosswordEntry("KORALLE", "Baut Riffe im Meer"),
    GermanCrosswordEntry("WESPE", "Stechendes Insekt am Kuchen"),
    GermanCrosswordEntry("HUMMEL", "Dicke pelzige Verwandte der Biene"),
    GermanCrosswordEntry("KAEFER", "Insekt mit hartem Flügelpanzer"),
    GermanCrosswordEntry("MUECKE", "Sticht im Sommer am Abend"),
    GermanCrosswordEntry("FLIEGE", "Summt um die Lampe"),
    GermanCrosswordEntry("FALTER", "Bunter Schmetterling"),
    GermanCrosswordEntry("RAUPE", "Wird später zum Falter"),
    GermanCrosswordEntry("LIBELLE", "Insekt mit langem Körper am Teich"),
    GermanCrosswordEntry("GRILLE", "Zirpt in der Nacht"),
    GermanCrosswordEntry("SCHNECKE", "Kriecht mit Haus auf dem Rücken"),
    GermanCrosswordEntry("REGENWURM", "Lockert die Erde"),
    GermanCrosswordEntry("SKORPION", "Spinnentier mit Giftstachel"),
    GermanCrosswordEntry("GORILLA", "Größter Menschenaffe"),
    GermanCrosswordEntry("PANDA", "Schwarz-weißer Bär aus China"),
    GermanCrosswordEntry("KOALA", "Beuteltier aus Australien"),
    GermanCrosswordEntry("KAENGURU", "Springt mit Beutel"),
    GermanCrosswordEntry("FAULTIER", "Langsamstes Säugetier"),
    GermanCrosswordEntry("NASHORN", "Dickhäuter mit Horn"),
    GermanCrosswordEntry("NILPFERD", "Schweres Tier im afrikanischen Fluss"),
    GermanCrosswordEntry("LEOPARD", "Raubkatze mit Flecken"),
    GermanCrosswordEntry("GEPARD", "Schnellstes Landtier"),
    GermanCrosswordEntry("PUMA", "Raubkatze Amerikas"),
    GermanCrosswordEntry("JAGUAR", "Raubkatze des Regenwaldes"),
    GermanCrosswordEntry("RENTIER", "Zieht den Schlitten"),
    GermanCrosswordEntry("ELCH", "Größter Hirsch des Nordens"),
    GermanCrosswordEntry("BISON", "Wildrind der Prärie"),
    GermanCrosswordEntry("LAMA", "Wolltier aus den Anden"),
    GermanCrosswordEntry("ALPAKA", "Verwandter des Lamas"),
    GermanCrosswordEntry("PONY", "Kleines Pferd"),
    GermanCrosswordEntry("FOHLEN", "Junges Pferd"),
    GermanCrosswordEntry("KALB", "Junges Rind"),
    GermanCrosswordEntry("FERKEL", "Junges Schwein"),
    GermanCrosswordEntry("WELPE", "Junger Hund"),
    GermanCrosswordEntry("NEST", "Zuhause der Vögel"),
    GermanCrosswordEntry("HORN", "Waffe auf dem Kopf des Stiers"),
    GermanCrosswordEntry("FELL", "Behaarte Tierhaut"),
    GermanCrosswordEntry("PFOTE", "Fuß der Katze"),
    GermanCrosswordEntry("FLUEGEL", "Ermöglicht den Vögeln das Fliegen"),
    GermanCrosswordEntry("SCHNABEL", "Mund des Vogels"),
    GermanCrosswordEntry("KRALLE", "Scharfer Nagel der Raubtiere"),
    GermanCrosswordEntry("STACHEL", "Waffe der Biene"),
    GermanCrosswordEntry("MAEHNE", "Haarpracht des Löwen"),
    GermanCrosswordEntry("BUCHE", "Laubbaum mit glatter Rinde"),
    GermanCrosswordEntry("FICHTE", "Nadelbaum im Wald"),
    GermanCrosswordEntry("ULME", "Laubbaum mit rauen Blättern"),
    GermanCrosswordEntry("PAPPEL", "Hoher schlanker Laubbaum"),
    GermanCrosswordEntry("WEIDE", "Baum mit hängenden Zweigen am Wasser"),
    GermanCrosswordEntry("KASTANIE", "Baum mit stacheligen Früchten"),
    GermanCrosswordEntry("PALME", "Baum am tropischen Strand"),
    GermanCrosswordEntry("KAKTUS", "Stachelige Wüstenpflanze"),
    GermanCrosswordEntry("FARN", "Pflanze mit gefiederten Wedeln"),
    GermanCrosswordEntry("EFEU", "Immergrüne Kletterpflanze"),
    GermanCrosswordEntry("DISTEL", "Stachelige Wiesenpflanze"),
    GermanCrosswordEntry("LOEWENZAHN", "Gelbe Wiesenblume mit Pusteblume"),
    GermanCrosswordEntry("MARGERITE", "Weiße Wiesenblume"),
    GermanCrosswordEntry("SONNENBLUME", "Dreht sich zur Sonne"),
    GermanCrosswordEntry("LILIE", "Elegante Blume mit großen Blüten"),
    GermanCrosswordEntry("ORCHIDEE", "Edle Zimmerblume"),
    GermanCrosswordEntry("NARZISSE", "Gelbe Frühlingsblume"),
    GermanCrosswordEntry("KROKUS", "Frühblüher im Rasen"),
    GermanCrosswordEntry("FLIEDER", "Duftender Strauch im Mai"),
    GermanCrosswordEntry("HOLUNDER", "Strauch mit schwarzen Beeren"),
    GermanCrosswordEntry("BROMBEERE", "Dunkle Beere am Dornenstrauch"),
    GermanCrosswordEntry("HIMBEERE", "Rote Beere am Strauch"),
    GermanCrosswordEntry("HEIDELBEERE", "Blaue Waldbeere"),
    GermanCrosswordEntry("PFLAUME", "Blaue Steinfrucht"),
    GermanCrosswordEntry("APRIKOSE", "Orange Steinfrucht"),
    GermanCrosswordEntry("PFIRSICH", "Pelzige Steinfrucht"),
    GermanCrosswordEntry("MANDARINE", "Kleine Zitrusfrucht"),
    GermanCrosswordEntry("MANGO", "Tropische süße Frucht"),
    GermanCrosswordEntry("KOKOSNUSS", "Harte Frucht der Palme"),
    GermanCrosswordEntry("FEIGE", "Süße Frucht aus dem Süden"),
    GermanCrosswordEntry("DATTEL", "Süße Frucht der Oase"),
    GermanCrosswordEntry("OLIVE", "Frucht für das Öl"),
    GermanCrosswordEntry("WALNUSS", "Nuss mit harter Schale"),
    GermanCrosswordEntry("HASELNUSS", "Nuss für die Schokolade"),
    GermanCrosswordEntry("MANDEL", "Nuss im Marzipan"),
    GermanCrosswordEntry("KUERBIS", "Große Frucht zu Halloween"),
    GermanCrosswordEntry("ZUCCHINI", "Grünes Gemüse wie eine Gurke"),
    GermanCrosswordEntry("PAPRIKA", "Buntes Gemüse, auch als Gewürz"),
    GermanCrosswordEntry("SPINAT", "Grünes Gemüse von Popeye"),
    GermanCrosswordEntry("KOHL", "Gemüse mit vielen Blättern"),
    GermanCrosswordEntry("LAUCH", "Langes Gemüse mit Zwiebelgeschmack"),
    GermanCrosswordEntry("RETTICH", "Scharfe weiße Knolle"),
    GermanCrosswordEntry("SELLERIE", "Suppengemüse mit Knolle"),
    GermanCrosswordEntry("ERBSE", "Kleine grüne Hülsenfrucht"),
    GermanCrosswordEntry("BOHNE", "Hülsenfrucht im Eintopf"),
    GermanCrosswordEntry("LINSE", "Kleine Hülsenfrucht im Eintopf"),
    GermanCrosswordEntry("WEIZEN", "Getreide für das Mehl"),
    GermanCrosswordEntry("ROGGEN", "Getreide für dunkles Brot"),
    GermanCrosswordEntry("HAFER", "Getreide für den Brei"),
    GermanCrosswordEntry("GERSTE", "Getreide für das Bier"),
    GermanCrosswordEntry("MAIS", "Getreide mit goldenen Kolben"),
    GermanCrosswordEntry("HEU", "Getrocknetes Gras für das Vieh"),
    GermanCrosswordEntry("STROH", "Trockene Getreidehalme im Stall"),
    GermanCrosswordEntry("WURZEL", "Unterirdischer Teil der Pflanze"),
    GermanCrosswordEntry("BLATT", "Grünes Pflanzenteil"),
    GermanCrosswordEntry("BLUETE", "Farbenprächtiger Pflanzenteil"),
    GermanCrosswordEntry("STAMM", "Tragender Teil des Baumes"),
    GermanCrosswordEntry("AST", "Verzweigung am Baum"),
    GermanCrosswordEntry("RINDE", "Äußere Schicht des Baumstamms"),
    GermanCrosswordEntry("SAMEN", "Woraus die Pflanze wächst"),
    GermanCrosswordEntry("KNOSPE", "Noch geschlossene Blüte"),
    GermanCrosswordEntry("DORN", "Spitzer Wehrteil der Rose"),
    GermanCrosswordEntry("LAUB", "Fällt im Herbst vom Baum"),
    GermanCrosswordEntry("ERNTE", "Einbringen der Feldfrüchte"),
    GermanCrosswordEntry("SAAT", "Was der Bauer im Frühling ausbringt"),
    GermanCrosswordEntry("HERZ", "Pumpt das Blut"),
    GermanCrosswordEntry("LUNGE", "Organ zum Atmen"),
    GermanCrosswordEntry("LEBER", "Entgiftet den Körper"),
    GermanCrosswordEntry("NIERE", "Organ, das den Urin bildet"),
    GermanCrosswordEntry("MAGEN", "Verdaut das Essen"),
    GermanCrosswordEntry("GEHIRN", "Zentrale des Denkens"),
    GermanCrosswordEntry("KNOCHEN", "Teil des Skeletts"),
    GermanCrosswordEntry("SKELETT", "Knochengerüst des Körpers"),
    GermanCrosswordEntry("MUSKEL", "Sorgt für Bewegung"),
    GermanCrosswordEntry("ADER", "Leitet das Blut"),
    GermanCrosswordEntry("BLUT", "Rote Körperflüssigkeit"),
    GermanCrosswordEntry("HAUT", "Größtes Organ des Menschen"),
    GermanCrosswordEntry("NASE", "Organ zum Riechen"),
    GermanCrosswordEntry("AUGE", "Organ zum Sehen"),
    GermanCrosswordEntry("OHR", "Organ zum Hören"),
    GermanCrosswordEntry("ZUNGE", "Organ zum Schmecken"),
    GermanCrosswordEntry("ZAHN", "Zum Kauen im Mund"),
    GermanCrosswordEntry("LIPPE", "Rand des Mundes"),
    GermanCrosswordEntry("KINN", "Unter dem Mund"),
    GermanCrosswordEntry("STIRN", "Über den Augen"),
    GermanCrosswordEntry("WANGE", "Seitlicher Teil des Gesichts"),
    GermanCrosswordEntry("HALS", "Verbindet Kopf und Rumpf"),
    GermanCrosswordEntry("SCHULTER", "Wo der Arm ansetzt"),
    GermanCrosswordEntry("ELLBOGEN", "Gelenk im Arm"),
    GermanCrosswordEntry("FINGER", "Zehn davon an den Händen"),
    GermanCrosswordEntry("DAUMEN", "Kürzester Finger"),
    GermanCrosswordEntry("KNIE", "Gelenk im Bein"),
    GermanCrosswordEntry("FERSE", "Hinterer Teil des Fußes"),
    GermanCrosswordEntry("ZEHE", "Finger am Fuß"),
    GermanCrosswordEntry("RIPPE", "Knochen im Brustkorb"),
    GermanCrosswordEntry("RUECKEN", "Körperseite hinten"),
    GermanCrosswordEntry("BAUCH", "Vorderseite des Rumpfes"),
    GermanCrosswordEntry("HUEFTE", "Seitlicher Beckenbereich"),
    GermanCrosswordEntry("WIRBEL", "Knochen der Wirbelsäule"),
    GermanCrosswordEntry("FIEBER", "Erhöhte Körpertemperatur"),
    GermanCrosswordEntry("HUSTEN", "Symptom bei Erkältung"),
    GermanCrosswordEntry("SCHNUPFEN", "Laufende Nase"),
    GermanCrosswordEntry("GRIPPE", "Ansteckende Viruskrankheit"),
    GermanCrosswordEntry("WUNDE", "Verletzung der Haut"),
    GermanCrosswordEntry("NARBE", "Bleibt nach der Wunde"),
    GermanCrosswordEntry("PFLASTER", "Klebt auf der Wunde"),
    GermanCrosswordEntry("VERBAND", "Wickelt die Wunde ein"),
    GermanCrosswordEntry("SALBE", "Creme aus der Apotheke"),
    GermanCrosswordEntry("TABLETTE", "Medikament zum Schlucken"),
    GermanCrosswordEntry("SPRITZE", "Injektion beim Arzt"),
    GermanCrosswordEntry("IMPFUNG", "Schutz vor einer Krankheit"),
    GermanCrosswordEntry("APOTHEKE", "Hier gibt es Medikamente"),
    GermanCrosswordEntry("KLINIK", "Haus für Kranke"),
    GermanCrosswordEntry("ZAHNARZT", "Kümmert sich um die Zähne"),
    GermanCrosswordEntry("MEHL", "Grundstoff zum Backen"),
    GermanCrosswordEntry("TEIG", "Vorstufe des Brotes"),
    GermanCrosswordEntry("HEFE", "Lässt den Teig aufgehen"),
    GermanCrosswordEntry("SAHNE", "Kommt auf den Kuchen"),
    GermanCrosswordEntry("JOGHURT", "Sauermilchprodukt im Becher"),
    GermanCrosswordEntry("QUARK", "Frischkäse für den Kuchen"),
    GermanCrosswordEntry("MARMELADE", "Süßer Brotaufstrich"),
    GermanCrosswordEntry("SCHOKOLADE", "Süßigkeit aus Kakao"),
    GermanCrosswordEntry("KAKAO", "Getränk aus der braunen Bohne"),
    GermanCrosswordEntry("BONBON", "Süßigkeit zum Lutschen"),
    GermanCrosswordEntry("KEKS", "Kleines süßes Gebäck"),
    GermanCrosswordEntry("WAFFEL", "Süßes Gebäck aus dem Eisen"),
    GermanCrosswordEntry("BREZEL", "Gebäck mit Knoten"),
    GermanCrosswordEntry("SEMMEL", "Österreichisches Brötchen"),
    GermanCrosswordEntry("KNOEDEL", "Runde Beilage aus Teig"),
    GermanCrosswordEntry("POMMES", "Frittierte Kartoffelstäbchen"),
    GermanCrosswordEntry("PIZZA", "Italienisches Gericht aus dem Ofen"),
    GermanCrosswordEntry("PASTA", "Italienische Teigwaren"),
    GermanCrosswordEntry("SPAGHETTI", "Lange dünne Nudeln"),
    GermanCrosswordEntry("LASAGNE", "Geschichteter Nudelauflauf"),
    GermanCrosswordEntry("RISOTTO", "Cremiges Reisgericht"),
    GermanCrosswordEntry("GULASCH", "Ungarisches Fleischgericht"),
    GermanCrosswordEntry("SCHNITZEL", "Paniertes Fleisch"),
    GermanCrosswordEntry("BRATEN", "Großes Stück Fleisch aus dem Ofen"),
    GermanCrosswordEntry("WURST", "Kommt in die Semmel"),
    GermanCrosswordEntry("SCHINKEN", "Geräuchertes vom Schwein"),
    GermanCrosswordEntry("SPECK", "Fettes Stück vom Schwein"),
    GermanCrosswordEntry("FISCH", "Tier mit Flossen und Kiemen"),
    GermanCrosswordEntry("EIER", "Kommen vom Huhn"),
    GermanCrosswordEntry("OMELETT", "Eierspeise aus der Pfanne"),
    GermanCrosswordEntry("PFANNE", "Flaches Kochgeschirr"),
    GermanCrosswordEntry("TOPF", "Gefäß zum Kochen"),
    GermanCrosswordEntry("HERD", "Wird zum Kochen heiß"),
    GermanCrosswordEntry("BACKOFEN", "Zum Backen des Kuchens"),
    GermanCrosswordEntry("MIXER", "Gerät zum Pürieren"),
    GermanCrosswordEntry("TELLER", "Von ihm wird gegessen"),
    GermanCrosswordEntry("TASSE", "Gefäß für den Kaffee"),
    GermanCrosswordEntry("GLAS", "Gefäß für das Wasser"),
    GermanCrosswordEntry("FLASCHE", "Behälter für Getränke"),
    GermanCrosswordEntry("GABEL", "Besteck mit Zinken"),
    GermanCrosswordEntry("MESSER", "Besteck zum Schneiden"),
    GermanCrosswordEntry("LOEFFEL", "Besteck für die Suppe"),
    GermanCrosswordEntry("SERVIETTE", "Für den Mund beim Essen"),
    GermanCrosswordEntry("TABLETT", "Zum Tragen der Teller"),
    GermanCrosswordEntry("KORKEN", "Verschluss der Weinflasche"),
    GermanCrosswordEntry("REZEPT", "Anleitung zum Kochen"),
    GermanCrosswordEntry("MENUE", "Abfolge mehrerer Gänge"),
    GermanCrosswordEntry("DURST", "Verlangen nach Trinken"),
    GermanCrosswordEntry("HUNGER", "Verlangen nach Essen"),
    GermanCrosswordEntry("BETT", "Möbel zum Schlafen"),
    GermanCrosswordEntry("MATRATZE", "Liegt auf dem Bettrahmen"),
    GermanCrosswordEntry("STUHL", "Möbel zum Sitzen"),
    GermanCrosswordEntry("SESSEL", "Bequemes Polstermöbel"),
    GermanCrosswordEntry("TISCH", "Möbel mit Platte und Beinen"),
    GermanCrosswordEntry("KOMMODE", "Möbel mit Schubladen"),
    GermanCrosswordEntry("SCHUBLADE", "Lässt sich herausziehen"),
    GermanCrosswordEntry("VORHANG", "Hängt vor dem Fenster"),
    GermanCrosswordEntry("FLIESE", "Platte an der Badwand"),
    GermanCrosswordEntry("BODEN", "Untere Fläche im Zimmer"),
    GermanCrosswordEntry("WAND", "Senkrechte Begrenzung des Raums"),
    GermanCrosswordEntry("AUFZUG", "Fährt in den oberen Stock"),
    GermanCrosswordEntry("BALKON", "Vorsprung an der Hauswand"),
    GermanCrosswordEntry("TERRASSE", "Sitzplatz vor dem Haus"),
    GermanCrosswordEntry("GARAGE", "Unterstand für das Auto"),
    GermanCrosswordEntry("BRIEFKASTEN", "Hier landet die Post"),
    GermanCrosswordEntry("KLINGEL", "Ertönt an der Haustür"),
    GermanCrosswordEntry("SCHLUESSEL", "Öffnet die Tür"),
    GermanCrosswordEntry("RIEGEL", "Sichert die Tür"),
    GermanCrosswordEntry("STAUBSAUGER", "Gerät zum Reinigen"),
    GermanCrosswordEntry("SCHWAMM", "Zum Abwischen"),
    GermanCrosswordEntry("HANDTUCH", "Zum Abtrocknen"),
    GermanCrosswordEntry("DUSCHE", "Zum Waschen im Bad"),
    GermanCrosswordEntry("BADEWANNE", "Zum Baden im Wasser"),
    GermanCrosswordEntry("WASCHBECKEN", "Mit Wasserhahn im Bad"),
    GermanCrosswordEntry("BUERSTE", "Für die Haare"),
    GermanCrosswordEntry("ZAHNBUERSTE", "Putzt die Zähne"),
    GermanCrosswordEntry("BUEGELEISEN", "Glättet die Wäsche"),
    GermanCrosswordEntry("WAESCHE", "Was gewaschen wird"),
    GermanCrosswordEntry("HEMD", "Oberteil mit Knöpfen"),
    GermanCrosswordEntry("HOSE", "Kleidungsstück für die Beine"),
    GermanCrosswordEntry("ROCK", "Kleidungsstück für Damen"),
    GermanCrosswordEntry("KLEID", "Einteiliges Damenkleidungsstück"),
    GermanCrosswordEntry("JACKE", "Wärmt draußen"),
    GermanCrosswordEntry("PULLOVER", "Warmes Oberteil aus Wolle"),
    GermanCrosswordEntry("WESTE", "Jacke ohne Ärmel"),
    GermanCrosswordEntry("SOCKE", "Kommt in den Schuh"),
    GermanCrosswordEntry("SCHUH", "Schützt den Fuß"),
    GermanCrosswordEntry("SANDALE", "Offener Sommerschuh"),
    GermanCrosswordEntry("TURNSCHUH", "Schuh für den Sport"),
    GermanCrosswordEntry("KRAWATTE", "Um den Hals zum Hemd"),
    GermanCrosswordEntry("GUERTEL", "Hält die Hose"),
    GermanCrosswordEntry("HANDSCHUH", "Wärmt die Finger"),
    GermanCrosswordEntry("MUETZE", "Wärmt den Kopf"),
    GermanCrosswordEntry("KAPUZE", "Am Pullover über dem Kopf"),
    GermanCrosswordEntry("SCHIRM", "Schützt vor Regen"),
    GermanCrosswordEntry("ANZUG", "Feine Herrenkleidung"),
    GermanCrosswordEntry("UNIFORM", "Einheitliche Dienstkleidung"),
    GermanCrosswordEntry("KOSTUEM", "Verkleidung im Fasching"),
    GermanCrosswordEntry("MASKE", "Verdeckt das Gesicht"),
    GermanCrosswordEntry("ARMBAND", "Schmuck am Handgelenk"),
    GermanCrosswordEntry("OHRRING", "Schmuck am Ohr"),
    GermanCrosswordEntry("STOFF", "Material für Kleidung"),
    GermanCrosswordEntry("WOLLE", "Kommt vom Schaf"),
    GermanCrosswordEntry("SEIDE", "Edler Stoff der Raupe"),
    GermanCrosswordEntry("LEDER", "Material aus Tierhaut"),
    GermanCrosswordEntry("BAUMWOLLE", "Pflanzliche Faser"),
    GermanCrosswordEntry("FADEN", "Wird in die Nadel gefädelt"),
    GermanCrosswordEntry("KNOTEN", "Verknüpfung im Seil"),
    GermanCrosswordEntry("METZGER", "Verkauft Fleisch"),
    GermanCrosswordEntry("GAERTNER", "Pflegt den Garten"),
    GermanCrosswordEntry("FRISEUR", "Schneidet die Haare"),
    GermanCrosswordEntry("SCHNEIDER", "Näht die Kleidung"),
    GermanCrosswordEntry("TISCHLER", "Arbeitet mit Holz"),
    GermanCrosswordEntry("MAURER", "Baut Wände aus Ziegeln"),
    GermanCrosswordEntry("MALER", "Streicht die Wände"),
    GermanCrosswordEntry("DACHDECKER", "Arbeitet auf dem Dach"),
    GermanCrosswordEntry("KLEMPNER", "Repariert die Wasserleitung"),
    GermanCrosswordEntry("ELEKTRIKER", "Kümmert sich um den Strom"),
    GermanCrosswordEntry("MECHANIKER", "Repariert Motoren"),
    GermanCrosswordEntry("FAHRER", "Lenkt das Fahrzeug"),
    GermanCrosswordEntry("POLIZIST", "Sorgt für Ordnung"),
    GermanCrosswordEntry("FEUERWEHR", "Löscht den Brand"),
    GermanCrosswordEntry("SOLDAT", "Dient beim Militär"),
    GermanCrosswordEntry("ANWALT", "Vertritt vor Gericht"),
    GermanCrosswordEntry("NOTAR", "Beglaubigt Verträge"),
    GermanCrosswordEntry("HAENDLER", "Kauft und verkauft"),
    GermanCrosswordEntry("KELLNER", "Serviert im Restaurant"),
    GermanCrosswordEntry("BAUER", "Bewirtschaftet den Hof"),
    GermanCrosswordEntry("FISCHER", "Fängt Fische"),
    GermanCrosswordEntry("JAEGER", "Geht auf die Pirsch"),
    GermanCrosswordEntry("FOERSTER", "Betreut den Wald"),
    GermanCrosswordEntry("IMKER", "Hält die Bienen"),
    GermanCrosswordEntry("SCHMIED", "Arbeitet am Amboss"),
    GermanCrosswordEntry("MUELLER", "Mahlt das Korn"),
    GermanCrosswordEntry("WINZER", "Baut Wein an"),
    GermanCrosswordEntry("APOTHEKER", "Gibt Medikamente aus"),
    GermanCrosswordEntry("FORSCHER", "Sucht neues Wissen"),
    GermanCrosswordEntry("INGENIEUR", "Entwickelt Maschinen"),
    GermanCrosswordEntry("ARCHITEKT", "Plant Gebäude"),
    GermanCrosswordEntry("JOURNALIST", "Schreibt für die Zeitung"),
    GermanCrosswordEntry("SAENGER", "Singt auf der Bühne"),
    GermanCrosswordEntry("TAENZER", "Bewegt sich zur Musik"),
    GermanCrosswordEntry("MUSIKER", "Spielt ein Instrument"),
    GermanCrosswordEntry("KUENSTLER", "Schafft Kunstwerke"),
    GermanCrosswordEntry("FOTOGRAF", "Macht Bilder"),
    GermanCrosswordEntry("TRAINER", "Leitet die Mannschaft"),
    GermanCrosswordEntry("GAST", "Besucher im Hotel"),
    GermanCrosswordEntry("KUNDE", "Kauft im Geschäft"),
    GermanCrosswordEntry("CHEF", "Leitet den Betrieb"),
    GermanCrosswordEntry("GITARRE", "Instrument mit sechs Saiten"),
    GermanCrosswordEntry("CELLO", "Großes Streichinstrument"),
    GermanCrosswordEntry("POSAUNE", "Blechblasinstrument mit Zug"),
    GermanCrosswordEntry("KLARINETTE", "Holzblasinstrument"),
    GermanCrosswordEntry("SAXOFON", "Gebogenes Blasinstrument"),
    GermanCrosswordEntry("AKKORDEON", "Zieh-Instrument mit Balg"),
    GermanCrosswordEntry("ORGEL", "Instrument in der Kirche"),
    GermanCrosswordEntry("TRIANGEL", "Dreieckiges Schlaginstrument"),
    GermanCrosswordEntry("NOTE", "Zeichen für einen Ton"),
    GermanCrosswordEntry("TAKT", "Rhythmische Einheit der Musik"),
    GermanCrosswordEntry("MELODIE", "Folge von Tönen"),
    GermanCrosswordEntry("LIED", "Gesungenes Musikstück"),
    GermanCrosswordEntry("REFRAIN", "Kehrt im Lied wieder"),
    GermanCrosswordEntry("BUEHNE", "Wo gespielt wird"),
    GermanCrosswordEntry("APPLAUS", "Beifall des Publikums"),
    GermanCrosswordEntry("KONZERT", "Musikalische Aufführung"),
    GermanCrosswordEntry("BALLETT", "Klassischer Bühnentanz"),
    GermanCrosswordEntry("WALZER", "Tanz im Dreivierteltakt"),
    GermanCrosswordEntry("TANGO", "Tanz aus Argentinien"),
    GermanCrosswordEntry("ORCHESTER", "Große Musikergruppe"),
    GermanCrosswordEntry("DIRIGENT", "Leitet das Orchester"),
    GermanCrosswordEntry("LEINWAND", "Untergrund des Malers"),
    GermanCrosswordEntry("SKULPTUR", "Plastisches Kunstwerk"),
    GermanCrosswordEntry("STATUE", "Standbild aus Stein"),
    GermanCrosswordEntry("GEMAELDE", "Gemaltes Bild"),
    GermanCrosswordEntry("GALERIE", "Ausstellungsraum für Kunst"),
    GermanCrosswordEntry("GEDICHT", "Text in Versen"),
    GermanCrosswordEntry("SAGE", "Alte überlieferte Erzählung"),
    GermanCrosswordEntry("FABEL", "Erzählung mit sprechenden Tieren"),
    GermanCrosswordEntry("KAPITEL", "Abschnitt eines Buches"),
    GermanCrosswordEntry("SEITE", "Blatt im Buch"),
    GermanCrosswordEntry("TITEL", "Name eines Buches"),
    GermanCrosswordEntry("AUTOR", "Verfasser eines Buches"),
    GermanCrosswordEntry("VERLAG", "Gibt Bücher heraus"),
    GermanCrosswordEntry("BIBLIOTHEK", "Hier leiht man Bücher"),
    GermanCrosswordEntry("HANDBALL", "Ballsport in der Halle"),
    GermanCrosswordEntry("BASKETBALL", "Ballsport mit Korb"),
    GermanCrosswordEntry("VOLLEYBALL", "Ballsport über das Netz"),
    GermanCrosswordEntry("GOLF", "Sport mit Schläger und Loch"),
    GermanCrosswordEntry("BOXEN", "Kampfsport mit Handschuhen"),
    GermanCrosswordEntry("JUDO", "Japanischer Kampfsport"),
    GermanCrosswordEntry("KARATE", "Kampfsport mit Schlägen und Tritten"),
    GermanCrosswordEntry("TURNEN", "Sport am Reck und Barren"),
    GermanCrosswordEntry("SCHWIMMEN", "Sport im Wasser"),
    GermanCrosswordEntry("RUDERN", "Sport mit Riemen im Boot"),
    GermanCrosswordEntry("SEGELN", "Sport mit Wind auf dem Wasser"),
    GermanCrosswordEntry("RADFAHREN", "Sport auf zwei Rädern"),
    GermanCrosswordEntry("KLETTERN", "Sport an der Felswand"),
    GermanCrosswordEntry("WANDERN", "Zu Fuß in den Bergen"),
    GermanCrosswordEntry("LAUFEN", "Sich schnell zu Fuß bewegen"),
    GermanCrosswordEntry("SPRINT", "Kurzer schneller Lauf"),
    GermanCrosswordEntry("STAFFEL", "Lauf mit Übergabe des Stabs"),
    GermanCrosswordEntry("HUERDE", "Hindernis beim Lauf"),
    GermanCrosswordEntry("NETZ", "Trennt die Spielfeldhälften"),
    GermanCrosswordEntry("BALL", "Rundes Sportgerät"),
    GermanCrosswordEntry("SCHLAEGER", "Gerät beim Tennis"),
    GermanCrosswordEntry("HELM", "Schützt den Kopf"),
    GermanCrosswordEntry("TRIKOT", "Sportkleidung der Mannschaft"),
    GermanCrosswordEntry("POKAL", "Preis für den Sieger"),
    GermanCrosswordEntry("SIEG", "Gewonnener Wettkampf"),
    GermanCrosswordEntry("NIEDERLAGE", "Verlorener Wettkampf"),
    GermanCrosswordEntry("PUNKT", "Wertung im Spiel"),
    GermanCrosswordEntry("REKORD", "Bestleistung im Sport"),
    GermanCrosswordEntry("TURNIER", "Wettkampf mit mehreren Runden"),
    GermanCrosswordEntry("SPIELER", "Nimmt am Spiel teil"),
    GermanCrosswordEntry("MANNSCHAFT", "Gruppe von Spielern"),
    GermanCrosswordEntry("HALLE", "Überdachter Sportraum"),
    GermanCrosswordEntry("PISTE", "Abfahrt im Skigebiet"),
    GermanCrosswordEntry("LIFT", "Bringt Skifahrer den Berg hinauf"),
    GermanCrosswordEntry("SCHLITTEN", "Fährt über den Schnee"),
    GermanCrosswordEntry("EISHOCKEY", "Sport auf dem Eis"),
    GermanCrosswordEntry("AUTO", "Fahrzeug mit vier Rädern"),
    GermanCrosswordEntry("FAHRRAD", "Fahrzeug mit zwei Rädern"),
    GermanCrosswordEntry("MOTORRAD", "Zweirad mit Motor"),
    GermanCrosswordEntry("BUS", "Verkehrsmittel auf der Straße"),
    GermanCrosswordEntry("TRAM", "Straßenbahn in der Stadt"),
    GermanCrosswordEntry("TAXI", "Bezahlte Fahrt in der Stadt"),
    GermanCrosswordEntry("LASTWAGEN", "Transportiert Güter"),
    GermanCrosswordEntry("TRAKTOR", "Zugmaschine des Bauern"),
    GermanCrosswordEntry("BAGGER", "Gräbt auf der Baustelle"),
    GermanCrosswordEntry("KRAN", "Hebt schwere Lasten"),
    GermanCrosswordEntry("FLUGZEUG", "Fliegt durch die Luft"),
    GermanCrosswordEntry("HUBSCHRAUBER", "Fliegt mit Rotor"),
    GermanCrosswordEntry("BALLON", "Steigt mit heißer Luft"),
    GermanCrosswordEntry("SCHIFF", "Fährt über das Meer"),
    GermanCrosswordEntry("BOOT", "Kleines Wasserfahrzeug"),
    GermanCrosswordEntry("KANU", "Boot mit Stechpaddel"),
    GermanCrosswordEntry("FLOSS", "Wasserfahrzeug aus Stämmen"),
    GermanCrosswordEntry("RUDER", "Zum Antrieb des Bootes"),
    GermanCrosswordEntry("PADDEL", "Antrieb des Kanus"),
    GermanCrosswordEntry("LENKRAD", "Zum Steuern des Autos"),
    GermanCrosswordEntry("BREMSE", "Bringt das Fahrzeug zum Stehen"),
    GermanCrosswordEntry("BENZIN", "Treibstoff für das Auto"),
    GermanCrosswordEntry("DIESEL", "Treibstoff des Lastwagens"),
    GermanCrosswordEntry("KREUZUNG", "Wo Straßen sich treffen"),
    GermanCrosswordEntry("AUTOBAHN", "Schnelle Straße ohne Kreuzungen"),
    GermanCrosswordEntry("PARKPLATZ", "Abstellfläche für Autos"),
    GermanCrosswordEntry("BAHNHOF", "Halt für Züge"),
    GermanCrosswordEntry("FLUGHAFEN", "Start und Landung der Flugzeuge"),
    GermanCrosswordEntry("GEPAECK", "Was man auf Reisen mitnimmt"),
    GermanCrosswordEntry("FAHRKARTE", "Berechtigt zur Fahrt"),
    GermanCrosswordEntry("FAHRPLAN", "Zeigt die Abfahrtszeiten"),
    GermanCrosswordEntry("STAU", "Stockender Verkehr"),
    GermanCrosswordEntry("DRUCKER", "Bringt Text aufs Papier"),
    GermanCrosswordEntry("KAMERA", "Gerät zum Fotografieren"),
    GermanCrosswordEntry("BATTERIE", "Speichert Strom"),
    GermanCrosswordEntry("KABEL", "Leitet den Strom"),
    GermanCrosswordEntry("STECKER", "Kommt in die Steckdose"),
    GermanCrosswordEntry("STECKDOSE", "Hier kommt der Strom heraus"),
    GermanCrosswordEntry("SCHALTER", "Macht das Licht an"),
    GermanCrosswordEntry("GLUEHBIRNE", "Spendet Licht"),
    GermanCrosswordEntry("KOPFHOERER", "Musik für die Ohren"),
    GermanCrosswordEntry("MIKROFON", "Nimmt den Ton auf"),
    GermanCrosswordEntry("FERNSEHER", "Gerät für Filme"),
    GermanCrosswordEntry("SATELLIT", "Kreist um die Erde"),
    GermanCrosswordEntry("PROGRAMM", "Software auf dem Computer"),
    GermanCrosswordEntry("DATEI", "Gespeicherte Daten"),
    GermanCrosswordEntry("SPEICHER", "Hier liegen die Daten"),
    GermanCrosswordEntry("PASSWORT", "Geheimes Kennwort"),
    GermanCrosswordEntry("NETZWERK", "Verbindet Computer"),
    GermanCrosswordEntry("SERVER", "Zentraler Rechner"),
    GermanCrosswordEntry("LADEGERAET", "Füllt den Akku"),
    GermanCrosswordEntry("MASCHINE", "Technisches Arbeitsgerät"),
    GermanCrosswordEntry("TURBINE", "Wandelt Strömung in Drehung"),
    GermanCrosswordEntry("GETRIEBE", "Überträgt die Kraft"),
    GermanCrosswordEntry("ZAHNRAD", "Greift in ein anderes Rad"),
    GermanCrosswordEntry("SCHRAUBE", "Wird eingedreht"),
    GermanCrosswordEntry("ZANGE", "Werkzeug zum Greifen"),
    GermanCrosswordEntry("BOHRER", "Macht ein Loch"),
    GermanCrosswordEntry("FEILE", "Glättet das Metall"),
    GermanCrosswordEntry("WERKZEUG", "Sammelbegriff für Hammer und Zange"),
    GermanCrosswordEntry("WERKSTATT", "Raum zum Reparieren"),
    GermanCrosswordEntry("FABRIK", "Hier wird produziert"),
    GermanCrosswordEntry("MERKUR", "Innerster Planet"),
    GermanCrosswordEntry("JUPITER", "Größter Planet"),
    GermanCrosswordEntry("SATURN", "Planet mit Ringen"),
    GermanCrosswordEntry("URANUS", "Planet hinter dem Saturn"),
    GermanCrosswordEntry("NEPTUN", "Äußerster Planet"),
    GermanCrosswordEntry("PLUTO", "Ehemaliger neunter Planet"),
    GermanCrosswordEntry("GALAXIE", "Riesiges Sternsystem"),
    GermanCrosswordEntry("METEOR", "Sternschnuppe am Himmel"),
    GermanCrosswordEntry("UMLAUFBAHN", "Weg um einen Himmelskörper"),
    GermanCrosswordEntry("ASTRONAUT", "Reist ins Weltall"),
    GermanCrosswordEntry("RAUMSCHIFF", "Fahrzeug im All"),
    GermanCrosswordEntry("ALL", "Der Weltraum"),
    GermanCrosswordEntry("LICHTJAHR", "Maß für große Entfernungen"),
    GermanCrosswordEntry("CHEMIE", "Lehre von den Stoffen"),
    GermanCrosswordEntry("PHYSIK", "Lehre von Kraft und Materie"),
    GermanCrosswordEntry("BIOLOGIE", "Lehre vom Leben"),
    GermanCrosswordEntry("MATHEMATIK", "Lehre von den Zahlen"),
    GermanCrosswordEntry("FORMEL", "Kurze Schreibweise in der Mathematik"),
    GermanCrosswordEntry("GLEICHUNG", "Hat ein Gleichheitszeichen"),
    GermanCrosswordEntry("WINKEL", "Wird in Grad gemessen"),
    GermanCrosswordEntry("KUGEL", "Vollkommen runder Körper"),
    GermanCrosswordEntry("LINIE", "Gerade Verbindung zweier Punkte"),
    GermanCrosswordEntry("METER", "Einheit der Länge"),
    GermanCrosswordEntry("LITER", "Einheit für Flüssigkeiten"),
    GermanCrosswordEntry("GRAMM", "Einheit der Masse"),
    GermanCrosswordEntry("KILO", "Tausend Gramm"),
    GermanCrosswordEntry("GRAD", "Einheit der Temperatur"),
    GermanCrosswordEntry("VOLT", "Einheit der Spannung"),
    GermanCrosswordEntry("WATT", "Einheit der Leistung"),
    GermanCrosswordEntry("MINUTE", "Sechzig Sekunden"),
    GermanCrosswordEntry("MOLEKUEL", "Verbund von Atomen"),
    GermanCrosswordEntry("ELEMENT", "Grundstoff im Periodensystem"),
    GermanCrosswordEntry("SAUERSTOFF", "Gas zum Atmen"),
    GermanCrosswordEntry("WASSERSTOFF", "Leichtestes Element"),
    GermanCrosswordEntry("KUPFER", "Rötliches Metall"),
    GermanCrosswordEntry("ZINN", "Weiches Metall für Legierungen"),
    GermanCrosswordEntry("BLEI", "Sehr schweres Metall"),
    GermanCrosswordEntry("STAHL", "Harte Eisenlegierung"),
    GermanCrosswordEntry("BETON", "Baustoff aus Zement und Kies"),
    GermanCrosswordEntry("ZEMENT", "Bindemittel im Beton"),
    GermanCrosswordEntry("ZIEGEL", "Gebrannter Baustein"),
    GermanCrosswordEntry("KUNSTSTOFF", "Synthetisches Material"),
    GermanCrosswordEntry("GUMMI", "Elastisches Material"),
    GermanCrosswordEntry("HOLZ", "Material aus dem Baum"),
    GermanCrosswordEntry("STEIN", "Harter Brocken aus dem Fels"),
    GermanCrosswordEntry("SAND", "Feines Material am Strand"),
    GermanCrosswordEntry("LEHM", "Formbarer Boden für Ziegel"),
    GermanCrosswordEntry("TON", "Material des Töpfers"),
    GermanCrosswordEntry("KRISTALL", "Regelmäßig geformter Festkörper"),
    GermanCrosswordEntry("FRUEHLING", "Jahreszeit nach dem Winter"),
    GermanCrosswordEntry("HAGEL", "Eiskörner vom Himmel"),
    GermanCrosswordEntry("TAU", "Feuchtigkeit am Morgengras"),
    GermanCrosswordEntry("EIS", "Gefrorenes Wasser"),
    GermanCrosswordEntry("HITZE", "Sehr warmes Wetter"),
    GermanCrosswordEntry("KAELTE", "Sehr tiefe Temperatur"),
    GermanCrosswordEntry("WIND", "Bewegte Luft"),
    GermanCrosswordEntry("BRISE", "Leichter Wind"),
    GermanCrosswordEntry("ORKAN", "Sehr heftiger Sturm"),
    GermanCrosswordEntry("GEWITTER", "Blitz und Donner zusammen"),
    GermanCrosswordEntry("REGENBOGEN", "Bunter Bogen nach dem Regen"),
    GermanCrosswordEntry("KLIMA", "Langfristiges Wettergeschehen"),
    GermanCrosswordEntry("WETTER", "Zustand der Atmosphäre"),
    GermanCrosswordEntry("THERMOMETER", "Misst die Temperatur"),
    GermanCrosswordEntry("BAROMETER", "Misst den Luftdruck"),
    GermanCrosswordEntry("JANUAR", "Erster Monat des Jahres"),
    GermanCrosswordEntry("FEBRUAR", "Kürzester Monat"),
    GermanCrosswordEntry("MAERZ", "Monat des Frühlingsanfangs"),
    GermanCrosswordEntry("MAI", "Monat der Maiglöckchen"),
    GermanCrosswordEntry("JUNI", "Monat des Sommeranfangs"),
    GermanCrosswordEntry("JULI", "Monat mitten im Sommer"),
    GermanCrosswordEntry("AUGUST", "Monat der großen Ferien"),
    GermanCrosswordEntry("SEPTEMBER", "Monat des Herbstanfangs"),
    GermanCrosswordEntry("OKTOBER", "Monat des Oktoberfests"),
    GermanCrosswordEntry("NOVEMBER", "Monat vor dem Dezember"),
    GermanCrosswordEntry("DEZEMBER", "Monat mit Weihnachten"),
    GermanCrosswordEntry("DIENSTAG", "Tag nach dem Montag"),
    GermanCrosswordEntry("MITTWOCH", "Mitte der Arbeitswoche"),
    GermanCrosswordEntry("DONNERSTAG", "Tag vor dem Freitag"),
    GermanCrosswordEntry("SAMSTAG", "Tag vor dem Sonntag"),
    GermanCrosswordEntry("SONNTAG", "Tag der Ruhe"),
    GermanCrosswordEntry("WOCHE", "Sieben Tage"),
    GermanCrosswordEntry("MONAT", "Zwölf davon im Jahr"),
    GermanCrosswordEntry("MORGEN", "Beginn des Tages"),
    GermanCrosswordEntry("MITTAG", "Zeit des Sonnenhöchststandes"),
    GermanCrosswordEntry("ABEND", "Ende des Tages"),
    GermanCrosswordEntry("NACHT", "Dunkle Zeit des Tages"),
    GermanCrosswordEntry("HEUTE", "Der aktuelle Tag"),
    GermanCrosswordEntry("GESTERN", "Der Tag davor"),
    GermanCrosswordEntry("KALENDER", "Zeigt Tage und Monate"),
    GermanCrosswordEntry("GEBURTSTAG", "Jährlicher Ehrentag"),
    GermanCrosswordEntry("WEIHNACHTEN", "Fest im Dezember"),
    GermanCrosswordEntry("OSTERN", "Fest mit bunten Eiern"),
    GermanCrosswordEntry("FASCHING", "Zeit der Verkleidung"),
    GermanCrosswordEntry("HOCHZEIT", "Fest der Vermählung"),
    GermanCrosswordEntry("FEIER", "Fröhliches Zusammensein"),
    GermanCrosswordEntry("LIEBE", "Starkes Gefühl der Zuneigung"),
    GermanCrosswordEntry("FREUDE", "Gefühl des Glücklichseins"),
    GermanCrosswordEntry("ANGST", "Gefühl der Bedrohung"),
    GermanCrosswordEntry("TRAUER", "Gefühl nach einem Verlust"),
    GermanCrosswordEntry("WUT", "Starker Zorn"),
    GermanCrosswordEntry("NEID", "Missgunst gegenüber anderen"),
    GermanCrosswordEntry("STOLZ", "Gefühl nach einem Erfolg"),
    GermanCrosswordEntry("HOFFNUNG", "Zuversicht auf Besseres"),
    GermanCrosswordEntry("GEDULD", "Fähigkeit zu warten"),
    GermanCrosswordEntry("FLEISS", "Eifer bei der Arbeit"),
    GermanCrosswordEntry("TREUE", "Verlässliche Verbundenheit"),
    GermanCrosswordEntry("LUEGE", "Bewusst falsche Aussage"),
    GermanCrosswordEntry("WAHRHEIT", "Was den Tatsachen entspricht"),
    GermanCrosswordEntry("GEHEIMNIS", "Was niemand wissen soll"),
    GermanCrosswordEntry("WITZ", "Kurze lustige Geschichte"),
    GermanCrosswordEntry("LACHEN", "Ausdruck der Fröhlichkeit"),
    GermanCrosswordEntry("TRAENE", "Tropfen beim Weinen"),
    GermanCrosswordEntry("SCHLAF", "Nächtliche Ruhe"),
    GermanCrosswordEntry("IDEE", "Plötzlicher Gedanke"),
    GermanCrosswordEntry("PLAN", "Vorhaben für die Zukunft"),
    GermanCrosswordEntry("ZIEL", "Was man erreichen will"),
    GermanCrosswordEntry("WUNSCH", "Was man sich ersehnt"),
    GermanCrosswordEntry("FRIEDE", "Gegenteil von Krieg"),
    GermanCrosswordEntry("KRIEG", "Bewaffneter Konflikt"),
    GermanCrosswordEntry("FREIHEIT", "Recht, selbst zu entscheiden"),
    GermanCrosswordEntry("GESETZ", "Vom Staat erlassene Regel"),
    GermanCrosswordEntry("REGEL", "Vorschrift für das Verhalten"),
    GermanCrosswordEntry("STRAFE", "Folge eines Vergehens"),
    GermanCrosswordEntry("GERICHT", "Hier wird Recht gesprochen"),
    GermanCrosswordEntry("POLIZEI", "Sorgt für Sicherheit"),
    GermanCrosswordEntry("STEUER", "Abgabe an den Staat"),
    GermanCrosswordEntry("GELD", "Womit man bezahlt"),
    GermanCrosswordEntry("MUENZE", "Metallgeld"),
    GermanCrosswordEntry("SCHEIN", "Papiergeld"),
    GermanCrosswordEntry("BANK", "Hier liegt das Geld"),
    GermanCrosswordEntry("KASSE", "Hier wird im Laden bezahlt"),
    GermanCrosswordEntry("PREIS", "Was eine Ware kostet"),
    GermanCrosswordEntry("RABATT", "Nachlass auf den Preis"),
    GermanCrosswordEntry("RECHNUNG", "Zahlungsaufforderung"),
    GermanCrosswordEntry("VERTRAG", "Schriftliche Vereinbarung"),
    GermanCrosswordEntry("POSTKARTE", "Gruß aus dem Urlaub"),
    GermanCrosswordEntry("PAKET", "Wird von der Post geliefert"),
    GermanCrosswordEntry("ADRESSE", "Wohnort mit Straße und Nummer"),
    GermanCrosswordEntry("NAME", "Wie jemand heißt"),
    GermanCrosswordEntry("BUCHSTABE", "Zeichen im Alphabet"),
    GermanCrosswordEntry("ALPHABET", "Alle Buchstaben der Reihe nach"),
    GermanCrosswordEntry("SATZ", "Folge von Wörtern mit Punkt"),
    GermanCrosswordEntry("GESPRAECH", "Austausch von Worten"),
    GermanCrosswordEntry("FLUESTERN", "Sehr leise sprechen"),
    GermanCrosswordEntry("SIGNAL", "Zeichen zur Verständigung"),
    GermanCrosswordEntry("ZEICHEN", "Symbol mit Bedeutung"),
    GermanCrosswordEntry("SCHRIFT", "Geschriebene Zeichen"),
    GermanCrosswordEntry("DRUCK", "Vervielfältigung auf Papier"),
    GermanCrosswordEntry("NACHRICHT", "Neue Information"),
    GermanCrosswordEntry("RADIERGUMMI", "Entfernt Bleistiftspuren"),
    GermanCrosswordEntry("BLEISTIFT", "Schreibgerät mit Mine"),
    GermanCrosswordEntry("KLASSE", "Gruppe von Schülern"),
    GermanCrosswordEntry("SCHUELER", "Geht zur Schule"),
    GermanCrosswordEntry("PAUSE", "Unterbrechung im Unterricht"),
    GermanCrosswordEntry("AUFGABE", "Muss gelöst werden"),
    GermanCrosswordEntry("PRUEFUNG", "Test des Wissens"),
    GermanCrosswordEntry("STUDENT", "Studiert an der Hochschule"),
    GermanCrosswordEntry("WISSEN", "Gesamtheit der Kenntnisse"),
    GermanCrosswordEntry("LERNEN", "Sich Wissen aneignen"),
    GermanCrosswordEntry("FEE", "Zauberwesen mit Flügeln"),
    GermanCrosswordEntry("ELF", "Schlankes Fabelwesen"),
    GermanCrosswordEntry("GEIST", "Erscheinung aus dem Jenseits"),
    GermanCrosswordEntry("VAMPIR", "Beißt in den Hals"),
    GermanCrosswordEntry("GESPENST", "Weißes Schreckwesen"),
    GermanCrosswordEntry("EINHORN", "Pferd mit einem Horn"),
    GermanCrosswordEntry("TROLL", "Grobschlächtiges Fabelwesen"),
    GermanCrosswordEntry("THRON", "Sitz des Königs"),
    GermanCrosswordEntry("SCHWERT", "Waffe des Ritters"),
    GermanCrosswordEntry("SCHILD", "Schutz des Ritters"),
    GermanCrosswordEntry("RUESTUNG", "Panzerkleid des Ritters"),
    GermanCrosswordEntry("LANZE", "Lange Stoßwaffe"),
    GermanCrosswordEntry("BOGEN", "Waffe mit Pfeilen"),
    GermanCrosswordEntry("PFEIL", "Wird vom Bogen geschossen"),
    GermanCrosswordEntry("ZAUBERSTAB", "Werkzeug der Fee"),
    GermanCrosswordEntry("TRANK", "Getränk mit Zauberkraft"),
    GermanCrosswordEntry("ORAKEL", "Weissagung der Antike"),
    GermanCrosswordEntry("GOETTIN", "Weibliche Gottheit"),
    GermanCrosswordEntry("TEMPEL", "Heiliges Gebäude der Antike"),
    GermanCrosswordEntry("PYRAMIDE", "Grabmal der Pharaonen"),
    GermanCrosswordEntry("PHARAO", "Herrscher im alten Ägypten"),
    GermanCrosswordEntry("MUMIE", "Einbalsamierter Leichnam"),
    GermanCrosswordEntry("SPHINX", "Wesen mit Löwenleib"),
    GermanCrosswordEntry("LABYRINTH", "Irrgarten mit vielen Wegen"),
)
