package org.lerchenflo.schneaggchatv3mp.games.presentation.crossword

/**
 * Word/clue pool for the locally generated German daily crossword.
 * Words are A-Z only (crossword convention: Ä→AE, Ö→OE, Ü→UE, ß→SS);
 * clues keep normal German spelling. Content lives in code like the other
 * game word lists (Morse, Undercover) — not in string resources.
 */
data class GermanCrosswordEntry(
    val word: String,
    val clue: String,
)

val germanCrosswordWords: List<GermanCrosswordEntry> = listOf(
    GermanCrosswordEntry("DONAU", "Fluss durch Wien"),
    GermanCrosswordEntry("RHEIN", "Fluss durch Köln"),
    GermanCrosswordEntry("ALPEN", "Höchstes Gebirge Europas"),
    GermanCrosswordEntry("BERLIN", "Hauptstadt Deutschlands"),
    GermanCrosswordEntry("WIEN", "Hauptstadt Österreichs"),
    GermanCrosswordEntry("BERN", "Hauptstadt der Schweiz"),
    GermanCrosswordEntry("ROM", "Hauptstadt Italiens"),
    GermanCrosswordEntry("PARIS", "Stadt an der Seine"),
    GermanCrosswordEntry("TIROL", "Bundesland mit Innsbruck"),
    GermanCrosswordEntry("BREGENZ", "Hauptstadt Vorarlbergs"),
    GermanCrosswordEntry("BODENSEE", "See zwischen drei Ländern"),
    GermanCrosswordEntry("EUROPA", "Kontinent mit Deutschland"),
    GermanCrosswordEntry("AFRIKA", "Kontinent mit der Sahara"),
    GermanCrosswordEntry("ASIEN", "Größter Kontinent"),
    GermanCrosswordEntry("NIL", "Längster Fluss Afrikas"),
    GermanCrosswordEntry("SAHARA", "Größte Wüste der Erde"),
    GermanCrosswordEntry("INSEL", "Land, das von Wasser umgeben ist"),
    GermanCrosswordEntry("VULKAN", "Feuerspeiender Berg"),
    GermanCrosswordEntry("GLETSCHER", "Ewiges Eis im Gebirge"),
    GermanCrosswordEntry("WUESTE", "Sehr trockene Landschaft"),
    GermanCrosswordEntry("OZEAN", "Weltmeer"),
    GermanCrosswordEntry("EBBE", "Niedrigwasser am Meer"),
    GermanCrosswordEntry("FLUT", "Hochwasser am Meer"),
    GermanCrosswordEntry("HAFEN", "Anlegestelle für Schiffe"),
    GermanCrosswordEntry("ANKER", "Hält das Schiff an Ort und Stelle"),
    GermanCrosswordEntry("SEGEL", "Windfänger am Boot"),
    GermanCrosswordEntry("KOMPASS", "Zeigt immer nach Norden"),
    GermanCrosswordEntry("NORDEN", "Himmelsrichtung mit Polarstern"),
    GermanCrosswordEntry("SUEDEN", "Himmelsrichtung Richtung Mittag"),
    GermanCrosswordEntry("OSTEN", "Himmelsrichtung des Sonnenaufgangs"),
    GermanCrosswordEntry("WESTEN", "Himmelsrichtung des Sonnenuntergangs"),
    GermanCrosswordEntry("SONNE", "Stern im Zentrum unseres Systems"),
    GermanCrosswordEntry("MOND", "Erdtrabant"),
    GermanCrosswordEntry("STERN", "Leuchtet am Nachthimmel"),
    GermanCrosswordEntry("PLANET", "Erde, Mars oder Venus"),
    GermanCrosswordEntry("MARS", "Roter Planet"),
    GermanCrosswordEntry("VENUS", "Planet und römische Liebesgöttin"),
    GermanCrosswordEntry("KOMET", "Schweifstern"),
    GermanCrosswordEntry("RAKETE", "Fahrzeug für den Weltraum"),
    GermanCrosswordEntry("WOLKE", "Schwebt am Himmel und bringt Regen"),
    GermanCrosswordEntry("REGEN", "Wasser vom Himmel"),
    GermanCrosswordEntry("SCHNEE", "Weiße Winterpracht"),
    GermanCrosswordEntry("NEBEL", "Trübt die Sicht am Morgen"),
    GermanCrosswordEntry("BLITZ", "Grelles Leuchten beim Gewitter"),
    GermanCrosswordEntry("DONNER", "Grollen nach dem Blitz"),
    GermanCrosswordEntry("STURM", "Sehr starker Wind"),
    GermanCrosswordEntry("FROST", "Temperatur unter null Grad"),
    GermanCrosswordEntry("SOMMER", "Wärmste Jahreszeit"),
    GermanCrosswordEntry("WINTER", "Kälteste Jahreszeit"),
    GermanCrosswordEntry("HERBST", "Jahreszeit des Laubfalls"),
    GermanCrosswordEntry("APRIL", "Monat, der macht, was er will"),
    GermanCrosswordEntry("MONTAG", "Erster Tag der Arbeitswoche"),
    GermanCrosswordEntry("FREITAG", "Letzter Arbeitstag vor dem Wochenende"),
    GermanCrosswordEntry("ADLER", "Wappenvogel vieler Länder"),
    GermanCrosswordEntry("AMSEL", "Schwarzer Singvogel"),
    GermanCrosswordEntry("EULE", "Nachtaktiver Vogel"),
    GermanCrosswordEntry("PINGUIN", "Frackträger der Antarktis"),
    GermanCrosswordEntry("DELFIN", "Kluger Meeressäuger"),
    GermanCrosswordEntry("WAL", "Größtes Tier der Erde"),
    GermanCrosswordEntry("HAI", "Gefürchteter Meeresräuber"),
    GermanCrosswordEntry("FORELLE", "Fisch aus Schuberts Quintett"),
    GermanCrosswordEntry("BIENE", "Fleißige Honigmacherin"),
    GermanCrosswordEntry("AMEISE", "Fleißiges Krabbeltier im Staat"),
    GermanCrosswordEntry("SPINNE", "Achtbeiniger Netzbauer"),
    GermanCrosswordEntry("IGEL", "Stacheliger Gartenbewohner"),
    GermanCrosswordEntry("FUCHS", "Schlauer Waldbewohner"),
    GermanCrosswordEntry("WOLF", "Wilder Verwandter des Hundes"),
    GermanCrosswordEntry("BAER", "Meister Petz"),
    GermanCrosswordEntry("HIRSCH", "Waldtier mit Geweih"),
    GermanCrosswordEntry("REH", "Scheues Waldtier"),
    GermanCrosswordEntry("HASE", "Langohr auf dem Feld"),
    GermanCrosswordEntry("PFERD", "Reittier mit Mähne"),
    GermanCrosswordEntry("ESEL", "Grautier mit langen Ohren"),
    GermanCrosswordEntry("ZIEGE", "Meckerndes Haustier"),
    GermanCrosswordEntry("SCHAF", "Liefert Wolle"),
    GermanCrosswordEntry("KUH", "Gibt Milch"),
    GermanCrosswordEntry("KAMEL", "Wüstenschiff"),
    GermanCrosswordEntry("LOEWE", "König der Tiere"),
    GermanCrosswordEntry("TIGER", "Gestreifte Raubkatze"),
    GermanCrosswordEntry("ZEBRA", "Gestreiftes Steppentier"),
    GermanCrosswordEntry("GIRAFFE", "Tier mit dem längsten Hals"),
    GermanCrosswordEntry("ELEFANT", "Dickhäuter mit Rüssel"),
    GermanCrosswordEntry("AFFE", "Kletterkünstler im Dschungel"),
    GermanCrosswordEntry("SCHLANGE", "Kriechtier ohne Beine"),
    GermanCrosswordEntry("EIDECHSE", "Flinkes Reptil auf sonnigen Steinen"),
    GermanCrosswordEntry("FROSCH", "Quakender Teichbewohner"),
    GermanCrosswordEntry("EICHE", "Baum mit Eicheln"),
    GermanCrosswordEntry("BIRKE", "Baum mit weißer Rinde"),
    GermanCrosswordEntry("TANNE", "Beliebter Weihnachtsbaum"),
    GermanCrosswordEntry("AHORN", "Baum im kanadischen Wappen"),
    GermanCrosswordEntry("LINDE", "Baum vieler Dorfplätze"),
    GermanCrosswordEntry("ROSE", "Blume mit Dornen"),
    GermanCrosswordEntry("TULPE", "Blume aus Holland"),
    GermanCrosswordEntry("NELKE", "Blume und Gewürz"),
    GermanCrosswordEntry("VEILCHEN", "Blaue Frühlingsblume"),
    GermanCrosswordEntry("KLEE", "Glücksbringer mit vier Blättern"),
    GermanCrosswordEntry("MOOS", "Weicher grüner Waldteppich"),
    GermanCrosswordEntry("PILZ", "Wächst nach dem Regen im Wald"),
    GermanCrosswordEntry("APFEL", "Frucht vom Baum der Erkenntnis"),
    GermanCrosswordEntry("BIRNE", "Frucht und Glühlampe"),
    GermanCrosswordEntry("KIRSCHE", "Kleine rote Steinfrucht"),
    GermanCrosswordEntry("TRAUBE", "Frucht für den Wein"),
    GermanCrosswordEntry("ZITRONE", "Saure gelbe Frucht"),
    GermanCrosswordEntry("ORANGE", "Apfelsine"),
    GermanCrosswordEntry("BANANE", "Krumme gelbe Frucht"),
    GermanCrosswordEntry("ANANAS", "Tropenfrucht mit Blätterkrone"),
    GermanCrosswordEntry("MELONE", "Große Sommerfrucht und Hutform"),
    GermanCrosswordEntry("ERDBEERE", "Rote Frucht mit Kernen außen"),
    GermanCrosswordEntry("GURKE", "Grünes Salatgemüse"),
    GermanCrosswordEntry("TOMATE", "Rotes Salatgemüse"),
    GermanCrosswordEntry("KAROTTE", "Lieblingsgemüse der Hasen"),
    GermanCrosswordEntry("ZWIEBEL", "Gemüse, das zum Weinen bringt"),
    GermanCrosswordEntry("KARTOFFEL", "Erdapfel"),
    GermanCrosswordEntry("SALAT", "Grünes Blattgemüse"),
    GermanCrosswordEntry("HONIG", "Süßes Bienenprodukt"),
    GermanCrosswordEntry("ZUCKER", "Süßungsmittel"),
    GermanCrosswordEntry("SALZ", "Weißes Gold der Küche"),
    GermanCrosswordEntry("PFEFFER", "Scharfes schwarzes Gewürz"),
    GermanCrosswordEntry("SENF", "Gelbe Würzpaste"),
    GermanCrosswordEntry("BUTTER", "Streichfett aus Milch"),
    GermanCrosswordEntry("KAESE", "Reift mit Löchern im Laib"),
    GermanCrosswordEntry("BROT", "Grundnahrungsmittel vom Bäcker"),
    GermanCrosswordEntry("KUCHEN", "Süßes Gebäck zum Kaffee"),
    GermanCrosswordEntry("TORTE", "Festliches Schichtgebäck"),
    GermanCrosswordEntry("NUDEL", "Teigware"),
    GermanCrosswordEntry("REIS", "Grundnahrungsmittel Asiens"),
    GermanCrosswordEntry("SUPPE", "Flüssige Vorspeise"),
    GermanCrosswordEntry("KAFFEE", "Schwarzes Wachmacher-Getränk"),
    GermanCrosswordEntry("TEE", "Aufgussgetränk"),
    GermanCrosswordEntry("SAFT", "Gepresstes Fruchtgetränk"),
    GermanCrosswordEntry("WEIN", "Getränk aus Trauben"),
    GermanCrosswordEntry("BIER", "Getränk aus Hopfen und Malz"),
    GermanCrosswordEntry("MILCH", "Weißes Getränk von der Kuh"),
    GermanCrosswordEntry("WASSER", "H2O"),
    GermanCrosswordEntry("GEIGE", "Streichinstrument"),
    GermanCrosswordEntry("KLAVIER", "Tasteninstrument"),
    GermanCrosswordEntry("TROMPETE", "Blechblasinstrument"),
    GermanCrosswordEntry("FLOETE", "Holzblasinstrument"),
    GermanCrosswordEntry("HARFE", "Zupfinstrument mit vielen Saiten"),
    GermanCrosswordEntry("TROMMEL", "Schlaginstrument"),
    GermanCrosswordEntry("OPER", "Musiktheater"),
    GermanCrosswordEntry("CHOR", "Singende Gemeinschaft"),
    GermanCrosswordEntry("MOZART", "Komponist der Zauberflöte"),
    GermanCrosswordEntry("GOETHE", "Dichter des Faust"),
    GermanCrosswordEntry("SCHILLER", "Dichter der Räuber"),
    GermanCrosswordEntry("MUSEUM", "Haus für Kunst und Geschichte"),
    GermanCrosswordEntry("THEATER", "Haus der Schauspielkunst"),
    GermanCrosswordEntry("KINO", "Haus der bewegten Bilder"),
    GermanCrosswordEntry("BUCH", "Gedrucktes Lesewerk"),
    GermanCrosswordEntry("ROMAN", "Langes Erzählwerk"),
    GermanCrosswordEntry("MAERCHEN", "Es war einmal..."),
    GermanCrosswordEntry("RAETSEL", "Knifflige Denkaufgabe"),
    GermanCrosswordEntry("SCHACH", "Königliches Brettspiel"),
    GermanCrosswordEntry("DAME", "Brettspiel und Spielkarte"),
    GermanCrosswordEntry("WUERFEL", "Sechsseitiger Spielstein"),
    GermanCrosswordEntry("TENNIS", "Sport mit Schläger und Filzball"),
    GermanCrosswordEntry("FUSSBALL", "Beliebtester Sport der Welt"),
    GermanCrosswordEntry("TOR", "Ziel beim Fußball"),
    GermanCrosswordEntry("SKI", "Bretter für den Schnee"),
    GermanCrosswordEntry("RODEL", "Schlitten"),
    GermanCrosswordEntry("MARATHON", "Lauf über 42 Kilometer"),
    GermanCrosswordEntry("STADION", "Große Sportarena"),
    GermanCrosswordEntry("MEDAILLE", "Auszeichnung für Sieger"),
    GermanCrosswordEntry("ARZT", "Doktor im Krankenhaus"),
    GermanCrosswordEntry("LEHRER", "Unterrichtet in der Schule"),
    GermanCrosswordEntry("BAECKER", "Backt Brot und Semmeln"),
    GermanCrosswordEntry("KOCH", "Meister in der Küche"),
    GermanCrosswordEntry("PILOT", "Steuert das Flugzeug"),
    GermanCrosswordEntry("RICHTER", "Spricht Recht im Gericht"),
    GermanCrosswordEntry("CLOWN", "Spaßmacher im Zirkus"),
    GermanCrosswordEntry("SCHULE", "Ort des Lernens"),
    GermanCrosswordEntry("TAFEL", "Schreibfläche im Klassenzimmer"),
    GermanCrosswordEntry("KREIDE", "Schreibstift für die Tafel"),
    GermanCrosswordEntry("HEFT", "Schreibblock für die Schule"),
    GermanCrosswordEntry("FERIEN", "Schulfreie Zeit"),
    GermanCrosswordEntry("ZEUGNIS", "Notenblatt am Schuljahresende"),
    GermanCrosswordEntry("FENSTER", "Glasöffnung in der Wand"),
    GermanCrosswordEntry("TUER", "Eingang zum Zimmer"),
    GermanCrosswordEntry("DACH", "Oberster Abschluss des Hauses"),
    GermanCrosswordEntry("KELLER", "Raum unter dem Haus"),
    GermanCrosswordEntry("KAMIN", "Offene Feuerstelle im Haus"),
    GermanCrosswordEntry("TREPPE", "Verbindet Stockwerke"),
    GermanCrosswordEntry("GARTEN", "Grünes Reich hinter dem Haus"),
    GermanCrosswordEntry("ZAUN", "Grenze um den Garten"),
    GermanCrosswordEntry("BRUNNEN", "Wasserquelle auf dem Dorfplatz"),
    GermanCrosswordEntry("KERZE", "Spendet Licht mit Docht und Wachs"),
    GermanCrosswordEntry("LAMPE", "Elektrische Lichtquelle"),
    GermanCrosswordEntry("SPIEGEL", "Zeigt das eigene Bild"),
    GermanCrosswordEntry("TEPPICH", "Weicher Bodenbelag"),
    GermanCrosswordEntry("SOFA", "Bequemes Sitzmöbel"),
    GermanCrosswordEntry("REGAL", "Möbel für Bücher"),
    GermanCrosswordEntry("SCHRANK", "Möbel für Kleidung"),
    GermanCrosswordEntry("KISSEN", "Weiche Kopfunterlage"),
    GermanCrosswordEntry("DECKE", "Wärmt im Bett"),
    GermanCrosswordEntry("WECKER", "Klingelt am Morgen"),
    GermanCrosswordEntry("SCHERE", "Werkzeug zum Schneiden"),
    GermanCrosswordEntry("HAMMER", "Werkzeug zum Nageln"),
    GermanCrosswordEntry("SAEGE", "Werkzeug mit Zähnen"),
    GermanCrosswordEntry("NAGEL", "Wird in die Wand geschlagen"),
    GermanCrosswordEntry("LEITER", "Hilft beim Hochklettern"),
    GermanCrosswordEntry("EIMER", "Gefäß mit Henkel"),
    GermanCrosswordEntry("BESEN", "Kehrgerät"),
    GermanCrosswordEntry("SEIFE", "Schäumt beim Händewaschen"),
    GermanCrosswordEntry("KAMM", "Ordnet die Haare"),
    GermanCrosswordEntry("BRILLE", "Sehhilfe auf der Nase"),
    GermanCrosswordEntry("HUT", "Kopfbedeckung"),
    GermanCrosswordEntry("SCHAL", "Wärmt den Hals"),
    GermanCrosswordEntry("MANTEL", "Langes Kleidungsstück für kalte Tage"),
    GermanCrosswordEntry("STIEFEL", "Hoher Schuh"),
    GermanCrosswordEntry("KNOPF", "Verschluss am Hemd"),
    GermanCrosswordEntry("TASCHE", "Behältnis zum Tragen"),
    GermanCrosswordEntry("KOFFER", "Reisegepäck"),
    GermanCrosswordEntry("ZUG", "Fährt auf Schienen"),
    GermanCrosswordEntry("GLEIS", "Schienenweg am Bahnhof"),
    GermanCrosswordEntry("AMPEL", "Regelt den Verkehr mit drei Farben"),
    GermanCrosswordEntry("REIFEN", "Rundes Gummiteil am Auto"),
    GermanCrosswordEntry("MOTOR", "Antrieb des Autos"),
    GermanCrosswordEntry("TANKEN", "Kraftstoff nachfüllen"),
    GermanCrosswordEntry("FAEHRE", "Schiff für die Überfahrt"),
    GermanCrosswordEntry("BRUECKE", "Führt über den Fluss"),
    GermanCrosswordEntry("TUNNEL", "Weg durch den Berg"),
    GermanCrosswordEntry("STRASSE", "Weg für Autos"),
    GermanCrosswordEntry("PLATZ", "Freie Fläche in der Stadt"),
    GermanCrosswordEntry("TURM", "Hohes schmales Bauwerk"),
    GermanCrosswordEntry("BURG", "Mittelalterliche Festung"),
    GermanCrosswordEntry("SCHLOSS", "Prunkbau und Türverriegelung"),
    GermanCrosswordEntry("KIRCHE", "Gotteshaus mit Glockenturm"),
    GermanCrosswordEntry("GLOCKE", "Läutet im Kirchturm"),
    GermanCrosswordEntry("KOENIG", "Herrscher mit Krone"),
    GermanCrosswordEntry("KRONE", "Kopfschmuck des Königs"),
    GermanCrosswordEntry("RITTER", "Kämpfer in Rüstung"),
    GermanCrosswordEntry("DRACHE", "Feuerspeiendes Fabelwesen"),
    GermanCrosswordEntry("ZWERG", "Kleiner Märchengeselle"),
    GermanCrosswordEntry("RIESE", "Großer Märchengeselle"),
    GermanCrosswordEntry("HEXE", "Reitet auf dem Besen"),
    GermanCrosswordEntry("ZAUBER", "Magisches Kunststück"),
    GermanCrosswordEntry("SCHATZ", "Vergrabene Kostbarkeit"),
    GermanCrosswordEntry("GOLD", "Edles gelbes Metall"),
    GermanCrosswordEntry("SILBER", "Edles weißes Metall"),
    GermanCrosswordEntry("EISEN", "Metall für Stahl"),
    GermanCrosswordEntry("DIAMANT", "Härtester Edelstein"),
    GermanCrosswordEntry("PERLE", "Schmuck aus der Muschel"),
    GermanCrosswordEntry("RING", "Schmuck am Finger"),
    GermanCrosswordEntry("KETTE", "Schmuck um den Hals"),
    GermanCrosswordEntry("UHR", "Zeigt die Zeit"),
    GermanCrosswordEntry("SEKUNDE", "Kürzeste gängige Zeiteinheit"),
    GermanCrosswordEntry("STUNDE", "Sechzig Minuten"),
    GermanCrosswordEntry("JAHR", "Zwölf Monate"),
    GermanCrosswordEntry("ZAHL", "Mathematisches Zeichen"),
    GermanCrosswordEntry("NULL", "Zahl ohne Wert"),
    GermanCrosswordEntry("DUTZEND", "Zwölf Stück"),
    GermanCrosswordEntry("KREIS", "Runde geometrische Form"),
    GermanCrosswordEntry("DREIECK", "Form mit drei Ecken"),
    GermanCrosswordEntry("QUADRAT", "Form mit vier gleichen Seiten"),
    GermanCrosswordEntry("LINEAL", "Hilfsmittel für gerade Linien"),
    GermanCrosswordEntry("ZIRKEL", "Zeichengerät für Kreise"),
    GermanCrosswordEntry("ATOM", "Kleinster Baustein der Elemente"),
    GermanCrosswordEntry("ENERGIE", "Kraft zum Arbeiten"),
    GermanCrosswordEntry("STROM", "Elektrizität oder großer Fluss"),
    GermanCrosswordEntry("MAGNET", "Zieht Eisen an"),
    GermanCrosswordEntry("LUPE", "Vergrößerungsglas"),
    GermanCrosswordEntry("MIKROSKOP", "Gerät für winzig Kleines"),
    GermanCrosswordEntry("TELESKOP", "Gerät für den Sternenhimmel"),
    GermanCrosswordEntry("ROBOTER", "Maschinenmensch"),
    GermanCrosswordEntry("COMPUTER", "Elektronischer Rechner"),
    GermanCrosswordEntry("TASTATUR", "Eingabegerät mit Tasten"),
    GermanCrosswordEntry("BILDSCHIRM", "Anzeigefläche des Computers"),
    GermanCrosswordEntry("INTERNET", "Weltweites Datennetz"),
    GermanCrosswordEntry("EMAIL", "Elektronische Post"),
    GermanCrosswordEntry("HANDY", "Mobiltelefon"),
    GermanCrosswordEntry("AKKU", "Wiederaufladbare Batterie"),
    GermanCrosswordEntry("FOTO", "Aufnahme mit der Kamera"),
    GermanCrosswordEntry("RADIO", "Gerät für Hörfunk"),
    GermanCrosswordEntry("ANTENNE", "Empfängt Funkwellen"),
    GermanCrosswordEntry("ZEITUNG", "Tägliches Nachrichtenblatt"),
    GermanCrosswordEntry("BRIEF", "Post im Umschlag"),
    GermanCrosswordEntry("MARKE", "Klebt auf dem Briefumschlag"),
    GermanCrosswordEntry("STEMPEL", "Drückt Tinte aufs Papier"),
    GermanCrosswordEntry("TINTE", "Flüssigkeit im Füller"),
    GermanCrosswordEntry("PAPIER", "Beschreibbarer Bogen"),
    GermanCrosswordEntry("FEDER", "Historisches Schreibgerät vom Vogel"),
    GermanCrosswordEntry("PINSEL", "Werkzeug des Malers"),
    GermanCrosswordEntry("FARBE", "Rot, Gelb oder Blau"),
    GermanCrosswordEntry("BILD", "Hängt gerahmt an der Wand"),
    GermanCrosswordEntry("RAHMEN", "Fasst das Bild ein"),
    GermanCrosswordEntry("SCHATTEN", "Dunkler Begleiter bei Sonne"),
    GermanCrosswordEntry("ECHO", "Widerhall im Gebirge"),
    GermanCrosswordEntry("TRAUM", "Nächtliches Kopfkino"),
    GermanCrosswordEntry("GLUECK", "Gegenteil von Pech"),
    GermanCrosswordEntry("MUT", "Tapferkeit"),
    GermanCrosswordEntry("RUHE", "Stille und Frieden"),
    GermanCrosswordEntry("LAERM", "Störender Krach"),
    GermanCrosswordEntry("DUFT", "Angenehmer Geruch"),
    GermanCrosswordEntry("GERUCH", "Wahrnehmung der Nase"),
    GermanCrosswordEntry("STIMME", "Klang beim Sprechen"),
    GermanCrosswordEntry("SPRACHE", "Deutsch oder Italienisch"),
    GermanCrosswordEntry("WORT", "Baustein des Satzes"),
    GermanCrosswordEntry("SILBE", "Teil eines Wortes"),
    GermanCrosswordEntry("FRAGE", "Satz mit Fragezeichen"),
    GermanCrosswordEntry("ANTWORT", "Erwiderung auf eine Frage"),
)
